// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

export 'initialize.dart';
export 'update_profile.dart';
export 'add_tag.dart';
export 'remove_tag.dart';
export 'fetch.dart';
