// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/profile_program.dart';

final class InitializeCommand extends Command<void> {
  InitializeCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption('name', mandatory: true, help: "name")
      ..addOption('bio', mandatory: true, help: "bio")
      ..addOption('authority', mandatory: false, help: "The wallet creating the profile. Pays for account creation and becomes [default: payer]")
      ..addOption('profile', mandatory: true, help: "The profile PDA account (must be empty — not yet created)");
  }

  @override
  String get name => 'initialize';

  @override
  String get description => "Instruction data for `Initialize`.  Contains the PDA bump seed and bounded initial name and bio.";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final profile = pubkey('--profile', results['profile']! as String);
    final bumpValue = integer('--bump', results['bump']! as String);
    final nameValue = results['name']! as String;
    final bioValue = results['bio']! as String;
    final instruction = getInitializeInstruction(
      programAddress: context.programAddress,
      authority: authority,
      profile: profile,
      systemProgram: Address('11111111111111111111111111111111'),
      bump: bumpValue,
      name: nameValue,
      bio: bioValue,
    );
    await context.send([instruction]);
  }
}
