//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use optional_accounts_program_client;
use serde_json::Value;
use serde_json::json;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Subcommand)]
pub enum Command {
	/// On-chain store state touched through the optional mutable slot.
	///
	/// Layout (10 bytes): 1 discriminator + 1 bump + 8 count.
	StoreState(StoreStateArgs),
}

#[derive(Debug, Args)]
pub struct StoreStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `authority`.
	#[arg(long)]
	authority: Option<String>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::StoreState(args) => fetch_store_state(context, args),
	}
}

fn fetch_store_state(context: &CliContext, args: StoreStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let authority = match &args.authority {
				Some(value) => CliContext::pubkey("--authority", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "store-state".to_string(),
						seed: "--authority".to_string(),
					});
				}
			};
			let seeds: &[&[u8]] = &["store".as_bytes(), authority.as_ref()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match optional_accounts_program_client::accounts::StoreState::from_bytes(&data) {
		Ok(account) => store_state_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "store-state", &address, &value);
	Ok(())
}

fn store_state_json(account: &optional_accounts_program_client::accounts::StoreStateZc) -> Value {
	json!({
		"bump": account.bump,
		"count": account.count.get(),
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
