// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/optional_accounts_program.dart';

final class InitCommand extends Command<void> {
  InitCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption(
        'authority',
        mandatory: false,
        help:
            "Pays for account creation and seeds the store PDA [default: payer]",
      )
      ..addOption(
        'store',
        mandatory: false,
        help:
            "The store PDA account (must be empty — not yet created) [default: derived]",
      );
  }

  @override
  String get name => 'init';

  @override
  String get description => "init";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final store = (results['store'] as String?) != null
        ? pubkey('--store', results['store']! as String)
        : (await findStorePda(
            seeds: StoreSeeds(authority: authority),
            programAddress: context.programAddress,
          )).$1;
    final bumpValue = integer('--bump', results['bump']! as String);
    final instruction = getInitInstruction(
      programAddress: context.programAddress,
      authority: authority,
      store: store,
      systemProgram: Address('11111111111111111111111111111111'),
      bump: bumpValue,
    );
    await context.send([instruction]);
  }
}
