// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/optional_accounts_program.dart';

final class NoteCommand extends Command<void> {
  NoteCommand() {
    argParser
      ..addOption('authority', mandatory: false, help: "The transaction fee payer; always required [default: payer]")
      ..addOption('note', mandatory: true, help: "An arbitrary readonly account attached as context");
  }

  @override
  String get name => 'note';

  @override
  String get description => "note";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final note = pubkey('--note', results['note']! as String);

    final instruction = getNoteInstruction(
      programAddress: context.programAddress,
      authority: authority,
      note: note,
    );
    await context.send([instruction]);
  }
}
