//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

pub mod initialize;
pub mod realloc;
pub mod realloc2;

pub use initialize::InitializeArgs;
pub use realloc::ReallocArgs;
pub use realloc2::Realloc2Args;
