//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments,
	rustdoc::broken_intra_doc_links
)]

use account_realloc_program_client::instructions::Realloc2;
use account_realloc_program_client::instructions::Realloc2InstructionData;
use clap::Args;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct Realloc2Args {
	#[arg(long)]
	len: u16,
	/// The `sample1` account [default: derived]
	#[arg(long)]
	sample1: Option<String>,
	/// The `sample2` account [default: derived]
	#[arg(long)]
	sample2: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: Realloc2Args) -> Result<(), CliError> {
	let authority = context.payer_pubkey();
	let sample1 = match &args.sample1 {
		Some(value) => CliContext::pubkey("--sample1", value)?,
		None => {
			Pubkey::find_program_address(
				&["sample".as_bytes(), authority.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let sample2 = match &args.sample2 {
		Some(value) => CliContext::pubkey("--sample2", value)?,
		None => {
			Pubkey::find_program_address(
				&["sample".as_bytes(), authority.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let data = Realloc2InstructionData::new(|data| {
		data.len.set(args.len);
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Realloc2 {
		authority,
		sample1,
		sample2,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
