//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: f844c00cea745fabf42ad27cde7edc32abecb0137ad6408c1441e4a4d2b306e1
// program-id: DCF5KBmtQ9ryDC7mQezKLwuJHem6coVUCmKkw37M9J4A
// version-type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "DCF5KBmtQ9ryDC7mQezKLwuJHem6coVUCmKkw37M9J4A";

/// ABI layout for the `HelloInstructionData` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "HelloInstructionData";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0964b5ff00a94fb98f2536839ca6abc68a04f31d844cbac2a3aa627a73eeca5a";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

