// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/todo_program.dart';

final class UpdateDigestCommand extends Command<void> {
  UpdateDigestCommand() {
    argParser
      ..addOption('digest', mandatory: true, help: "digest")
      ..addOption(
        'owner',
        mandatory: false,
        help: "The owner account [default: payer]",
      )
      ..addOption(
        'todo',
        mandatory: false,
        help: "The todo account [default: derived]",
      );
  }

  @override
  String get name => 'update_digest';

  @override
  String get description => "update_digest";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final owner = (results['owner'] as String?) != null
        ? pubkey('--owner', results['owner']! as String)
        : context.payerAddress;
    final todo = (results['todo'] as String?) != null
        ? pubkey('--todo', results['todo']! as String)
        : (await findTodoPda(
            seeds: TodoSeeds(owner: owner),
            programAddress: context.programAddress,
          )).$1;
    final digestValue = base58Bytes('--digest', results['digest']! as String);
    final instruction = getUpdateDigestInstruction(
      programAddress: context.programAddress,
      owner: owner,
      todo: todo,
      digest: digestValue,
    );
    await context.send([instruction]);
  }
}
