// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getCancelInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const cancelCommand = registerGlobals(new Command("cancel"))
	.description("cancel")
	.requiredOption("--mint <mint>", "The `mint` account")
	.requiredOption(
		"--vesting-state <vestingState>",
		"The `vesting_state` account",
	)
	.requiredOption("--admin-ata <adminAta>", "The `admin_ata` account")
	.requiredOption("--vault <vault>", "The `vault` account")
	.requiredOption(
		"--token-program <tokenProgram>",
		"The `token_program` account",
	)
	.requiredOption(
		"--clock <clock>",
		"Clock for the vested-entitlement settlement: cancellation must not",
	)
	.requiredOption(
		"--beneficiary-ata <beneficiaryAta>",
		"The beneficiary's ATA: the vested-but-unclaimed amount settles here",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			admin: context.payer,
			mint: pubkey("--mint", options.mint),
			vestingState: pubkey("--vesting-state", options.vestingState),
			adminAta: pubkey("--admin-ata", options.adminAta),
			vault: pubkey("--vault", options.vault),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
			clock: pubkey("--clock", options.clock),
			beneficiaryAta: pubkey("--beneficiary-ata", options.beneficiaryAta),
		};
		const instruction = getCancelInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
