// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getClaimInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const claimCommand = registerGlobals(new Command("claim"))
	.description("claim")
	.requiredOption("--amount <amount>", "amount")
	.option(
		"--beneficiary <beneficiary>",
		"The `beneficiary` account [default: payer]",
	)
	.requiredOption("--mint <mint>", "The `mint` account")
	.requiredOption(
		"--vesting-state <vestingState>",
		"The `vesting_state` account",
	)
	.requiredOption(
		"--beneficiary-ata <beneficiaryAta>",
		"The `beneficiary_ata` account",
	)
	.requiredOption("--vault <vault>", "The `vault` account")
	.requiredOption(
		"--token-program <tokenProgram>",
		"The `token_program` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			amount: bigInteger("--amount", options.amount),
			beneficiary: context.payer,
			mint: pubkey("--mint", options.mint),
			vestingState: pubkey("--vesting-state", options.vestingState),
			beneficiaryAta: pubkey("--beneficiary-ata", options.beneficiaryAta),
			vault: pubkey("--vault", options.vault),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
		};
		const instruction = getClaimInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
