[package]
name = "require_program_owned_before_lamport_mutation"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "6.0.4"

[dev-dependencies]
dylint_testing = "6.0.4"

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]
