[package]
name = "validation_program_cli"
version = "0.1.0"
edition = "2021"
publish = false
description = "Generated CLI for validationProgram"

[[bin]]
name = "validation-program-cli"
path = "src/main.rs"

[dependencies]
bs58 = { workspace = true, default-features = true }
clap = { workspace = true, default-features = true, features = ["derive", "std", "env"] }
serde_json = { workspace = true, default-features = true }
solana-rpc-client = { workspace = true, default-features = true }
solana-sdk = { workspace = true, default-features = true }
thiserror = { workspace = true, default-features = true }
validation-program-client = { path = "../../../rust/validation_program" }
