packages:
  - .
  - packages/*
  - codama/tests/js
  - codama/tests/litesvm
  - codama/tests/quasar-svm

allowBuilds:
  esbuild: true
  koffi: true

onlyBuiltDependencies:
  - esbuild
  - koffi

useNodeVersion: 24.13.0
