//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

//! Generated CLI for the `transferSolProgram` program.

mod commands;
mod context;
use clap::Parser;
use clap::Subcommand;
use context::CliContext;
use solana_sdk::pubkey::Pubkey;

/// Command-line interface for transferSolProgram
#[derive(Debug, Parser)]
#[command(name = "transfer-sol-program-cli", version = env!("CARGO_PKG_VERSION"), propagate_version = true)]
struct Cli {
	/// RPC endpoint: `mainnet`, `devnet`, `testnet`, `localhost`, or an https URL.
	#[arg(short = 'u', long, default_value = "devnet", env = "SOLANA_URL")]
	url: String,

	/// Payer keypair file in the standard Solana JSON byte-array format.
	#[arg(
		short = 'k',
		long,
		default_value = "~/.config/solana/id.json",
		env = "PINA_KEYPAIR"
	)]
	keypair: String,

	/// Override the on-chain program address.
	#[arg(long)]
	program_id: Option<String>,

	/// Simulate the transaction and print its logs instead of sending.
	#[arg(long)]
	simulate: bool,

	/// Print machine-readable JSON output.
	#[arg(long)]
	json: bool,

	#[command(subcommand)]
	command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
	/// Instruction data for `CpiTransfer`.
	///
	/// Layout:
	/// ```text
	/// | offset | size | field         |
	/// |--------|------|---------------|
	/// | 0      | 1    | discriminator |
	/// | 1      | 8    | amount (u64)  |
	/// ```
	CpiTransfer(commands::CpiTransferArgs),
	/// Instruction data for `DirectTransfer`.
	///
	/// Same layout as `CpiTransferInstruction` but with a different discriminator
	/// byte.
	DirectTransfer(commands::DirectTransferArgs),
}

fn main() {
	let cli = Cli::parse();
	if let Err(error) = run(cli) {
		eprintln!("error: {error}");
		std::process::exit(1);
	}
}

fn run(cli: Cli) -> Result<(), context::CliError> {
	let program_address = match &cli.program_id {
		Some(value) => CliContext::pubkey("--program-id", value)?,
		None => Pubkey::from_str_const("BuXKn8EiVMKF8zYThuea3xhLq3jUHTTwDDLfCoehq7WG"),
	};
	let context = CliContext::new(
		&cli.url,
		&cli.keypair,
		program_address,
		cli.simulate,
		cli.json,
	)?;

	match cli.command {
		Command::CpiTransfer(args) => commands::cpi_transfer::run(&context, args),
		Command::DirectTransfer(args) => commands::direct_transfer::run(&context, args),
	}
}
