//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use custom_errors_program_client::instructions::Hello;
use custom_errors_program_client::instructions::HelloInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct HelloArgs {}

pub(crate) fn run(context: &CliContext, _args: HelloArgs) -> Result<(), CliError> {
	let data = HelloInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Hello {};

	context.send(accounts.instruction(data))
}
