//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

pub mod hello;
pub mod hello_next;
pub mod hello_no_msg;
pub mod require_eq;
pub mod require_gt;
pub mod require_gte;
pub mod require_neq;

pub use hello::HelloArgs;
pub use hello_next::HelloNextArgs;
pub use hello_no_msg::HelloNoMsgArgs;
pub use require_eq::RequireEqArgs;
pub use require_gt::RequireGtArgs;
pub use require_gte::RequireGteArgs;
pub use require_neq::RequireNeqArgs;
