//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use custom_errors_program_client::instructions::RequireNeq;
use custom_errors_program_client::instructions::RequireNeqInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct RequireNeqArgs {}

pub(crate) fn run(context: &CliContext, args: RequireNeqArgs) -> Result<(), CliError> {
	let data = RequireNeqInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = RequireNeq {};

	context.send(accounts.instruction(data))
}
