// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'dart:typed_data';

import 'package:args/command_runner.dart';
import 'package:solana_kit_accounts/solana_kit_accounts.dart';
import 'package:solana_kit_rpc_types/solana_kit_rpc_types.dart' hide TransactionVersion;

import '../context.dart';
import 'package:pina_codama_clients/counter_program.dart';

final class FetchCounterStateCommand extends Command<void> {
  FetchCounterStateCommand() {
    argParser
      ..addOption('address', help: 'Account address; overrides PDA derivation.')
      ..addOption('authority', mandatory: true, help: "PDA seed `authority`.");
  }

  @override
  String get name => 'counter-state';

  @override
  String get description => "On-chain counter state.";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authorityValue = pubkey('--authority', results['authority']! as String);
    final address = (results['address'] as String?) != null
        ? pubkey('--address', results['address']! as String)
        : (await findCounterPda(
            seeds: CounterSeeds(
              authority: authorityValue,
            ),
            programAddress: context.programAddress,
          )).$1;
    final data = await context.fetchAccount(address);
    final encoded = Account<Uint8List>(
      address: address,
      data: data,
      executable: false,
      lamports: Lamports(BigInt.zero),
      programAddress: context.programAddress,
      space: BigInt.from(data.length),
    );
    final account = decodeCounterState(encoded);
    printFields(
      context.json,
      'counter-state',
      address,
      <String, Object?>{
        'bump': account.data.bump,
        'count': account.data.count,
      },
    );
  }
}

final class FetchCommand extends Command<void> {
  @override
  String get name => 'fetch';

  @override
  String get description => 'Fetch and decode program accounts.';
}
