//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use serde_json::Value;
use serde_json::json;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Subcommand)]
pub enum Command {
	VestingState(VestingStateArgs),
}

#[derive(Debug, Args)]
pub struct VestingStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `admin`.
	#[arg(long)]
	admin: Option<String>,
	/// PDA seed `beneficiary`.
	#[arg(long)]
	beneficiary: Option<String>,
	/// PDA seed `mint`.
	#[arg(long)]
	mint: Option<String>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::VestingState(args) => fetch_vesting_state(context, args),
	}
}

fn fetch_vesting_state(context: &CliContext, args: VestingStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let admin = match &args.admin {
				Some(value) => CliContext::pubkey("--admin", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "vesting-state".to_string(),
						seed: "--admin".to_string(),
					});
				}
			};
			let beneficiary = match &args.beneficiary {
				Some(value) => CliContext::pubkey("--beneficiary", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "vesting-state".to_string(),
						seed: "--beneficiary".to_string(),
					});
				}
			};
			let mint = match &args.mint {
				Some(value) => CliContext::pubkey("--mint", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "vesting-state".to_string(),
						seed: "--mint".to_string(),
					});
				}
			};
			let seeds: &[&[u8]] = &[
				"vesting".as_bytes(),
				admin.as_ref(),
				beneficiary.as_ref(),
				mint.as_ref(),
			];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match vesting_program_client::accounts::VestingState::from_bytes(&data) {
		Ok(account) => vesting_state_json(account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "vesting-state", &address, &value);
	Ok(())
}

fn vesting_state_json(account: &vesting_program_client::accounts::VestingStateZc) -> Value {
	json!({
		"admin": account.admin.to_string(),
		"beneficiary": account.beneficiary.to_string(),
		"mint": account.mint.to_string(),
		"total_amount": account.total_amount.get(),
		"claimed_amount": account.claimed_amount.get(),
		"start_ts": account.start_ts.get(),
		"cliff_ts": account.cliff_ts.get(),
		"end_ts": account.end_ts.get(),
		"cancelled": account.cancelled.get(),
		"bump": account.bump,
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
