// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { sysvarsCommand } from "./commands/sysvars.ts";

import { registerGlobals } from "./context.ts";

const program = registerGlobals(new Command())
	.name("sysvar-checks-program-cli")
	.version("0.1.0")
	.description("Command-line interface for sysvarChecksProgram");
program.addCommand(sysvarsCommand);
program.parseAsync(process.argv);
