//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use solana_sdk::pubkey::Pubkey;
use validation_program_client::instructions::CheckPolicy;
use validation_program_client::instructions::CheckPolicyInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct CheckPolicyArgs {
	#[arg(long)]
	amount: u64,
	#[arg(long)]
	memo: String,
	#[arg(long)]
	approvals: String,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `policy` account [default: derived]
	#[arg(long)]
	policy: Option<String>,
	/// A shared account may still require the transaction's writable flag
	#[arg(long)]
	audit: String,
}

pub(crate) fn run(context: &CliContext, args: CheckPolicyArgs) -> Result<(), CliError> {
	let approvals = CliContext::byte_vec("--approvals", &args.approvals)?;
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let policy = match &args.policy {
		Some(value) => CliContext::pubkey("--policy", value)?,
		None => {
			Pubkey::find_program_address(
				&["validation-policy".as_bytes(), authority.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let audit = CliContext::pubkey("--audit", &args.audit)?;
	let mut invalid: Option<String> = None;
	let data = CheckPolicyInstructionData::new(|data| {
		data.amount.set(args.amount);
		if let Err(error) = data.memo.try_set(&args.memo) {
			invalid = Some(format!("--memo: {error}"));
		}
		if let Err(error) = data.approvals.try_set_from_slice(&approvals) {
			invalid = Some(format!("--approvals: {error}"));
		}
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;
	if let Some(message) = invalid {
		return Err(CliError::InvalidData { message });
	}

	let accounts = CheckPolicy {
		authority,
		policy,
		audit,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
