//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

pub mod check_policy;
pub mod initialize_policy;

pub use check_policy::CheckPolicyArgs;
pub use initialize_policy::InitializePolicyArgs;
