//! Parsing and code generation for value validation annotations.

use darling::FromField;
use darling::FromMeta;
#[cfg(feature = "validation")]
use quote::quote;
use syn::Expr;
use syn::Fields;
use syn::Ident;
use syn::ItemStruct;
use syn::Type;

use crate::args::ValidationHook;

/// One `#[pina(validate(...))]` group on a schema field.
#[derive(Debug, FromMeta)]
#[cfg_attr(not(feature = "validation"), allow(dead_code))]
pub(crate) struct ValueValidation {
	min: Option<Expr>,
	max: Option<Expr>,
	min_len: Option<Expr>,
	max_len: Option<Expr>,
	exact_len: Option<Expr>,
	error: Option<Expr>,
}

/// Validation metadata parsed from one schema field.
#[derive(Debug, FromField)]
#[darling(attributes(pina))]
struct ValueField {
	ident: Option<Ident>,
	ty: Type,
	#[darling(multiple)]
	validate: Vec<ValueValidation>,
}

/// Validation target generated by `PinaPod` for a schema.
#[derive(Clone, Copy)]
#[cfg(feature = "validation")]
pub(crate) enum ValueTarget<'a> {
	Fixed(&'a Ident),
	Compact {
		target: &'a Ident,
		tails: &'a [crate::schema::CompactTail],
	},
}

/// Extract, validate, and remove schema-field helper attributes.
pub(crate) fn take_value_validations(
	item: &mut ItemStruct,
) -> syn::Result<Vec<(Ident, Type, Vec<ValueValidation>)>> {
	let Fields::Named(fields) = &mut item.fields else {
		// The schema validator owns the diagnostic for unsupported struct
		// shapes. Returning no field rules here preserves that more specific
		// error instead of reporting a validation error for a tuple or unit
		// struct that did not request validation.
		return Ok(Vec::new());
	};
	let mut result = Vec::with_capacity(fields.named.len());

	for field in &mut fields.named {
		let parsed = ValueField::from_field(field).map_err(|error| darling_to_syn(&error))?;
		let ident = parsed.ident.ok_or_else(|| {
			syn::Error::new_spanned(&*field, "validation annotations require a named field")
		})?;

		validate_value_groups(&ident, &parsed.ty, &parsed.validate)?;
		field
			.attrs
			.retain(|attribute| !attribute.path().is_ident("pina"));
		result.push((ident, parsed.ty, parsed.validate));
	}

	Ok(result)
}

/// Whether any field or type-level application validator was declared.
#[cfg(not(feature = "validation"))]
pub(crate) fn validation_requested(
	fields: &[(Ident, Type, Vec<ValueValidation>)],
	hook: Option<&ValidationHook>,
) -> bool {
	hook.is_some() || fields.iter().any(|(_, _, groups)| !groups.is_empty())
}

/// Generate the `PinaValidate` implementation for a fixed or compact view.
#[cfg(feature = "validation")]
pub(crate) fn generate_value_validation(
	crate_path: &syn::Path,
	target: ValueTarget<'_>,
	fields: &[(Ident, Type, Vec<ValueValidation>)],
	hook: Option<&ValidationHook>,
	default_error: &proc_macro2::TokenStream,
) -> proc_macro2::TokenStream {
	let mut validations = Vec::new();
	for (field, ty, groups) in fields {
		for group in groups {
			validations.extend(generate_value_group(
				field,
				ty,
				group,
				&target,
				default_error,
			));
		}
	}
	let hook = hook.map(|hook| {
		let with = &hook.with;

		quote! {
			#with(self)?;
		}
	});

	match target {
		ValueTarget::Fixed(target) => {
			quote! {
				impl #crate_path::PinaValidate for #target {
					#[inline]
					fn validate(&self) -> #crate_path::ProgramResult {
						#(#validations)*
						#hook

						Ok(())
					}
				}
			}
		}
		ValueTarget::Compact { target, .. } => {
			quote! {
				impl<'__pina_validation> #crate_path::PinaValidate
					for #target<'__pina_validation>
				{
					#[inline]
					fn validate(&self) -> #crate_path::ProgramResult {
						#(#validations)*
						#hook

						Ok(())
					}
				}
			}
		}
	}
}

/// Emit the feature-gate diagnostic before generated code can mention a
/// missing runtime trait.
#[cfg(not(feature = "validation"))]
pub(crate) fn feature_error(item: &ItemStruct) -> proc_macro2::TokenStream {
	syn::Error::new_spanned(
		&item.ident,
		"validation annotations require Pina's `validation` feature; enable it with `pina = { \
		 version = \"...\", features = [\"validation\"] }` (or enable `pina_macros/validation` \
		 when using the proc-macro crate directly)",
	)
	.to_compile_error()
}

/// Add the macro name and complete validation vocabulary to a Darling error.
pub(crate) fn attribute_error(
	error: &darling::Error,
	macro_name: &str,
) -> proc_macro2::TokenStream {
	let reason = darling_reason(error);
	let outer_arguments = if macro_name == "account" {
		"`discriminator = path`, `variant = name`, `crate = path`, `compact`, and `validate(with = \
		 function)`"
	} else {
		"`discriminator = path`, `variant = name`, `crate = path`, and `validate(with = function)`"
	};

	syn::Error::new(
		error.span(),
		format!(
			"invalid `#[{macro_name}(...)]` arguments: {reason} Supported outer arguments are \
			 {outer_arguments}. Supported field validation syntax is `#[pina(validate(min = EXPR, \
			 max = EXPR, min_len = EXPR, max_len = EXPR, exact_len = EXPR, error = ERROR))]`"
		),
	)
	.to_compile_error()
}

/// Format a Darling diagnostic as one sentence before adding corrective help.
pub(crate) fn darling_reason(error: &darling::Error) -> String {
	let mut reason = error.to_string();
	if !reason.ends_with(['.', '?', '!']) {
		reason.push('.');
	}

	reason
}

fn validate_value_groups(field: &Ident, ty: &Type, groups: &[ValueValidation]) -> syn::Result<()> {
	let mut seen_min = false;
	let mut seen_max = false;
	let mut seen_min_len = false;
	let mut seen_max_len = false;
	let mut seen_exact_len = false;

	for group in groups {
		let has_numeric = group.min.is_some() || group.max.is_some();
		let has_length_rule =
			group.min_len.is_some() || group.max_len.is_some() || group.exact_len.is_some();

		if !has_numeric && !has_length_rule {
			return Err(syn::Error::new_spanned(
				field,
				"empty `validate(...)` annotation; add `min`, `max`, `min_len`, `max_len`, or \
				 `exact_len`, or remove the annotation",
			));
		}

		if has_numeric && !is_integer(ty) {
			return Err(syn::Error::new_spanned(
				ty,
				format!(
					"`min` and `max` on field `{field}` require an integer field; supported types \
					 are the fixed-width signed and unsigned Rust integers and Pina `Pod*` \
					 integer types"
				),
			));
		}

		if has_length_rule && !has_length(ty) {
			return Err(syn::Error::new_spanned(
				ty,
				format!(
					"length validation on field `{field}` requires `String<N>`, `PodString<N, \
					 PFX>`, `Vec<T, N>`, `PodVec<T, N, PFX>`, or `[u8; N]`"
				),
			));
		}

		if group.exact_len.is_some() && (group.min_len.is_some() || group.max_len.is_some()) {
			return Err(syn::Error::new_spanned(
				field,
				"`exact_len` cannot be combined with `min_len` or `max_len` in the same \
				 validation group; use only `exact_len` for an exact-size rule",
			));
		}

		check_duplicate(&mut seen_min, group.min.as_ref(), "min", field)?;
		check_duplicate(&mut seen_max, group.max.as_ref(), "max", field)?;
		check_duplicate(&mut seen_min_len, group.min_len.as_ref(), "min_len", field)?;
		check_duplicate(&mut seen_max_len, group.max_len.as_ref(), "max_len", field)?;
		check_duplicate(
			&mut seen_exact_len,
			group.exact_len.as_ref(),
			"exact_len",
			field,
		)?;
	}

	Ok(())
}

fn check_duplicate(
	seen: &mut bool,
	value: Option<&Expr>,
	name: &str,
	field: &Ident,
) -> syn::Result<()> {
	if value.is_none() {
		return Ok(());
	}

	if *seen {
		return Err(syn::Error::new_spanned(
			field,
			format!(
				"duplicate `{name}` validation on field `{field}`; keep one rule so validation \
				 order and its error are unambiguous"
			),
		));
	}

	*seen = true;
	Ok(())
}

#[cfg(feature = "validation")]
fn generate_value_group(
	field: &Ident,
	ty: &Type,
	group: &ValueValidation,
	target: &ValueTarget<'_>,
	default_error: &proc_macro2::TokenStream,
) -> Vec<proc_macro2::TokenStream> {
	let error = group
		.error
		.as_ref()
		.map_or_else(|| quote!(#default_error), |error| quote!((#error).into()));
	let value = value_expression(field, ty, target);
	let length = length_expression(field, target);
	let mut checks = Vec::new();

	if let Some(min) = &group.min {
		checks.push(quote! {
			if #value < (#min) {
				return Err(#error);
			}
		});
	}

	if let Some(max) = &group.max {
		checks.push(quote! {
			if #value > (#max) {
				return Err(#error);
			}
		});
	}

	if let Some(min_len) = &group.min_len {
		checks.push(quote! {
			if #length < (#min_len) {
				return Err(#error);
			}
		});
	}

	if let Some(max_len) = &group.max_len {
		checks.push(quote! {
			if #length > (#max_len) {
				return Err(#error);
			}
		});
	}

	if let Some(exact_len) = &group.exact_len {
		checks.push(quote! {
			if #length != (#exact_len) {
				return Err(#error);
			}
		});
	}

	checks
}

#[cfg(feature = "validation")]
fn value_expression(
	field: &Ident,
	ty: &Type,
	target: &ValueTarget<'_>,
) -> proc_macro2::TokenStream {
	let name = last_type_name(ty).unwrap_or_default();
	let is_pod = name.starts_with("PodU") || name.starts_with("PodI");

	match target {
		ValueTarget::Fixed(_) if is_pod => quote!(self.#field().get()),
		ValueTarget::Fixed(_) => quote!(self.#field()),
		ValueTarget::Compact { .. } if matches!(name.as_str(), "u8" | "i8") => {
			quote!(self.#field)
		}
		ValueTarget::Compact { .. } => quote!(self.#field.get()),
	}
}

#[cfg(feature = "validation")]
fn length_expression(field: &Ident, target: &ValueTarget<'_>) -> proc_macro2::TokenStream {
	match target {
		ValueTarget::Fixed(_) => quote!(self.#field().len()),
		ValueTarget::Compact { tails, .. } if tails.iter().any(|tail| tail.name == *field) => {
			quote!(self.#field().len())
		}
		ValueTarget::Compact { .. } => quote!(self.#field.len()),
	}
}

fn is_integer(ty: &Type) -> bool {
	matches!(
		last_type_name(ty).as_deref(),
		Some(
			"u8" | "u16"
				| "u32" | "u64"
				| "u128" | "i8"
				| "i16" | "i32"
				| "i64" | "i128"
				| "PodU16" | "PodU32"
				| "PodU64" | "PodU128"
				| "PodI16" | "PodI32"
				| "PodI64" | "PodI128"
		)
	)
}

fn has_length(ty: &Type) -> bool {
	if matches!(ty, Type::Array(_)) {
		return true;
	}

	matches!(
		last_type_name(ty).as_deref(),
		Some("String" | "PodString" | "Vec" | "PodVec")
	)
}

fn last_type_name(ty: &Type) -> Option<String> {
	let Type::Path(path) = ty else {
		return None;
	};

	path.path
		.segments
		.last()
		.map(|segment| segment.ident.to_string())
}

fn darling_to_syn(error: &darling::Error) -> syn::Error {
	let reason = darling_reason(error);

	syn::Error::new(
		error.span(),
		format!(
			"invalid Pina validation annotation: {reason} Supported value rules are `min = EXPR`, \
			 `max = EXPR`, `min_len = EXPR`, `max_len = EXPR`, `exact_len = EXPR`, and `error = \
			 ERROR`"
		),
	)
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn rejects_numeric_validation_on_non_integer_fields() {
		let mut item: ItemStruct = syn::parse_quote! {
			struct Example {
				#[pina(validate(min = 1))]
				value: bool,
			}
		};
		let error = take_value_validations(&mut item).expect_err("bool must reject min");

		assert!(error.to_string().contains("require an integer field"));
	}

	#[test]
	fn reports_supported_rules_for_unknown_validation_names() {
		let mut item: ItemStruct = syn::parse_quote! {
			struct Example {
				#[pina(validate(mim = 1))]
				value: u64,
			}
		};
		let error = take_value_validations(&mut item).expect_err("typo must fail");
		let message = error.to_string();

		assert!(message.contains("invalid Pina validation annotation"));
		assert!(message.contains("Supported value rules"));
	}
}
