// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/sysvar_checks_program.dart';

final class SysvarsCommand extends Command<void> {
  SysvarsCommand() {
    argParser
      ..addOption('clock', mandatory: true, help: "The clock account")
      ..addOption('rent', mandatory: true, help: "The rent account")
      ..addOption('stake_history', mandatory: true, help: "The stake_history account");
  }

  @override
  String get name => 'sysvars';

  @override
  String get description => "sysvars";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final clock = pubkey('--clock', results['clock']! as String);
    final rent = pubkey('--rent', results['rent']! as String);
    final stakeHistory = pubkey('--stake-history', results['stake_history']! as String);

    final instruction = getSysvarsInstruction(
      programAddress: context.programAddress,
      clock: clock,
      rent: rent,
      stakeHistory: stakeHistory,
    );
    await context.send([instruction]);
  }
}
