//! Typed instruction construction helpers for client-side usage.
//!
//! This module provides lightweight utilities for building instruction data and
//! account metadata tuples from pina types. The helpers are `no_std` compatible
//! and work with any `HasDiscriminator + ZeroPodFixed<Zc = T>` type.
//!
//! # Account metadata helpers
//!
//! The free functions [`writable_signer`], [`writable`], [`readonly_signer`],
//! and [`readonly`] produce `(Address, bool, bool)` tuples suitable for passing
//! to instruction builders in downstream SDKs.
//!
//! # Instruction data
//!
//! [`InstructionBuilder::data`] returns the raw byte representation of a zero-copy
//! instruction struct (which already includes the discriminator as its first
//! field thanks to the `#[instruction]` macro).

use crate::Address;
use crate::HasDiscriminator;
use crate::ZeroPodFixed;

/// Builds instruction data for types that implement [`HasDiscriminator`] and
/// [`ZeroPodFixed`].
///
/// Because `#[instruction]` types already include the discriminator as their
/// first field, `data` simply returns the raw byte representation.
///
/// # Examples
///
/// ```ignore
/// use pina::HasDiscriminator;
/// use pina::transaction::InstructionBuilder;
///
/// // `MyInstruction` is generated by `#[instruction]`; it implements
/// // `HasDiscriminator` and `ZeroPodFixed<Zc = Self>`.
/// let ix = MyInstruction { /* ... */ };
/// let bytes = InstructionBuilder::<MyInstruction>::data(&ix);
/// assert_eq!(bytes[0], 1); // discriminator
/// assert_eq!(bytes.len(), core::mem::size_of::<MyInstruction>());
/// ```
pub struct InstructionBuilder<T: HasDiscriminator> {
	_marker: core::marker::PhantomData<T>,
}

impl<T: HasDiscriminator + ZeroPodFixed<Zc = T>> InstructionBuilder<T> {
	/// Returns the raw byte representation of `instruction`.
	///
	/// The returned slice includes the discriminator prefix (which is part of
	/// the zero-copy struct layout) followed by any instruction arguments.
	#[inline]
	#[allow(unsafe_code)]
	pub fn data(instruction: &T) -> &[u8] {
		// SAFETY: `T` is `#[repr(C)]` with align-1 pod fields (compile-time
		// asserted by the `#[instruction]` macro), so its bytes are a valid
		// representation.
		unsafe { core::slice::from_raw_parts(instruction as *const T as *const u8, size_of::<T>()) }
	}
}

/// An account metadata tuple of `(address, is_signer, is_writable)`.
///
/// This type alias mirrors the common three-field representation used by
/// Solana SDK `AccountMeta` without pulling in the full `solana-sdk`
/// dependency.
pub type AccountMetaTuple = (Address, bool, bool);

/// Creates an account metadata entry for an address that is both a signer and
/// writable.
///
/// # Examples
///
/// ```
/// use pina::Address;
/// use pina::transaction::writable_signer;
///
/// let address = Address::from([1u8; 32]);
/// let (addr, is_signer, is_writable) = writable_signer(&address);
/// assert!(is_signer);
/// assert!(is_writable);
/// assert_eq!(addr, address);
/// ```
#[inline]
pub fn writable_signer(address: &Address) -> AccountMetaTuple {
	(*address, true, true)
}

/// Creates an account metadata entry for an address that is writable but not a
/// signer.
///
/// # Examples
///
/// ```
/// use pina::Address;
/// use pina::transaction::writable;
///
/// let address = Address::from([2u8; 32]);
/// let (addr, is_signer, is_writable) = writable(&address);
/// assert!(!is_signer);
/// assert!(is_writable);
/// assert_eq!(addr, address);
/// ```
#[inline]
pub fn writable(address: &Address) -> AccountMetaTuple {
	(*address, false, true)
}

/// Creates an account metadata entry for an address that is a signer but
/// read-only.
///
/// # Examples
///
/// ```
/// use pina::Address;
/// use pina::transaction::readonly_signer;
///
/// let address = Address::from([3u8; 32]);
/// let (addr, is_signer, is_writable) = readonly_signer(&address);
/// assert!(is_signer);
/// assert!(!is_writable);
/// assert_eq!(addr, address);
/// ```
#[inline]
pub fn readonly_signer(address: &Address) -> AccountMetaTuple {
	(*address, true, false)
}

/// Creates an account metadata entry for an address that is neither a signer
/// nor writable.
///
/// # Examples
///
/// ```
/// use pina::Address;
/// use pina::transaction::readonly;
///
/// let address = Address::from([4u8; 32]);
/// let (addr, is_signer, is_writable) = readonly(&address);
/// assert!(!is_signer);
/// assert!(!is_writable);
/// assert_eq!(addr, address);
/// ```
#[inline]
pub fn readonly(address: &Address) -> AccountMetaTuple {
	(*address, false, false)
}

#[cfg(test)]
mod tests {
	#![allow(unsafe_code)]
	extern crate std;

	use super::*;
	use crate::PodU64;
	use crate::ZcElem;
	use crate::ZcValidate;
	use crate::ZeroPodError;
	use crate::ZeroPodFixed;
	use crate::ZeroPodSchema;

	#[repr(C)]
	#[derive(Copy, Clone, Debug)]
	struct TestInstruction {
		discriminator: u8,
		amount: PodU64,
	}

	impl ZcValidate for TestInstruction {
		fn validate_ref(value: &Self) -> Result<(), ZeroPodError> {
			u8::validate_ref(&value.discriminator)?;
			PodU64::validate_ref(&value.amount)?;
			Ok(())
		}
	}

	// SAFETY: align 1, no padding, every bit pattern valid, validate_ref
	// is load-bearing.
	unsafe impl ZcElem for TestInstruction {}

	impl ZeroPodSchema for TestInstruction {
		const LAYOUT: crate::LayoutKind = crate::LayoutKind::Fixed;
	}

	impl ZeroPodFixed for TestInstruction {
		type Zc = TestInstruction;

		const SIZE: usize = core::mem::size_of::<TestInstruction>();

		fn from_bytes(data: &[u8]) -> Result<&Self::Zc, ZeroPodError> {
			Self::validate(data)?;
			Ok(unsafe { &*(data.as_ptr() as *const Self::Zc) })
		}

		fn from_bytes_mut(data: &mut [u8]) -> Result<&mut Self::Zc, ZeroPodError> {
			Self::validate(data)?;
			Ok(unsafe { &mut *(data.as_mut_ptr() as *mut Self::Zc) })
		}

		fn validate(data: &[u8]) -> Result<(), ZeroPodError> {
			if data.len() < Self::SIZE {
				return Err(ZeroPodError::BufferTooSmall);
			}
			let zc = unsafe { &*(data.as_ptr() as *const Self::Zc) };
			<Self::Zc as ZcValidate>::validate_ref(zc)?;
			Ok(())
		}

		unsafe fn from_bytes_unchecked(data: &[u8]) -> &Self::Zc {
			&*(data.as_ptr() as *const Self::Zc)
		}

		unsafe fn from_bytes_mut_unchecked(data: &mut [u8]) -> &mut Self::Zc {
			&mut *(data.as_mut_ptr() as *mut Self::Zc)
		}
	}

	impl HasDiscriminator for TestInstruction {
		type Type = u8;

		const VALUE: u8 = 5;
	}

	#[test]
	fn instruction_builder_data_includes_discriminator() {
		let ix = TestInstruction {
			discriminator: 5,
			amount: PodU64::from(1000),
		};
		let bytes = InstructionBuilder::<TestInstruction>::data(&ix);
		assert_eq!(bytes[0], 5);
		assert_eq!(bytes.len(), size_of::<TestInstruction>());
	}

	#[test]
	fn instruction_builder_data_preserves_payload() {
		let ix = TestInstruction {
			discriminator: 5,
			amount: PodU64::from(u64::MAX),
		};
		let bytes = InstructionBuilder::<TestInstruction>::data(&ix);
		// First byte is discriminator.
		assert_eq!(bytes[0], 5);
		// Remaining bytes are the PodU64 in little-endian.
		assert_eq!(&bytes[1..], &u64::MAX.to_le_bytes());
	}

	#[test]
	fn writable_signer_returns_correct_tuple() {
		let addr = Address::from([0xAA; 32]);
		let (a, signer, w) = writable_signer(&addr);
		assert_eq!(a, addr);
		assert!(signer);
		assert!(w);
	}

	#[test]
	fn writable_returns_correct_tuple() {
		let addr = Address::from([0xBB; 32]);
		let (a, signer, w) = writable(&addr);
		assert_eq!(a, addr);
		assert!(!signer);
		assert!(w);
	}

	#[test]
	fn readonly_signer_returns_correct_tuple() {
		let addr = Address::from([0xCC; 32]);
		let (a, signer, w) = readonly_signer(&addr);
		assert_eq!(a, addr);
		assert!(signer);
		assert!(!w);
	}

	#[test]
	fn readonly_returns_correct_tuple() {
		let addr = Address::from([0xDD; 32]);
		let (a, signer, w) = readonly(&addr);
		assert_eq!(a, addr);
		assert!(!signer);
		assert!(!w);
	}

	#[test]
	fn zero_address_helpers() {
		let zero = Address::from([0u8; 32]);
		assert_eq!(writable_signer(&zero).0, zero);
		assert_eq!(writable(&zero).0, zero);
		assert_eq!(readonly_signer(&zero).0, zero);
		assert_eq!(readonly(&zero).0, zero);
	}
}
