//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: 1a5bf9ca6d821d733f4ff6c8f3ffc1bcb2188ea3bd7e78065ca0d1e79d3f60d6
// program-id: 6oW4PDgWpZGWqAEZNvqnAtQi8GotATsxxjCLYQpZJhHL
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "6oW4PDgWpZGWqAEZNvqnAtQi8GotATsxxjCLYQpZJhHL";

/// ABI layout for the `ProfileState` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ProfileState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "032b267b01aefa873053524e24c0b9eda42002a88f7d68e819714b7453aecdcc";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 239;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 239;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
		("name", MIGRATION_HEADER_SIZE + 1, 33),
		("bio", MIGRATION_HEADER_SIZE + 34, 129),
		("tags", MIGRATION_HEADER_SIZE + 163, 66),
		("favorite_tag", MIGRATION_HEADER_SIZE + 229, 9),
		("active", MIGRATION_HEADER_SIZE + 238, 1),
	];
}

/// ABI layout for the `InitializeInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "cd10bc8b9f702e13b810e213473d6f4effac3dd761ba35bc2b3359440eb5ffa8";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 163;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 163;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
		("name", MIGRATION_HEADER_SIZE + 1, 33),
		("bio", MIGRATION_HEADER_SIZE + 34, 129),
	];
}

/// ABI layout for the `UpdateProfileInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "UpdateProfileInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9036d93d716da69009369a1473d58331794b9879412ef9d6963f004270efc8a6";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 162;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 162;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("name", MIGRATION_HEADER_SIZE + 0, 33),
		("bio", MIGRATION_HEADER_SIZE + 33, 129),
	];
}

/// ABI layout for the `AddTagInstruction` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "AddTagInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4da0cc201bf302ccd5c1cb1d32d77b50ce5c9001306c6ad3dade76a7d432a5a5";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 8;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 8;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("tag", MIGRATION_HEADER_SIZE + 0, 8),
	];
}

/// ABI layout for the `RemoveTagInstruction` instruction.
pub mod instruction_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "RemoveTagInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0ee1c0abc4c4a8fe4413375e257f5860485f9a6ee1906c118f0bd56665a435ab";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 8;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 8;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("index", MIGRATION_HEADER_SIZE + 0, 8),
	];
}

