[package]
name = "optional_accounts_program_cli"
version = "0.1.0"
edition = "2021"
publish = false
description = "Generated CLI for optionalAccountsProgram"

[[bin]]
name = "optional-accounts-program-cli"
path = "src/main.rs"

[dependencies]
bs58 = { workspace = true, default-features = true }
clap = { workspace = true, default-features = true, features = ["derive", "std", "env"] }
optional-accounts-program-client = { path = "../../../rust/optional_accounts_program" }
serde_json = { workspace = true, default-features = true }
solana-rpc-client = { workspace = true, default-features = true }
solana-sdk = { workspace = true, default-features = true }
thiserror = { workspace = true, default-features = true }
