//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use pina_bpf_program_client;
use serde_json::Value;
use serde_json::json;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Subcommand)]
pub enum Command {
	State(StateArgs),
}

#[derive(Debug, Args)]
pub struct StateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::State(args) => fetch_state(context, args),
	}
}

fn fetch_state(context: &CliContext, args: StateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let seeds: &[&[u8]] = &["state".as_bytes()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match pina_bpf_program_client::accounts::State::from_bytes(&data) {
		Ok(account) => state_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "state", &address, &value);
	Ok(())
}

fn state_json(account: &pina_bpf_program_client::accounts::StateZc) -> Value {
	json!({
		"bump": account.bump,
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
