// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/multisig_program.dart';

final class ConfigExecuteCommand extends Command<void> {
  ConfigExecuteCommand() {
    argParser
      ..addOption('multisig', mandatory: true, help: "The multisig account")
      ..addOption('proposal', mandatory: true, help: "The proposal account")
      ..addOption('member', mandatory: false, help: "The member account [default: payer]")
      ..addOption('rent_payer', mandatory: false, help: "The rent_payer account [default: payer]")
      ..addOption('clock', mandatory: true, help: "The clock account")
      ..addOption('spending_limit_accounts', mandatory: true, help: "Spending limit accounts referenced by add/remove spending-limit");
  }

  @override
  String get name => 'config_execute';

  @override
  String get description => "config_execute";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final multisig = pubkey('--multisig', results['multisig']! as String);
    final proposal = pubkey('--proposal', results['proposal']! as String);
    final member = (results['member'] as String?) != null
        ? pubkey('--member', results['member']! as String)
        : context.payerAddress;
    final rentPayer = (results['rent_payer'] as String?) != null
        ? pubkey('--rent-payer', results['rent_payer']! as String)
        : context.payerAddress;
    final clock = pubkey('--clock', results['clock']! as String);
    final spendingLimitAccounts = pubkey('--spending-limit-accounts', results['spending_limit_accounts']! as String);

    final instruction = getConfigExecuteInstruction(
      programAddress: context.programAddress,
      multisig: multisig,
      proposal: proposal,
      member: member,
      rentPayer: rentPayer,
      systemProgram: Address('11111111111111111111111111111111'),
      clock: clock,
      spendingLimitAccounts: spendingLimitAccounts,
    );
    await context.send([instruction]);
  }
}
