// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/multisig_program.dart';

final class ConfigInitializeCommand extends Command<void> {
  ConfigInitializeCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption('treasury', mandatory: true, help: "treasury")
      ..addOption('creation_fee', mandatory: true, help: "creationFee")
      ..addOption('authority', mandatory: false, help: "The authority account [default: payer]")
      ..addOption('program_config', mandatory: false, help: "The program_config account [default: derived]");
  }

  @override
  String get name => 'config_initialize';

  @override
  String get description => "config_initialize";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final programConfig = (results['program_config'] as String?) != null
        ? pubkey('--program-config', results['program_config']! as String)
        : (await findProgramConfigPda(
          programAddress: context.programAddress,
        )).$1;
    final bumpValue = integer('--bump', results['bump']! as String);
    final treasuryValue = pubkey('--treasury', results['treasury']! as String);
    final creationFeeValue = bigInteger('--creation-fee', results['creation_fee']! as String);
    final instruction = getConfigInitializeInstruction(
      programAddress: context.programAddress,
      authority: authority,
      programConfig: programConfig,
      systemProgram: Address('11111111111111111111111111111111'),
      bump: bumpValue,
      treasury: treasuryValue,
      creationFee: creationFeeValue,
    );
    await context.send([instruction]);
  }
}
