//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use multisig_program_client::instructions::ConfigUpdate;
use multisig_program_client::instructions::ConfigUpdateInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ConfigUpdateArgs {
	#[arg(long)]
	set_treasury: bool,
	#[arg(long)]
	treasury: String,
	#[arg(long)]
	set_creation_fee: bool,
	#[arg(long)]
	creation_fee: u64,
	/// The `program_config` account [default: derived]
	#[arg(long)]
	program_config: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: ConfigUpdateArgs) -> Result<(), CliError> {
	let treasury = CliContext::pubkey("--treasury", &args.treasury)?;
	let authority = context.payer_pubkey();
	let program_config = match &args.program_config {
		Some(value) => CliContext::pubkey("--program_config", value)?,
		None => {
			Pubkey::find_program_address(
				&["multisig-program-config".as_bytes()],
				&context.program_address,
			)
			.0
		}
	};
	let data = ConfigUpdateInstructionData::new(|data| {
		data.set_treasury.set(args.set_treasury);
		data.treasury = treasury;
		data.set_creation_fee.set(args.set_creation_fee);
		data.creation_fee.set(args.creation_fee);
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = ConfigUpdate {
		authority,
		program_config,
	};

	context.send(accounts.instruction(data))
}
