//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use multisig_program_client::instructions::ConfigExecute;
use multisig_program_client::instructions::ConfigExecuteInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ConfigExecuteArgs {
	/// The `multisig` account
	#[arg(long)]
	multisig: String,
	/// The `proposal` account
	#[arg(long)]
	proposal: String,
	/// The `clock` account
	#[arg(long)]
	clock: String,
	/// Refund destination for closed spending-limit accounts. When the multisig configures a rent collector this must be that address; with none configured any writable account fills the slot and refunds fall back to `rent_payer`, which also funds any growth
	#[arg(long)]
	rent_collector: String,
	/// Spending limit accounts referenced by add/remove spending-limit actions, in any order
	#[arg(long)]
	spending_limit_accounts: String,
}

pub(crate) fn run(context: &CliContext, args: ConfigExecuteArgs) -> Result<(), CliError> {
	let multisig = CliContext::pubkey("--multisig", &args.multisig)?;
	let proposal = CliContext::pubkey("--proposal", &args.proposal)?;
	let member = context.payer_pubkey();
	let rent_payer = context.payer_pubkey();
	let clock = CliContext::pubkey("--clock", &args.clock)?;
	let rent_collector = CliContext::pubkey("--rent_collector", &args.rent_collector)?;
	let spending_limit_accounts =
		CliContext::pubkey("--spending_limit_accounts", &args.spending_limit_accounts)?;
	let data = ConfigExecuteInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = ConfigExecute {
		multisig,
		proposal,
		member,
		rent_payer,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
		clock,
		rent_collector,
		spending_limit_accounts,
	};

	context.send(accounts.instruction(data))
}
