//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use multisig_program_client::instructions::MultisigCreate;
use multisig_program_client::instructions::MultisigCreateInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct MultisigCreateArgs {
	#[arg(long)]
	bump: u8,
	#[arg(long)]
	threshold: u16,
	#[arg(long)]
	timelock: u32,
	#[arg(long)]
	ttl: u32,
	#[arg(long)]
	member_permissions: String,
	#[arg(long)]
	config_authority: String,
	#[arg(long)]
	rent_collector: String,
	/// The `program_config` account
	#[arg(long)]
	program_config: String,
	/// The `create_key` account [default: payer]
	#[arg(long)]
	create_key: Option<String>,
	/// The `multisig` account [default: derived]
	#[arg(long)]
	multisig: Option<String>,
	/// The `rent_payer` account [default: payer]
	#[arg(long)]
	rent_payer: Option<String>,
	/// Treasury that collects the creation fee; pass the program's own address as a filler when the fee is zero
	#[arg(long)]
	treasury: String,
	/// The founding members, sorted by address; `member_permissions` indexes into this list positionally
	#[arg(long)]
	member_accounts: String,
}

pub(crate) fn run(context: &CliContext, args: MultisigCreateArgs) -> Result<(), CliError> {
	let member_permissions =
		CliContext::bytes::<16>("--member_permissions", &args.member_permissions)?;
	let config_authority = CliContext::pubkey("--config_authority", &args.config_authority)?;
	let rent_collector = CliContext::pubkey("--rent_collector", &args.rent_collector)?;
	let program_config = CliContext::pubkey("--program_config", &args.program_config)?;
	let create_key = match &args.create_key {
		Some(value) => CliContext::pubkey("--create_key", value)?,
		None => context.payer_pubkey(),
	};
	let multisig = match &args.multisig {
		Some(value) => CliContext::pubkey("--multisig", value)?,
		None => {
			Pubkey::find_program_address(
				&["multisig".as_bytes(), create_key.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let rent_payer = match &args.rent_payer {
		Some(value) => CliContext::pubkey("--rent_payer", value)?,
		None => context.payer_pubkey(),
	};
	let treasury = CliContext::pubkey("--treasury", &args.treasury)?;
	let member_accounts = CliContext::pubkey("--member_accounts", &args.member_accounts)?;
	let data = MultisigCreateInstructionData::new(|data| {
		data.bump = args.bump;
		data.threshold.set(args.threshold);
		data.timelock.set(args.timelock);
		data.ttl.set(args.ttl);
		data.member_permissions = member_permissions;
		data.config_authority = config_authority;
		data.rent_collector = rent_collector;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = MultisigCreate {
		program_config,
		create_key,
		multisig,
		rent_payer,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
		treasury: Some(treasury),
		member_accounts,
	};

	context.send(accounts.instruction(data))
}
