//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use multisig_program_client::instructions::ProposalClose;
use multisig_program_client::instructions::ProposalCloseInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ProposalCloseArgs {
	/// The `multisig` account
	#[arg(long)]
	multisig: String,
	/// The `proposal` account
	#[arg(long)]
	proposal: String,
	/// The `rent_collector` account
	#[arg(long)]
	rent_collector: String,
}

pub(crate) fn run(context: &CliContext, args: ProposalCloseArgs) -> Result<(), CliError> {
	let multisig = CliContext::pubkey("--multisig", &args.multisig)?;
	let proposal = CliContext::pubkey("--proposal", &args.proposal)?;
	let rent_collector = CliContext::pubkey("--rent_collector", &args.rent_collector)?;
	let data = ProposalCloseInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = ProposalClose {
		multisig,
		proposal,
		rent_collector,
	};

	context.send(accounts.instruction(data))
}
