// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getCreatePdaInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const createPdaCommand = registerGlobals(new Command("create_pda"))
	.description("createPda")
	.requiredOption("--bump <bump>", "bump")
	.option("--payer <payer>", "The `payer` account [default: payer]")
	.requiredOption("--state <state>", "The `state` account")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			payer: context.payer,
			state: pubkey("--state", options.state),
		};
		const instruction = getCreatePdaInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
