// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/privacy_pool_program.dart';

final class RequestDisclosureCommand extends Command<void> {
  RequestDisclosureCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption('nonce', mandatory: true, help: "nonce")
      ..addOption(
        'tier',
        mandatory: true,
        help: "Tier being invoked; see the `TIER_*` constants.",
      )
      ..addOption(
        'commitment',
        mandatory: true,
        help: "Target note commitment.",
      )
      ..addOption(
        'notice_len',
        mandatory: true,
        help: "Active length of the encrypted notice.",
      )
      ..addOption('notice', mandatory: true, help: "notice")
      ..addOption(
        'legal_basis_hash',
        mandatory: true,
        help: "Hash of the legal basis; nonzero required above tier 0.",
      )
      ..addOption(
        'pool_config',
        mandatory: false,
        help: "The pool_config account [default: derived]",
      )
      ..addOption(
        'requester_registry',
        mandatory: false,
        help: "The requester_registry account [default: derived]",
      )
      ..addOption(
        'note_commitment',
        mandatory: true,
        help: "The note_commitment account",
      )
      ..addOption(
        'disclosure_request',
        mandatory: true,
        help: "The disclosure_request account",
      )
      ..addOption(
        'system_program',
        mandatory: true,
        help: "The system_program account",
      )
      ..addOption('clock', mandatory: true, help: "The clock account");
  }

  @override
  String get name => 'request_disclosure';

  @override
  String get description => "request_disclosure";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final requester = context.payerAddress;
    final poolConfig = (results['pool_config'] as String?) != null
        ? pubkey('--pool-config', results['pool_config']! as String)
        : (await findPoolConfigPda(programAddress: context.programAddress)).$1;
    final requesterRegistry = (results['requester_registry'] as String?) != null
        ? pubkey(
            '--requester-registry',
            results['requester_registry']! as String,
          )
        : (await findRequesterRegistryPda(
            programAddress: context.programAddress,
          )).$1;
    final noteCommitment = pubkey(
      '--note-commitment',
      results['note_commitment']! as String,
    );
    final disclosureRequest = pubkey(
      '--disclosure-request',
      results['disclosure_request']! as String,
    );
    final systemProgram = pubkey(
      '--system-program',
      results['system_program']! as String,
    );
    final clock = pubkey('--clock', results['clock']! as String);
    final bumpValue = integer('--bump', results['bump']! as String);
    final nonceValue = bigInteger('--nonce', results['nonce']! as String);
    final tierValue = integer('--tier', results['tier']! as String);
    final commitmentValue = base58Bytes(
      '--commitment',
      results['commitment']! as String,
    );
    final noticeLenValue = integer(
      '--notice-len',
      results['notice_len']! as String,
    );
    final noticeValue = base58Bytes('--notice', results['notice']! as String);
    final legalBasisHashValue = base58Bytes(
      '--legal-basis-hash',
      results['legal_basis_hash']! as String,
    );
    final instruction = getRequestDisclosureInstruction(
      programAddress: context.programAddress,
      requester: requester,
      poolConfig: poolConfig,
      requesterRegistry: requesterRegistry,
      noteCommitment: noteCommitment,
      disclosureRequest: disclosureRequest,
      systemProgram: systemProgram,
      clock: clock,
      bump: bumpValue,
      nonce: nonceValue,
      tier: tierValue,
      commitment: commitmentValue,
      noticeLen: noticeLenValue,
      notice: noticeValue,
      legalBasisHash: legalBasisHashValue,
    );
    await context.send([
      instruction,
    ], recordedLimit: requestDisclosureComputeUnitLimit);
  }
}
