// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/privacy_pool_program.dart';

final class SetCustodiansCommand extends Command<void> {
  SetCustodiansCommand() {
    argParser
      ..addOption('custodians', mandatory: true, help: "custodians")
      ..addOption('pool_config', mandatory: true, help: "The pool_config account")
      ..addOption('custodian_registry', mandatory: true, help: "The custodian_registry account");
  }

  @override
  String get name => 'set_custodians';

  @override
  String get description => "set_custodians";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = context.payerAddress;
    final poolConfig = pubkey('--pool-config', results['pool_config']! as String);
    final custodianRegistry = pubkey('--custodian-registry', results['custodian_registry']! as String);
    final custodiansValue = base58Bytes('--custodians', results['custodians']! as String);
    final instruction = getSetCustodiansInstruction(
      programAddress: context.programAddress,
      authority: authority,
      poolConfig: poolConfig,
      custodianRegistry: custodianRegistry,
      custodians: custodiansValue,
    );
    await context.send([instruction]);
  }
}
