// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/privacy_pool_program.dart';

final class WithdrawCommand extends Command<void> {
  WithdrawCommand() {
    argParser
      ..addOption('nullifier', mandatory: true, help: "nullifier")
      ..addOption('root', mandatory: true, help: "root")
      ..addOption('proof_a', mandatory: true, help: "proofA")
      ..addOption('proof_b', mandatory: true, help: "proofB")
      ..addOption('proof_c', mandatory: true, help: "proofC")
      ..addOption(
        'pool_config',
        mandatory: true,
        help: "The pool_config account",
      )
      ..addOption('pool_vault', mandatory: true, help: "The pool_vault account")
      ..addOption(
        'merkle_tree',
        mandatory: true,
        help: "The merkle_tree account",
      )
      ..addOption(
        'nullifier_set',
        mandatory: true,
        help: "The nullifier_set account",
      )
      ..addOption(
        'verifying_key_account',
        mandatory: true,
        help: "The verifying_key_account account",
      )
      ..addOption('recipient', mandatory: true, help: "The recipient account");
  }

  @override
  String get name => 'withdraw';

  @override
  String get description => "withdraw";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final poolConfig = pubkey(
      '--pool-config',
      results['pool_config']! as String,
    );
    final poolVault = pubkey('--pool-vault', results['pool_vault']! as String);
    final merkleTree = pubkey(
      '--merkle-tree',
      results['merkle_tree']! as String,
    );
    final nullifierSet = pubkey(
      '--nullifier-set',
      results['nullifier_set']! as String,
    );
    final verifyingKeyAccount = pubkey(
      '--verifying-key-account',
      results['verifying_key_account']! as String,
    );
    final recipient = pubkey('--recipient', results['recipient']! as String);
    final nullifierValue = base58Bytes(
      '--nullifier',
      results['nullifier']! as String,
    );
    final rootValue = base58Bytes('--root', results['root']! as String);
    final proofAValue = base58Bytes('--proof-a', results['proof_a']! as String);
    final proofBValue = base58Bytes('--proof-b', results['proof_b']! as String);
    final proofCValue = base58Bytes('--proof-c', results['proof_c']! as String);
    final instruction = getWithdrawInstruction(
      programAddress: context.programAddress,
      poolConfig: poolConfig,
      poolVault: poolVault,
      merkleTree: merkleTree,
      nullifierSet: nullifierSet,
      verifyingKeyAccount: verifyingKeyAccount,
      recipient: recipient,
      systemProgram: Address('11111111111111111111111111111111'),
      nullifier: nullifierValue,
      root: rootValue,
      proofA: proofAValue,
      proofB: proofBValue,
      proofC: proofCValue,
    );
    await context.send([instruction]);
  }
}
