//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: bd3e3a2bdafcd16e7b0a45748b37771d50572b6d0ebd2c767655e215e0456118
// program-id: Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS";

/// ABI layout for the `Sample` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Sample";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "a0e56905453d4e0d99735202d624a100ab2c1f13e32a5acff74e89ddb75295c4";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Compact header size in bytes.
	pub const HEADER_SIZE: usize = 35;
	/// Maximum encoded size in bytes.
	pub const MAX_SIZE: usize = 547;
	/// Byte granularity of valid allocations.
	pub const TAIL_ALIGNMENT: usize = 8;
	/// Smallest valid encoded size, including the envelope header.
	pub const MIN_SIZE: usize = MIGRATION_HEADER_SIZE + HEADER_SIZE;
}

/// ABI layout for the `ReallocIx` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ReallocIx";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "8a50396e1191eaac7a9d3dc4f8a746667c8080f45a27ee31d11e051e1563bf8f";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("len", MIGRATION_HEADER_SIZE + 0, 2),
	];
}

/// ABI layout for the `Realloc2Ix` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Realloc2Ix";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "8a50396e1191eaac7a9d3dc4f8a746667c8080f45a27ee31d11e051e1563bf8f";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 2;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 2;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("len", MIGRATION_HEADER_SIZE + 0, 2),
	];
}

/// ABI layout for the `InitializeIx` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializeIx";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "3f3f22a55d540fe677d2f3ea9a3ecdc9ddc97436bbbf9e9d5a0974d4dd32e43b";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 1;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 1;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
	];
}

