[package]
name = "pina_fuzz_targets"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
counter_program = { path = "../../../examples/counter_program" }
libfuzzer-sys = "0.4"
pina = { path = "../../pina" }
pina_fuzz = { path = ".." }
role_registry_program = { path = "../../../examples/role_registry_program" }

[[bin]]
name = "account_deserialize"
path = "fuzz_targets/account_deserialize.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_instruction"
path = "fuzz_targets/parse_instruction.rs"
test = false
doc = false
bench = false
