// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/validation_program.dart';

final class CheckPolicyCommand extends Command<void> {
  CheckPolicyCommand() {
    argParser
      ..addOption('amount', mandatory: true, help: "amount")
      ..addOption('memo', mandatory: true, help: "memo")
      ..addOption('approvals', mandatory: true, help: "approvals")
      ..addOption('authority', mandatory: false, help: "The authority account [default: payer]")
      ..addOption('policy', mandatory: false, help: "The policy account [default: derived]")
      ..addOption('audit', mandatory: true, help: "A shared account may still require the transaction's writable flag");
  }

  @override
  String get name => 'check_policy';

  @override
  String get description => "check_policy";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final policy = (results['policy'] as String?) != null
        ? pubkey('--policy', results['policy']! as String)
        : (await findPolicyPda(
          seeds: PolicySeeds(authority: authority),
          programAddress: context.programAddress,
        )).$1;
    final audit = pubkey('--audit', results['audit']! as String);
    final amountValue = bigInteger('--amount', results['amount']! as String);
    final memoValue = results['memo']! as String;
    final approvalsValue = base58Bytes('--approvals', results['approvals']! as String);
    final instruction = getCheckPolicyInstruction(
      programAddress: context.programAddress,
      authority: authority,
      policy: policy,
      audit: audit,
      systemProgram: Address('11111111111111111111111111111111'),
      amount: amountValue,
      memo: memoValue,
      approvals: approvalsValue,
    );
    await context.send([instruction]);
  }
}
