//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use optional_accounts_program_client::instructions::Init;
use optional_accounts_program_client::instructions::InitInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct InitArgs {
	#[arg(long)]
	bump: u8,
	/// Pays for account creation and seeds the store PDA [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The store PDA account (must be empty — not yet created)
	#[arg(long)]
	store: String,
}

pub(crate) fn run(context: &CliContext, args: InitArgs) -> Result<(), CliError> {
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let store = CliContext::pubkey("--store", &args.store)?;
	let data = InitInstructionData::new(|data| {
		data.bump = args.bump;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Init {
		authority,
		store,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
