// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'dart:typed_data';

import 'package:args/command_runner.dart';
import 'package:solana_kit_accounts/solana_kit_accounts.dart';
import 'package:solana_kit_rpc_types/solana_kit_rpc_types.dart'
    hide TransactionVersion;

import '../context.dart';
import 'package:pina_codama_clients/float_accounts_program.dart';

final class FetchFloatDataAccountCommand extends Command<void> {
  FetchFloatDataAccountCommand() {
    argParser..addOption(
      'address',
      help: 'Account address; overrides PDA derivation.',
    );
  }

  @override
  String get name => 'float-data-account';

  @override
  String get description => "float_data_account";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final address = pubkey('--address', results['address']! as String);
    final data = await context.fetchAccount(address);
    final encoded = Account<Uint8List>(
      address: address,
      data: data,
      executable: false,
      lamports: Lamports(BigInt.zero),
      programAddress: context.programAddress,
      space: BigInt.from(data.length),
    );
    final account = decodeFloatDataAccount(encoded);
    printFields(context.json, 'float-data-account', address, <String, Object?>{
      'data_f64': account.data.dataF64,
      'data_f32': account.data.dataF32,
      'authority': account.data.authority,
    });
  }
}

final class FetchCommand extends Command<void> {
  @override
  String get name => 'fetch';

  @override
  String get description => 'Fetch and decode program accounts.';
}
