// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getInitializeInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const initializeCommand = registerGlobals(new Command("initialize"))
	.description("initialize")
	.requiredOption("--bump <bump>", "bump")
	.requiredOption("--entry-count <entryCount>", "entryCount")
	.requiredOption("--marker-count <markerCount>", "markerCount")
	.option(
		"--authority <authority>",
		"Funds rent and becomes the journal authority [default: payer]",
	)
	.option(
		"--journal <journal>",
		"Empty canonical journal PDA [default: derived]",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			entryCount: smallInteger("--entry-count", options.entryCount),
			markerCount: smallInteger("--marker-count", options.markerCount),
			authority: context.payer,
			journal: options.journal,
		};
		const instruction = await getInitializeInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
