// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getRenameInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const renameCommand = registerGlobals(new Command("rename"))
	.description("rename")
	.requiredOption("--title-len <titleLen>", "titleLen")
	.requiredOption("--title <title>", "title")
	.option(
		"--authority <authority>",
		"Funds title growth and receives rent refunded by title shrinkage [default: payer]",
	)
	.option("--journal <journal>", "The `journal` account [default: derived]")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			titleLen: smallInteger("--title-len", options.titleLen),
			title: base58("--title", options.title),
			authority: context.payer,
			journal: options.journal,
		};
		const instruction = await getRenameInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
