//! Counter program — demonstrates account state management with pina.
//!
//! This example shows how to use pina's macro system to define on-chain state
//! and mutate it across transactions. It covers:
//!
//! - **Account schemas** with `#[account]` — native Rust fields plus a
//!   generated, validated zeropod view over account bytes.
//! - **PDA-based accounts** — the counter is stored at a Program Derived
//!   Address seeded by the authority's public key, so each user gets their own
//!   counter.
//! - **Instruction dispatch** — `#[discriminator]` + `#[instruction]` +
//!   `parse_instruction` for type-safe routing.
//! - **Account validation chains** — `.assert_signer()?.assert_writable()?` for
//!   concise, composable checks.
//! - **`create_program_account`** — pina's CPI helper for PDA account creation.
//!
//! ## Instructions
//!
//! | Variant     | Description                               |
//! |-------------|-------------------------------------------|
//! | `Initialize` | Create a new counter PDA for the signer. |
//! | `Increment`  | Add 1 to the counter value.              |

#![allow(clippy::inline_always)]
#![no_std]

// On native builds the cdylib target needs std for unwinding and panic
// handling. On BPF, `nostd_entrypoint!()` provides the panic handler and
// allocator. Tests link against std automatically.
#[cfg(all(
	not(any(target_os = "solana", target_arch = "bpf")),
	not(feature = "bpf-entrypoint"),
	not(test)
))]
extern crate std;

use pina::*;

// ---------------------------------------------------------------------------
// Program ID
// ---------------------------------------------------------------------------

// The on-chain address of this program.
declare_id!("GJQcuWrT2f3f4KNuJcXhhwUa1ZQTYbxzzJ1hotzKu8hS");

// ---------------------------------------------------------------------------
// Discriminators
// ---------------------------------------------------------------------------

/// Instruction discriminator. Each variant maps to a unique `u8` tag that
/// appears as the first byte of instruction data.
#[discriminator]
pub enum CounterInstruction {
	Initialize = 0,
	Increment = 1,
}

/// Account discriminator. Stored as the first byte of on-chain account data
/// so the program can distinguish between different account types.
///
/// The variant name **must match** the struct name it discriminates (e.g.
/// `CounterState` variant for the `CounterState` struct). This is how the
/// `#[account]` macro links structs to their discriminator values.
#[discriminator]
pub enum CounterAccountType {
	CounterState = 1,
}

// ---------------------------------------------------------------------------
// Account state
// ---------------------------------------------------------------------------

/// On-chain counter state.
///
/// The `#[account]` macro generates:
/// - A discriminator field (`CounterAccountType::CounterState`) as the first
///   byte.
/// - A `CounterStateZc` storage view generated by `zeropod::ZeroPod`.
/// - `HasDiscriminator` linking this struct to
///   `CounterAccountType::CounterState`.
/// - `initialize` and `try_from_bytes` helpers for caller-owned storage.
///
/// Layout (10 bytes total):
/// ```text
/// | offset | size | field         |
/// |--------|------|---------------|
/// | 0      | 1    | discriminator |
/// | 1      | 1    | bump          |
/// | 2      | 8    | count (little-endian u64) |
/// ```
#[account(discriminator = CounterAccountType)]
#[pda(seeds = [COUNTER_SEED, authority: Address], bump = bump)]
pub struct CounterState {
	/// The PDA bump seed, stored on-chain so we don't need to re-derive it.
	pub bump: u8,
	/// The current counter value. The zeropod view stores it using its
	/// alignment-one, little-endian representation.
	pub count: u64,
}

// ---------------------------------------------------------------------------
// Instruction data structs
// ---------------------------------------------------------------------------

/// Instruction data for `Initialize`.
///
/// Contains the PDA bump seed so the client can pass a pre-computed bump
/// (avoids the cost of `find_program_address` on-chain).
#[instruction(discriminator = CounterInstruction::Initialize)]
pub struct InitializeInstruction {
	/// The PDA bump seed, computed off-chain.
	pub bump: u8,
}

/// Instruction data for `Increment`. No extra payload beyond the
/// discriminator byte.
#[instruction(discriminator = CounterInstruction::Increment)]
pub struct IncrementInstruction {}

// ---------------------------------------------------------------------------
// PDA seeds
// ---------------------------------------------------------------------------

/// Seed prefix for counter PDAs.
const COUNTER_SEED: &[u8] = b"counter";

// ---------------------------------------------------------------------------
// Accounts structs
// ---------------------------------------------------------------------------

/// Accounts for the `Initialize` instruction.
///
/// `#[derive(Accounts)]` generates `TryFromAccountInfos` which maps positional
/// accounts to named fields.
#[derive(Accounts, Debug)]
pub struct InitializeAccounts<'a> {
	/// The wallet creating the counter. Pays for account creation and becomes
	/// the authority whose address seeds the PDA.
	pub authority: &'a AccountView,
	/// The counter PDA account (must be empty — not yet created).
	pub counter: &'a mut AccountView,
	/// The system program, required for `CreateAccount` CPI.
	pub system_program: &'a AccountView,
}

/// Accounts for the `Increment` instruction.
#[derive(Accounts, Debug)]
pub struct IncrementAccounts<'a> {
	/// The counter's authority. Must sign to prove ownership.
	pub authority: &'a AccountView,
	/// The counter PDA account (must already exist and be writable).
	pub counter: &'a mut AccountView,
}

// ---------------------------------------------------------------------------
// Instruction processors
// ---------------------------------------------------------------------------

impl<'a> ProcessAccountInfos<'a> for InitializeAccounts<'a> {
	fn process(self, data: &[u8]) -> ProgramResult {
		// Parse instruction and prepare PDA seeds
		let args = InitializeInstruction::try_from_bytes(data)?;
		let authority_key = self.authority.address();
		let seeds = CounterState::seeds(authority_key);
		let seeds_with_bump = seeds.with_bump(args.bump);

		// Validate accounts
		self.authority.assert_signer()?;
		self.counter
			.assert_empty()?
			.assert_seeds_with_bump(&seeds_with_bump.as_slices(), &ID)?;
		self.system_program.assert_address(&system::ID)?;

		// Create the PDA account
		create_program_account_with_bump::<CounterState>(
			self.counter,
			self.authority,
			&ID,
			&seeds.as_slices(),
			args.bump,
		)?;

		// Initialize account data
		let mut counter = self.counter.as_account_mut::<CounterState>(&ID)?;
		counter.bump = args.bump;
		counter.count.set(0);

		log!("Counter initialized");

		Ok(())
	}
}

impl<'a> ProcessAccountInfos<'a> for IncrementAccounts<'a> {
	fn process(self, data: &[u8]) -> ProgramResult {
		// Validate instruction discriminator
		let _ = IncrementInstruction::try_from_bytes(data)?;

		// Validate accounts
		self.authority.assert_signer()?;

		let authority_key = self.authority.address();
		self.counter
			.assert_not_empty()?
			.assert_type::<CounterState>(&ID)?;

		// Verify the account is the PDA for the authority, using the stored
		// bump field (avoids re-deriving the canonical bump on-chain).
		CounterState::assert_seeds(self.counter, authority_key, &ID)?;

		// Mutate state
		let mut counter = self.counter.as_account_mut::<CounterState>(&ID)?;
		let current = counter.count.get();
		let next = current
			.checked_add(1)
			.ok_or(ProgramError::ArithmeticOverflow)?;

		counter.count.set(next);

		log!("Counter incremented");

		Ok(())
	}
}

// ---------------------------------------------------------------------------
// Entrypoint
// ---------------------------------------------------------------------------

#[cfg(feature = "bpf-entrypoint")]
pub mod entrypoint {
	use pina::*;

	use super::*;

	nostd_entrypoint!(process_instruction);

	#[inline(always)]
	pub fn process_instruction(
		program_id: &Address,
		accounts: &mut [AccountView],
		data: &[u8],
	) -> ProgramResult {
		let instruction: CounterInstruction = parse_instruction(program_id, &ID, data)?;

		match instruction {
			CounterInstruction::Initialize => InitializeAccounts::try_from(accounts)?.process(data),
			CounterInstruction::Increment => IncrementAccounts::try_from(accounts)?.process(data),
		}
	}
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn discriminator_values() {
		assert_eq!(CounterInstruction::Initialize as u8, 0);
		assert_eq!(CounterInstruction::Increment as u8, 1);
	}

	#[test]
	fn discriminator_roundtrip() {
		assert!(CounterInstruction::try_from(0u8).is_ok());
		assert!(CounterInstruction::try_from(1u8).is_ok());
		assert!(CounterInstruction::try_from(99u8).is_err());
	}

	#[test]
	fn counter_state_layout() {
		// CounterState: 1 (discriminator) + 1 (bump) + 8 (count) = 10 bytes.
		assert_eq!(CounterState::SIZE, 10);
	}

	#[test]
	fn counter_state_discriminator() {
		assert!(CounterState::matches_discriminator(&[
			CounterAccountType::CounterState as u8
		]));
		assert!(!CounterState::matches_discriminator(&[0u8]));
	}

	#[test]
	fn counter_state_initialization() {
		let mut bytes = [0u8; CounterState::SIZE];
		let state = CounterState::initialize(&mut bytes).unwrap();
		state.bump = 42;
		state.count.set(100);
		assert_eq!(state.bump, 42);
		assert_eq!(state.count.get(), 100);
	}

	#[test]
	fn counter_state_deserialize_roundtrip() {
		let mut bytes = [0u8; CounterState::SIZE];
		let state = CounterState::initialize(&mut bytes)
			.unwrap_or_else(|error| panic!("initialization failed: {error:?}"));
		state.bump = 7;
		state.count.set(999);
		let _ = state;
		assert_eq!(bytes.len(), 10);

		// Deserialize back.
		let deserialized = CounterState::try_from_bytes(&bytes)
			.unwrap_or_else(|e| panic!("deserialization failed: {e:?}"));
		assert_eq!(deserialized.bump, 7);
		assert_eq!(deserialized.count.get(), 999);
	}

	#[test]
	fn initialize_instruction_data_layout() {
		// InitializeInstruction: 1 (discriminator) + 1 (bump) = 2 bytes.
		assert_eq!(InitializeInstruction::SIZE, 2);
		assert!(InitializeInstruction::matches_discriminator(&[
			CounterInstruction::Initialize as u8
		]));
	}

	#[test]
	fn increment_instruction_data_layout() {
		// IncrementInstruction: 1 byte (discriminator only).
		assert_eq!(IncrementInstruction::SIZE, 1);
		assert!(IncrementInstruction::matches_discriminator(&[
			CounterInstruction::Increment as u8
		]));
	}

	#[test]
	fn initialize_instruction_try_from_bytes() {
		let data = [CounterInstruction::Initialize as u8, 42u8]; // discriminator + bump
		let ix = InitializeInstruction::try_from_bytes(&data)
			.unwrap_or_else(|e| panic!("failed: {e:?}"));
		assert_eq!(ix.bump, 42);
	}

	#[test]
	fn increment_instruction_try_from_bytes() {
		let data = [CounterInstruction::Increment as u8];
		let result = IncrementInstruction::try_from_bytes(&data);
		assert!(result.is_ok());
	}

	#[test]
	fn counter_seeds() {
		let authority = Address::new_from_array([1u8; 32]);
		let seeds = CounterState::seeds(&authority);
		let slices = seeds.as_slices();
		assert_eq!(slices.len(), 2);
		assert_eq!(slices[0], b"counter");
		assert_eq!(slices[1], authority.as_ref());
	}

	#[test]
	fn counter_seeds_with_bump() {
		let authority = Address::new_from_array([1u8; 32]);
		let seeds = CounterState::seeds(&authority);
		let with_bump = seeds.with_bump(42);
		let slices = with_bump.as_slices();
		assert_eq!(slices.len(), 3);
		assert_eq!(slices[0], b"counter");
		assert_eq!(slices[1], authority.as_ref());
		assert_eq!(slices[2], &[42u8]);
	}

	#[test]
	fn program_id_is_valid() {
		assert_ne!(ID, Address::default());
	}
}
