//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use migrations_program_client::instructions::Relay;
use migrations_program_client::instructions::RelayInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct RelayArgs {
	#[arg(long)]
	value: u64,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `referrer` account
	#[arg(long)]
	referrer: String,
	/// The `state` account
	#[arg(long)]
	state: String,
	/// The `migration_payer` account [default: payer]
	#[arg(long)]
	migration_payer: Option<String>,
	/// The `migration_program` account
	#[arg(long)]
	migration_program: String,
}

pub(crate) fn run(context: &CliContext, args: RelayArgs) -> Result<(), CliError> {
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let referrer = CliContext::pubkey("--referrer", &args.referrer)?;
	let state = CliContext::pubkey("--state", &args.state)?;
	let migration_payer = match &args.migration_payer {
		Some(value) => CliContext::pubkey("--migration_payer", value)?,
		None => context.payer_pubkey(),
	};
	let migration_program = CliContext::pubkey("--migration_program", &args.migration_program)?;
	let data = RelayInstructionData::new(|data| {
		data.value.set(args.value);
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Relay {
		authority,
		referrer,
		state,
		migration_payer,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
		migration_program,
	};

	context.send(accounts.instruction(data))
}
