// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/compact_accounts_program.dart';

final class InitializeCommand extends Command<void> {
  InitializeCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption('entry_count', mandatory: true, help: "entryCount")
      ..addOption('marker_count', mandatory: true, help: "markerCount")
      ..addOption(
        'authority',
        mandatory: false,
        help: "Funds rent and becomes the journal authority [default: payer]",
      )
      ..addOption(
        'journal',
        mandatory: false,
        help: "Empty canonical journal PDA [default: derived]",
      );
  }

  @override
  String get name => 'initialize';

  @override
  String get description => "initialize";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final journal = (results['journal'] as String?) != null
        ? pubkey('--journal', results['journal']! as String)
        : (await findJournalPda(
            seeds: JournalSeeds(authority: authority),
            programAddress: context.programAddress,
          )).$1;
    final bumpValue = integer('--bump', results['bump']! as String);
    final entryCountValue = integer(
      '--entry-count',
      results['entry_count']! as String,
    );
    final markerCountValue = integer(
      '--marker-count',
      results['marker_count']! as String,
    );
    final instruction = getInitializeInstruction(
      programAddress: context.programAddress,
      authority: authority,
      journal: journal,
      systemProgram: Address('11111111111111111111111111111111'),
      bump: bumpValue,
      entryCount: entryCountValue,
      markerCount: markerCountValue,
    );
    await context.send([instruction]);
  }
}
