// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/compact_accounts_program.dart';

final class WriteCommand extends Command<void> {
  WriteCommand() {
    argParser
      ..addOption('index', mandatory: true, help: "index")
      ..addOption('value', mandatory: true, help: "value")
      ..addOption(
        'authority',
        mandatory: false,
        help:
            "Funds growth if a future write patch changes the encoded length [default: payer]",
      )
      ..addOption(
        'journal',
        mandatory: false,
        help: "The journal account [default: derived]",
      );
  }

  @override
  String get name => 'write';

  @override
  String get description => "write";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final journal = (results['journal'] as String?) != null
        ? pubkey('--journal', results['journal']! as String)
        : (await findJournalPda(
            seeds: JournalSeeds(authority: authority),
            programAddress: context.programAddress,
          )).$1;
    final indexValue = integer('--index', results['index']! as String);
    final valueValue = bigInteger('--value', results['value']! as String);
    final instruction = getWriteInstruction(
      programAddress: context.programAddress,
      authority: authority,
      journal: journal,
      index: indexValue,
      value: valueValue,
    );
    await context.send([instruction]);
  }
}
