// Manual adjacent ABI migration generated by `pina migrations make`.
// Source version: 0 (3 bytes)
// Destination version: 1 (4 bytes)
// The planner validates the exact three-byte source before this total conversion runs.
pub(crate) const SOURCE_SIZE: usize = 3;
pub(crate) const DESTINATION_SIZE: usize = 4;
pub(crate) const WORKING_SIZE: usize = 4;

pub(crate) fn migrate(data: &mut [u8]) {
	let amount = u16::from(data[2]).to_le_bytes();
	data[2..4].copy_from_slice(&amount);
}
