// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { fetchJournal, findJournalPda } from "./client";
import {
	bigInteger,
	CliContext,
	CliError,
	pubkey,
	registerGlobals,
} from "./context";

export const fetchCommand = registerGlobals(new Command("fetch"))
	.description("Fetch and decode program accounts.")
	.addCommand(
		registerGlobals(new Command("journal"))
			.description(
				"A compact account with four independently encoded dynamic fields.\n\nThe fixed header includes a semantic `Option<u64>` encoded as\n`PodOption<PodU64>`. The title and optional note use compact strings, while\nentries and markers use vectors; only their active bytes are allocated.",
			)
			.option(
				"--address <address>",
				"Account address; overrides PDA derivation.",
			)
			.requiredOption("--authority <authority>", "PDA seed `authority`.")
			.action(async (options) => {
				const context = await CliContext.create(options);
				const authority = pubkey("--authority", options.authority as string);
				const address = options.address ??
					(await findJournalPda({ authority }, {
						programAddress: context.programAddress,
					}))[0];
				const account = await fetchJournal(context.rpc, address);
				if (account.programAddress !== context.programAddress) {
					throw new CliError(
						`account ${address} belongs to ${account.programAddress}, not the configured program`,
					);
				}
				printAccount(context.json, "journal", address, account.data);
			}),
	);

function printAccount(
	json: boolean,
	name: string,
	address: string,
	data: unknown,
): void {
	if (json) {
		console.log(JSON.stringify({ address, ...(data as object) }, null, "\t"));
		return;
	}
	console.log(`${name} ${address}`);
	const fields = data as Record<string, unknown>;
	for (const [key, value] of Object.entries(fields)) {
		console.log(`  ${key}: ${value}`);
	}
}
