// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { initializeCommand } from "./commands/initialize.ts";
import { renameCommand } from "./commands/rename.ts";
import { resizeCommand } from "./commands/resize.ts";
import { writeCommand } from "./commands/write.ts";
import { registerGlobals } from "./context.ts";
import { fetchCommand } from "./fetch.ts";

const program = registerGlobals(new Command())
	.name("compact-accounts-program-cli")
	.version("0.1.0")
	.description("Command-line interface for compactAccountsProgram");
program.addCommand(initializeCommand);
program.addCommand(resizeCommand);
program.addCommand(writeCommand);
program.addCommand(renameCommand);
program.addCommand(fetchCommand);
program.parseAsync(process.argv);
