// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getMakeInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const makeCommand = registerGlobals(new Command("make"))
	.description("make")
	.requiredOption("--seed <seed>", "seed")
	.requiredOption("--amount-a <amountA>", "amountA")
	.requiredOption("--amount-b <amountB>", "amountB")
	.requiredOption("--bump <bump>", "bump")
	.option("--maker <maker>", "The `maker` account [default: payer]")
	.requiredOption("--mint-a <mintA>", "The `mint_a` account")
	.requiredOption("--mint-b <mintB>", "The `mint_b` account")
	.requiredOption("--maker-ata-a <makerAtaA>", "The `maker_ata_a` account")
	.requiredOption("--escrow <escrow>", "The `escrow` account")
	.requiredOption("--vault <vault>", "The `vault` account")
	.requiredOption(
		"--token-program <tokenProgram>",
		"The `token_program` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			seed: bigInteger("--seed", options.seed),
			amountA: bigInteger("--amount-a", options.amountA),
			amountB: bigInteger("--amount-b", options.amountB),
			bump: smallInteger("--bump", options.bump),
			maker: context.payer,
			mintA: pubkey("--mint-a", options.mintA),
			mintB: pubkey("--mint-b", options.mintB),
			makerAtaA: pubkey("--maker-ata-a", options.makerAtaA),
			escrow: pubkey("--escrow", options.escrow),
			vault: pubkey("--vault", options.vault),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
		};
		const instruction = getMakeInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
