//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use solana_sdk::pubkey::Pubkey;
use todo_program_client::instructions::Initialize;
use todo_program_client::instructions::InitializeInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct InitializeArgs {
	#[arg(long)]
	bump: u8,
	#[arg(long)]
	digest: String,
	/// The `owner` account [default: payer]
	#[arg(long)]
	owner: Option<String>,
	/// The `todo` account [default: derived]
	#[arg(long)]
	todo: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: InitializeArgs) -> Result<(), CliError> {
	let digest = CliContext::bytes::<32>("--digest", &args.digest)?;
	let owner = match &args.owner {
		Some(value) => CliContext::pubkey("--owner", value)?,
		None => context.payer_pubkey(),
	};
	let todo = match &args.todo {
		Some(value) => CliContext::pubkey("--todo", value)?,
		None => {
			Pubkey::find_program_address(
				&["todo".as_bytes(), owner.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let data = InitializeInstructionData::new(|data| {
		data.bump = args.bump;
		data.digest = digest;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Initialize {
		owner,
		todo,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
