[package]
name = "events_program-surfpool-tests"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
base64 = { workspace = true, default-features = true }
generated_client = { package = "events_program-client", path = "../../../../codama/clients/rust/events_program" }
pina = { workspace = true, features = ["derive", "logs", "validation"] }
pina_test = { workspace = true }
