// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/declare_program.dart';

final class ValidateExternalProgramCommand extends Command<void> {
  ValidateExternalProgramCommand() {
    argParser
      ..addOption(
        'authority',
        mandatory: false,
        help: "The authority account [default: payer]",
      )
      ..addOption(
        'external_program',
        mandatory: true,
        help: "The external_program account",
      );
  }

  @override
  String get name => 'validate_external_program';

  @override
  String get description => "validate_external_program";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final externalProgram = pubkey(
      '--external-program',
      results['external_program']! as String,
    );

    final instruction = getValidateExternalProgramInstruction(
      programAddress: context.programAddress,
      authority: authority,
      externalProgram: externalProgram,
    );
    await context.send([instruction]);
  }
}
