//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use profile_program_client;
use serde_json::Value;
use serde_json::json;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Subcommand)]
pub enum Command {
	/// On-chain profile state.
	///
	/// The `#[account]` macro generates:
	/// - A discriminator field (`ProfileAccountType::ProfileState`) as the first
	/// byte.
	/// - `PinaAccount` and `PinaPod` validation for checked zero-copy access.
	/// - `HasDiscriminator` linking this account to
	/// `ProfileAccountType::ProfileState`.
	/// - `initialize` and `try_from_bytes` helpers for caller-owned storage.
	///
	/// Layout (240 bytes total):
	/// ```text
	/// | offset | size | field          |
	/// |--------|------|----------------|
	/// | 0      | 1    | discriminator  |
	/// | 1      | 1    | bump           |
	/// | 2      | 33   | name (`String<32>`)  |
	/// | 35     | 129  | bio (`String<128>`)  |
	/// | 164    | 66   | tags (`Vec<u64, 8>`) |
	/// | 230    | 9    | favorite_tag (PodOption<PodU64>) |
	/// | 239    | 1    | active (PodBool) |
	/// ```
	ProfileState(ProfileStateArgs),
}

#[derive(Debug, Args)]
pub struct ProfileStateArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `authority`.
	#[arg(long)]
	authority: Option<String>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::ProfileState(args) => fetch_profile_state(context, args),
	}
}

fn fetch_profile_state(context: &CliContext, args: ProfileStateArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let authority = match &args.authority {
				Some(value) => CliContext::pubkey("--authority", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "profile-state".to_string(),
						seed: "--authority".to_string(),
					});
				}
			};
			let seeds: &[&[u8]] = &["profile".as_bytes(), authority.as_ref()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match profile_program_client::accounts::ProfileState::from_bytes(&data) {
		Ok(account) => profile_state_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "profile-state", &address, &value);
	Ok(())
}

fn profile_state_json(account: &profile_program_client::accounts::ProfileStateZc) -> Value {
	json!({
		"bump": account.bump,
		"name": account.name.as_str(),
		"bio": account.bio.as_str(),
		"tags": account.tags.iter().map(|value| value.get()).collect::<Vec<_>>(),
		"favorite_tag": account.favorite_tag.get().map(|value| value.get()),
		"active": account.active.get(),
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
