//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments,
	rustdoc::broken_intra_doc_links
)]

use clap::Args;
use privacy_pool_program_client::instructions::ApproveDisclosure;
use privacy_pool_program_client::instructions::ApproveDisclosureInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ApproveDisclosureArgs {
	/// Reserved; must be zero.
	#[arg(long)]
	reserved: u8,
	/// The `pool_config` account [default: derived]
	#[arg(long)]
	pool_config: Option<String>,
	/// The `custodian_registry` account [default: derived]
	#[arg(long)]
	custodian_registry: Option<String>,
	/// The `disclosure_request` account
	#[arg(long)]
	disclosure_request: String,
	/// The `disclosure_log` account [default: derived]
	#[arg(long)]
	disclosure_log: Option<String>,
	/// The `clock` account
	#[arg(long)]
	clock: String,
}

pub(crate) fn run(context: &CliContext, args: ApproveDisclosureArgs) -> Result<(), CliError> {
	let custodian = context.payer_pubkey();
	let pool_config = match &args.pool_config {
		Some(value) => CliContext::pubkey("--pool_config", value)?,
		None => {
			Pubkey::find_program_address(
				&["privacy-pool-config".as_bytes()],
				&context.program_address,
			)
			.0
		}
	};
	let custodian_registry = match &args.custodian_registry {
		Some(value) => CliContext::pubkey("--custodian_registry", value)?,
		None => {
			Pubkey::find_program_address(
				&["privacy-pool-custodians".as_bytes()],
				&context.program_address,
			)
			.0
		}
	};
	let disclosure_request = CliContext::pubkey("--disclosure_request", &args.disclosure_request)?;
	let disclosure_log = match &args.disclosure_log {
		Some(value) => CliContext::pubkey("--disclosure_log", value)?,
		None => {
			Pubkey::find_program_address(&["privacy-pool-log".as_bytes()], &context.program_address)
				.0
		}
	};
	let clock = CliContext::pubkey("--clock", &args.clock)?;
	let data = ApproveDisclosureInstructionData::new(|data| {
		data.reserved = args.reserved;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = ApproveDisclosure {
		custodian,
		pool_config,
		custodian_registry,
		disclosure_request,
		disclosure_log,
		clock,
	};

	context.send(accounts.instruction(data))
}
