//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use privacy_pool_program_client::instructions::RegisterRequester;
use privacy_pool_program_client::instructions::RegisterRequesterInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct RegisterRequesterArgs {
	#[arg(long)]
	requester: String,
	#[arg(long)]
	max_tier: u8,
	/// The `pool_config` account
	#[arg(long)]
	pool_config: String,
	/// The `requester_registry` account
	#[arg(long)]
	requester_registry: String,
}

pub(crate) fn run(context: &CliContext, args: RegisterRequesterArgs) -> Result<(), CliError> {
	let requester = CliContext::pubkey("--requester", &args.requester)?;
	let authority = context.payer_pubkey();
	let pool_config = CliContext::pubkey("--pool_config", &args.pool_config)?;
	let requester_registry = CliContext::pubkey("--requester_registry", &args.requester_registry)?;
	let data = RegisterRequesterInstructionData::new(|data| {
		data.requester = requester;
		data.max_tier = args.max_tier;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = RegisterRequester {
		authority,
		pool_config,
		requester_registry,
	};

	context.send(accounts.instruction(data))
}
