//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments,
	rustdoc::broken_intra_doc_links
)]

use clap::Args;
use privacy_pool_program_client::instructions::RegisterRequester;
use privacy_pool_program_client::instructions::RegisterRequesterInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct RegisterRequesterArgs {
	#[arg(long)]
	requester: String,
	/// Highest tier the entity may file at.
	#[arg(long)]
	max_tier: u8,
	/// The `pool_config` account [default: derived]
	#[arg(long)]
	pool_config: Option<String>,
	/// The `requester_registry` account [default: derived]
	#[arg(long)]
	requester_registry: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: RegisterRequesterArgs) -> Result<(), CliError> {
	let requester = CliContext::pubkey("--requester", &args.requester)?;
	let authority = context.payer_pubkey();
	let pool_config = match &args.pool_config {
		Some(value) => CliContext::pubkey("--pool_config", value)?,
		None => {
			Pubkey::find_program_address(
				&["privacy-pool-config".as_bytes()],
				&context.program_address,
			)
			.0
		}
	};
	let requester_registry = match &args.requester_registry {
		Some(value) => CliContext::pubkey("--requester_registry", value)?,
		None => {
			Pubkey::find_program_address(
				&["privacy-pool-requesters".as_bytes()],
				&context.program_address,
			)
			.0
		}
	};
	let data = RegisterRequesterInstructionData::new(|data| {
		data.requester = requester;
		data.max_tier = args.max_tier;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = RegisterRequester {
		authority,
		pool_config,
		requester_registry,
	};

	context.send(accounts.instruction(data))
}
