//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use privacy_pool_program_client::instructions::ResolveChallenge;
use privacy_pool_program_client::instructions::ResolveChallengeInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ResolveChallengeArgs {
	#[arg(long)]
	approve: u8,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `pool_config` account
	#[arg(long)]
	pool_config: String,
	/// The `disclosure_request` account
	#[arg(long)]
	disclosure_request: String,
}

pub(crate) fn run(context: &CliContext, args: ResolveChallengeArgs) -> Result<(), CliError> {
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let pool_config = CliContext::pubkey("--pool_config", &args.pool_config)?;
	let disclosure_request = CliContext::pubkey("--disclosure_request", &args.disclosure_request)?;
	let data = ResolveChallengeInstructionData::new(|data| {
		data.approve = args.approve;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = ResolveChallenge {
		authority,
		pool_config,
		disclosure_request,
	};

	context.send(accounts.instruction(data))
}
