//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use privacy_pool_program_client::instructions::Transfer;
use privacy_pool_program_client::instructions::TransferInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct TransferArgs {
	#[arg(long)]
	bump: u8,
	#[arg(long)]
	nullifier: String,
	#[arg(long)]
	root: String,
	#[arg(long)]
	new_commitment: String,
	#[arg(long)]
	new_view_pubkey: String,
	#[arg(long)]
	envelope_len: u8,
	#[arg(long)]
	envelope: String,
	#[arg(long)]
	shares: String,
	#[arg(long)]
	proof_a: String,
	#[arg(long)]
	proof_b: String,
	#[arg(long)]
	proof_c: String,
	/// The `pool_config` account
	#[arg(long)]
	pool_config: String,
	/// The `merkle_tree` account
	#[arg(long)]
	merkle_tree: String,
	/// The `nullifier_set` account
	#[arg(long)]
	nullifier_set: String,
	/// The `verifying_key_account` account
	#[arg(long)]
	verifying_key_account: String,
	/// The `note_commitment` account
	#[arg(long)]
	note_commitment: String,
}

pub(crate) fn run(context: &CliContext, args: TransferArgs) -> Result<(), CliError> {
	let nullifier = CliContext::bytes::<32>("--nullifier", &args.nullifier)?;
	let root = CliContext::bytes::<32>("--root", &args.root)?;
	let new_commitment = CliContext::bytes::<32>("--new_commitment", &args.new_commitment)?;
	let new_view_pubkey = CliContext::bytes::<32>("--new_view_pubkey", &args.new_view_pubkey)?;
	let envelope = CliContext::bytes::<128>("--envelope", &args.envelope)?;
	let shares = CliContext::bytes::<144>("--shares", &args.shares)?;
	let proof_a = CliContext::bytes::<64>("--proof_a", &args.proof_a)?;
	let proof_b = CliContext::bytes::<128>("--proof_b", &args.proof_b)?;
	let proof_c = CliContext::bytes::<64>("--proof_c", &args.proof_c)?;
	let pool_config = CliContext::pubkey("--pool_config", &args.pool_config)?;
	let payer = context.payer_pubkey();
	let merkle_tree = CliContext::pubkey("--merkle_tree", &args.merkle_tree)?;
	let nullifier_set = CliContext::pubkey("--nullifier_set", &args.nullifier_set)?;
	let verifying_key_account =
		CliContext::pubkey("--verifying_key_account", &args.verifying_key_account)?;
	let note_commitment = CliContext::pubkey("--note_commitment", &args.note_commitment)?;
	let data = TransferInstructionData::new(|data| {
		data.bump = args.bump;
		data.nullifier = nullifier;
		data.root = root;
		data.new_commitment = new_commitment;
		data.new_view_pubkey = new_view_pubkey;
		data.envelope_len = args.envelope_len;
		data.envelope = envelope;
		data.shares = shares;
		data.proof_a = proof_a;
		data.proof_b = proof_b;
		data.proof_c = proof_c;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Transfer {
		pool_config,
		payer,
		merkle_tree,
		nullifier_set,
		verifying_key_account,
		note_commitment,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
