// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getToggleCompletedInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const toggleCompletedCommand = registerGlobals(
	new Command("toggle_completed"),
)
	.description("toggleCompleted")
	.option("--owner <owner>", "The `owner` account [default: payer]")
	.option("--todo <todo>", "The `todo` account [default: derived]")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			owner: context.payer,
			todo: options.todo,
		};
		const instruction = await getToggleCompletedInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
