//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use prop_amm_program_client::instructions::Initialize;
use prop_amm_program_client::instructions::InitializeInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct InitializeArgs {}

pub(crate) fn run(context: &CliContext, args: InitializeArgs) -> Result<(), CliError> {
	let payer = context.payer_pubkey();
	let oracle = context.payer_pubkey();
	let data = InitializeInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Initialize {
		payer,
		oracle,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
