//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use prop_amm_program_client::instructions::Update;
use prop_amm_program_client::instructions::UpdateInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct UpdateArgs {
	#[arg(long)]
	new_price: u64,
	/// The `oracle` account
	#[arg(long)]
	oracle: String,
	/// The `authority` account [default: payer]
	#[arg(long)]
	authority: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: UpdateArgs) -> Result<(), CliError> {
	let oracle = CliContext::pubkey("--oracle", &args.oracle)?;
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let data = UpdateInstructionData::new(|data| {
		data.new_price.set(args.new_price);
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Update { oracle, authority };

	context.send(accounts.instruction(data))
}
