// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { initializeCommand } from "./commands/initialize.ts";
import { reallocCommand } from "./commands/realloc.ts";
import { realloc2Command } from "./commands/realloc2.ts";
import { registerGlobals } from "./context.ts";
import { fetchCommand } from "./fetch.ts";

const program = registerGlobals(new Command())
	.name("account-realloc-program-cli")
	.version("0.1.0")
	.description("Command-line interface for accountReallocProgram");
program.addCommand(initializeCommand);
program.addCommand(reallocCommand);
program.addCommand(realloc2Command);
program.addCommand(fetchCommand);
program.parseAsync(process.argv);
