//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use solana_sdk::pubkey::Pubkey;
use transfer_sol_program_client::instructions::CpiTransfer;
use transfer_sol_program_client::instructions::CpiTransferInstructionData;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct CpiTransferArgs {
	#[arg(long)]
	amount: u64,
	/// The sender. Must be a signer and writable (lamports will be debited) [default: payer]
	#[arg(long)]
	sender: Option<String>,
	/// The recipient. Must be writable (lamports will be credited)
	#[arg(long)]
	recipient: String,
}

pub(crate) fn run(context: &CliContext, args: CpiTransferArgs) -> Result<(), CliError> {
	let sender = match &args.sender {
		Some(value) => CliContext::pubkey("--sender", value)?,
		None => context.payer_pubkey(),
	};
	let recipient = CliContext::pubkey("--recipient", &args.recipient)?;
	let data = CpiTransferInstructionData::new(|data| {
		data.amount.set(args.amount);
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = CpiTransfer {
		sender,
		recipient,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
