//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

pub mod cpi_transfer;
pub mod direct_transfer;

pub use cpi_transfer::CpiTransferArgs;
pub use direct_transfer::DirectTransferArgs;
