//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: 6fb8b48918e8ac3e1f045426663b865bbff7874016bc059dcbbef26f622370a1
// program-id: GJQcuWrT2f3f4KNuJcXhhwUa1ZQTYbxzzJ1hotzKu8hS
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "GJQcuWrT2f3f4KNuJcXhhwUa1ZQTYbxzzJ1hotzKu8hS";

/// ABI layout for the `State` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "State";
	/// Current schema version.
	pub const VERSION: u32 = 2;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "a4aaf89086b9d10d3874753007dae38c20ac7f50d6fe627420c42bdae963de05";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 42;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 42;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("authority", MIGRATION_HEADER_SIZE + 0, 32),
		("value", MIGRATION_HEADER_SIZE + 32, 8),
		("enabled", MIGRATION_HEADER_SIZE + 40, 1),
		("revision", MIGRATION_HEADER_SIZE + 41, 1),
	];
}

/// ABI layout for the `ManualState` account.
pub mod account_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ManualState";
	/// Current schema version.
	pub const VERSION: u32 = 2;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "6fa44f9998506683074b28f7232ce4655331f49d1cd85249249fd797d256b1c1";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Compact header size in bytes.
	pub const HEADER_SIZE: usize = 1;
	/// Maximum encoded size in bytes.
	pub const MAX_SIZE: usize = 6;
	/// Byte granularity of valid allocations.
	pub const TAIL_ALIGNMENT: usize = 1;
	/// Smallest valid encoded size, including the envelope header.
	pub const MIN_SIZE: usize = MIGRATION_HEADER_SIZE + HEADER_SIZE;
}

/// ABI layout for the `CompactState` account.
pub mod account_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CompactState";
	/// Current schema version.
	pub const VERSION: u32 = 1;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "6df091cab98908e26f4536a026f72c888d01cff2dc1610b2b743dcff646e01ca";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Compact header size in bytes.
	pub const HEADER_SIZE: usize = 3;
	/// Maximum encoded size in bytes.
	pub const MAX_SIZE: usize = 11;
	/// Byte granularity of valid allocations.
	pub const TAIL_ALIGNMENT: usize = 1;
	/// Smallest valid encoded size, including the envelope header.
	pub const MIN_SIZE: usize = MIGRATION_HEADER_SIZE + HEADER_SIZE;
}

/// ABI layout for the `ValueChangedEvent` event.
pub mod event_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ValueChangedEvent";
	/// Current schema version.
	pub const VERSION: u32 = 1;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "b16746feb2ea35413fcc06f392d263dbbe11febcd227806b70d1885f95c86df6";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("value", MIGRATION_HEADER_SIZE + 0, 8),
		("memo", MIGRATION_HEADER_SIZE + 8, 2),
	];
}

/// ABI layout for the `UpdateInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "UpdateInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 2;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "b16746feb2ea35413fcc06f392d263dbbe11febcd227806b70d1885f95c86df6";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 10;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 10;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("value", MIGRATION_HEADER_SIZE + 0, 8),
		("memo", MIGRATION_HEADER_SIZE + 8, 2),
	];
}

