// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getInitializeInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const initializeCommand = registerGlobals(new Command("initialize"))
	.description("initialize")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = null;
		const instruction = getInitializeInstruction(
			...[],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
