//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

//! Generated CLI for the `validationProgram` program.

mod commands;
mod context;
mod fetch;
use clap::Parser;
use clap::Subcommand;
use context::CliContext;
use solana_sdk::pubkey::Pubkey;

/// Command-line interface for validationProgram
#[derive(Debug, Parser)]
#[command(name = "validation-program-cli", version = env!("CARGO_PKG_VERSION"), propagate_version = true)]
struct Cli {
	/// RPC endpoint: `mainnet`, `devnet`, `testnet`, `localhost`, or an https URL.
	#[arg(short = 'u', long, default_value = "devnet", env = "SOLANA_URL")]
	url: String,

	/// Payer keypair file in the standard Solana JSON byte-array format.
	#[arg(
		short = 'k',
		long,
		default_value = "~/.config/solana/id.json",
		env = "PINA_KEYPAIR"
	)]
	keypair: String,

	/// Override the on-chain program address.
	#[arg(long)]
	program_id: Option<String>,

	/// Simulate the transaction and print its logs instead of sending.
	#[arg(long)]
	simulate: bool,

	/// Print machine-readable JSON output.
	#[arg(long)]
	json: bool,

	#[command(subcommand)]
	command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
	InitializePolicy(commands::InitializePolicyArgs),

	CheckPolicy(commands::CheckPolicyArgs),
	/// Fetch and decode a program account.
	#[command(subcommand)]
	Fetch(fetch::Command),
}

fn main() {
	let cli = Cli::parse();
	if let Err(error) = run(cli) {
		eprintln!("error: {error}");
		std::process::exit(1);
	}
}

fn run(cli: Cli) -> Result<(), context::CliError> {
	let program_address = match &cli.program_id {
		Some(value) => CliContext::pubkey("--program-id", value)?,
		None => Pubkey::from_str_const("GKYaKKaAJvuzkH2GKkaEFAqESh9NEobZ3V2Ub7qbpVYn"),
	};
	let context = CliContext::new(
		&cli.url,
		&cli.keypair,
		program_address,
		cli.simulate,
		cli.json,
	)?;

	match cli.command {
		Command::InitializePolicy(args) => commands::initialize_policy::run(&context, args),
		Command::CheckPolicy(args) => commands::check_policy::run(&context, args),
		Command::Fetch(command) => fetch::run(&context, command),
	}
}
