//! Generate the machine-checked ABI layout test for a program.
//!
//! Every program that opts into migrations has a checked-in manifest recording
//! each contract's size and per-field byte offsets. Nothing consumed that data
//! for tests, so consumers hand-wrote layout assertions — bitflip's
//! `assert_eq!(ConfigState::SIZE, 238)` style, kickjump's `data[203]` offset
//! reads — and those stayed correct only as long as someone remembered to
//! update them. Enabling the migration envelope shifts every byte after the
//! discriminator, so a forgotten offset produced a silent indexer gap
//! (bitflip) or a post-deploy `InvalidAmmProgram` (kickjump).
//!
//! [`generate`] renders a test module from the manifest. `pina migrations make`
//! writes it, and `pina migrations check` fails when it no longer matches, so a
//! layout change that forgets an offset goes red in the same pull request.

use std::fmt::Write as _;
use std::path::Path;

use pina_abi::ContractKind;
use pina_abi::MigrationManifest;
use pina_abi::PhysicalLayout;
use pina_abi::SchemaVersion;

/// Path of the generated ABI layout test, relative to the program directory.
pub const ABI_LAYOUT_TEST_PATH: &str = "tests/abi_layout.rs";

/// Render the ABI layout test for `manifest`.
///
/// `crate_name` is the program's library name, used to import its types. When
/// it is `None` the type-binding guard is omitted and only the recorded
/// constants are emitted.
///
/// The output is deterministic for a given manifest, so regenerating an
/// unchanged program produces byte-identical content.
pub fn generate(manifest: &MigrationManifest, crate_name: Option<&str>) -> String {
	let mut output = String::new();
	output.push_str(
		"//! Machine-checked ABI layout assertions.\n//!\n//! Generated by `pina migrations \
		 make`. Do not edit.\n//!\n//! Run `pina migrations make` after changing a schema; `pina \
		 migrations\n//! check` fails when this file no longer matches the manifest. A \
		 layout\n//! change that forgets an offset fails `cargo test` in the same change.\n\n",
	);
	let _ = writeln!(output, "// manifest-sha256: {}", manifest.sha256());
	output.push_str("// program-id: ");
	output.push_str(&manifest.program_id);
	output.push('\n');
	output.push_str("// version-type: ");
	output.push_str(manifest.version_type.as_str());
	output.push('\n');

	output.push_str(
		"\n#![allow(clippy::identity_op, \
		 clippy::eq_op)]\n#![allow(clippy::unreadable_literal)]\n\n",
	);

	// The program id is a constant every contract's guard compares against.
	let _ = writeln!(output, "/// Program id recorded in the manifest.");
	let _ = writeln!(
		output,
		"pub const PROGRAM_ID: &str = {:?};\n",
		manifest.program_id
	);

	if let Some(crate_name) = crate_name {
		render_crate_assertions(&mut output, manifest, crate_name);
	}

	for (key, history) in &manifest.contracts {
		let Some(current) = history.current() else {
			continue;
		};
		render_contract(
			&mut output,
			key,
			&history.rust_name,
			&history.identity.kind,
			history.identity.discriminator_bytes,
			manifest.version_type.bytes() as u8,
			current,
		);
	}

	output
}

/// Emit the module that binds manifest constants to the program's own types.
///
/// The per-contract constants document the geometry; this module is what makes
/// it a guard, so a schema change that moves a byte and forgets to re-run
/// `make` fails `cargo test`.
fn render_crate_assertions(output: &mut String, manifest: &MigrationManifest, crate_name: &str) {
	output.push_str("/// Bind the recorded geometry to the program's own types.\n");
	output.push_str("pub mod layout_guard {\n");
	output.push_str("\t#![allow(unused_imports)]\n\n");
	output.push_str("\tuse super::*;\n");
	let _ = writeln!(output, "\tuse {crate_name}::*;\n");

	// The program declares its own `ID` through `declare_id!`; the manifest
	// records the same value, so they must agree.
	output.push_str("\t#[test]\n");
	output.push_str("\tfn manifest_program_id_matches_the_program() {\n");
	output.push_str("\t\tassert_eq!(\n");
	output.push_str("\t\t\tID.to_string(),\n");
	output.push_str("\t\t\tsuper::PROGRAM_ID,\n");
	output.push_str("\t\t\t\"manifest program id drifted from `declare_id!`\"\n");
	output.push_str("\t\t);\n");
	output.push_str("\t}\n");

	for (key, history) in &manifest.contracts {
		let Some(current) = history.current() else {
			continue;
		};
		// Only fixed-layout contracts expose a `SIZE` constant on the type.
		if let PhysicalLayout::Fixed { .. } = &current.schema.physical {
			let module = sanitize_identifier(key);
			let rust_name = &history.rust_name;
			let version = current.version;
			let _ = writeln!(output, "\n\t#[test]");
			let _ = writeln!(output, "\tfn {module}_size_matches_the_program_type() {{");
			let _ = writeln!(
				output,
				"\t\tassert_eq!({rust_name}::SIZE, super::{module}::SIZE,"
			);
			let _ = writeln!(
				output,
				"\t\t\t\"{rust_name} changed size without regenerating the manifest (recorded \
				 version {version})\");"
			);
			let _ = writeln!(output, "\t}}");
		}
	}

	output.push_str("}\n\n");
}

/// Render one contract's constants.
fn render_contract(
	output: &mut String,
	key: &str,
	rust_name: &str,
	kind: &ContractKind,
	discriminator_bytes: u8,
	version_bytes: u8,
	current: &SchemaVersion,
) {
	let kind_label = match kind {
		ContractKind::Account => "account",
		ContractKind::Instruction => "instruction",
		ContractKind::Event => "event",
	};
	let module = sanitize_identifier(key);
	let envelope = usize::from(discriminator_bytes) + usize::from(version_bytes);

	let _ = writeln!(output, "/// ABI layout for the `{rust_name}` {kind_label}.");
	let _ = writeln!(output, "pub mod {module} {{");
	let _ = writeln!(output, "\t/// Manifest contract key.");
	let _ = writeln!(output, "\tpub const KEY: &str = {key:?};");
	let _ = writeln!(output, "\t/// Rust type name as declared in the program.");
	let _ = writeln!(output, "\tpub const RUST_NAME: &str = {rust_name:?};");
	let _ = writeln!(output, "\t/// Current schema version.");
	let _ = writeln!(output, "\tpub const VERSION: u32 = {};", current.version);
	let _ = writeln!(output, "\t/// Schema hash recorded for this version.");
	let _ = writeln!(
		output,
		"\tpub const SCHEMA_SHA256: &str = {:?};",
		current.schema_sha256
	);
	// The envelope geometry is the part consumers get wrong by hand: enabling
	// migrations inserts a version byte after the discriminator, so every byte
	// after the discriminator shifts by one. Recording it explicitly makes the
	// shift a checked constant instead of an implicit addition.
	let _ = writeln!(output, "\t/// Width of the discriminator in bytes.");
	let _ = writeln!(
		output,
		"\tpub const DISCRIMINATOR_BYTES: usize = {discriminator_bytes};"
	);
	let _ = writeln!(output, "\t/// Byte offset of the migration version field.");
	let _ = writeln!(
		output,
		"\tpub const VERSION_OFFSET: usize = {discriminator_bytes};"
	);
	let _ = writeln!(
		output,
		"\t/// Width of the migration version field in bytes."
	);
	let _ = writeln!(
		output,
		"\tpub const VERSION_BYTES: usize = {version_bytes};"
	);
	let _ = writeln!(
		output,
		"\t/// Bytes occupied by the discriminator and version envelope together."
	);
	let _ = writeln!(
		output,
		"\tpub const MIGRATION_HEADER_SIZE: usize = {envelope};"
	);

	match &current.schema.physical {
		PhysicalLayout::Fixed { size, fields } => {
			let payload = current.schema.fixed_payload_size().unwrap_or(0);
			let _ = writeln!(
				output,
				"\t/// Payload size in bytes, excluding the envelope header."
			);
			let _ = writeln!(output, "\tpub const PAYLOAD_SIZE: usize = {payload};");
			let _ = writeln!(
				output,
				"\t/// Total encoded size in bytes, including the envelope header."
			);
			let _ = writeln!(
				output,
				"\tpub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;"
			);
			let _ = writeln!(
				output,
				"\t/// Manifest payload size; must agree with `PAYLOAD_SIZE`."
			);
			let _ = writeln!(output, "\tpub const MANIFEST_PAYLOAD_SIZE: usize = {size};");
			let _ = writeln!(
				output,
				"\t/// `(name, absolute_offset, size)` in encoded bytes."
			);
			let _ = writeln!(output, "\tpub const FIELDS: &[(&str, usize, usize)] = &[");
			for field in fields {
				let _ = writeln!(
					output,
					"\t\t({:?}, MIGRATION_HEADER_SIZE + {}, {}),",
					field.name, field.offset, field.size
				);
			}
			let _ = writeln!(output, "\t];");
		}
		PhysicalLayout::Compact {
			header_size,
			maximum_size,
			tail_alignment,
			..
		} => {
			let _ = writeln!(output, "\t/// Compact header size in bytes.");
			let _ = writeln!(output, "\tpub const HEADER_SIZE: usize = {header_size};");
			let _ = writeln!(output, "\t/// Maximum encoded size in bytes.");
			let _ = writeln!(output, "\tpub const MAX_SIZE: usize = {maximum_size};");
			let _ = writeln!(output, "\t/// Byte granularity of valid allocations.");
			let _ = writeln!(
				output,
				"\tpub const TAIL_ALIGNMENT: usize = {tail_alignment};"
			);
			let _ = writeln!(
				output,
				"\t/// Smallest valid encoded size, including the envelope header."
			);
			let _ = writeln!(
				output,
				"\tpub const MIN_SIZE: usize = MIGRATION_HEADER_SIZE + HEADER_SIZE;"
			);
		}
	}

	let _ = writeln!(output, "}}\n");
}

/// Turn a manifest contract key into a valid Rust module name.
fn sanitize_identifier(key: &str) -> String {
	let mut identifier = String::with_capacity(key.len());
	for character in key.chars() {
		if character.is_ascii_alphanumeric() {
			identifier.push(character.to_ascii_lowercase());
		} else {
			identifier.push('_');
		}
	}
	if identifier.starts_with(|character: char| character.is_ascii_digit()) {
		identifier.insert(0, '_');
	}
	identifier
}

/// Read a previously generated file, if it exists.
pub fn read_existing(program_dir: &Path) -> std::io::Result<Option<String>> {
	let path = program_dir.join(ABI_LAYOUT_TEST_PATH);
	match std::fs::read_to_string(&path) {
		Ok(contents) => Ok(Some(contents)),
		Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
		Err(error) => Err(error),
	}
}
