//! Generate the machine-checked ABI layout test for a program.
//!
//! Every program that opts into migrations has a checked-in manifest recording
//! each contract's size and per-field byte offsets. Nothing consumed that data
//! for tests, so consumers hand-wrote layout assertions — bitflip's
//! `assert_eq!(ConfigState::SIZE, 238)` style, kickjump's `data[203]` offset
//! reads — and those stayed correct only as long as someone remembered to
//! update them. Enabling the migration envelope shifts every byte after the
//! discriminator, so a forgotten offset produced a silent indexer gap
//! (bitflip) or a post-deploy `InvalidAmmProgram` (kickjump).
//!
//! [`generate`] renders a test module from the manifest. `pina migrations make`
//! writes it, and `pina migrations check` fails when it no longer matches, so a
//! layout change that forgets an offset goes red in the same pull request.

use std::fmt::Write as _;
use std::path::Path;

use pina_abi::ContractKind;
use pina_abi::MigrationManifest;
use pina_abi::PhysicalLayout;
use pina_abi::SchemaVersion;

/// Path of the generated ABI layout test, relative to the program directory.
pub const ABI_LAYOUT_TEST_PATH: &str = "tests/abi_layout.rs";

/// Render the ABI layout test for `manifest`.
///
/// The output is deterministic for a given manifest, so regenerating an
/// unchanged program produces byte-identical content.
pub fn generate(manifest: &MigrationManifest) -> String {
	let mut output = String::new();
	output.push_str(
		"//! Machine-checked ABI layout assertions.\n//!\n//! Generated by `pina migrations \
		 make`. Do not edit.\n//!\n//! Run `pina migrations make` after changing a schema; `pina \
		 migrations\n//! check` fails when this file no longer matches the manifest. A \
		 layout\n//! change that forgets an offset fails `cargo test` in the same change.\n\n",
	);
	let _ = writeln!(output, "// manifest-sha256: {}", manifest.sha256());
	output.push_str("// program-id: ");
	output.push_str(&manifest.program_id);
	output.push('\n');
	output.push_str("// version-type: ");
	output.push_str(manifest.version_type.as_str());
	output.push('\n');

	output.push_str(
		"\n#![allow(clippy::identity_op, \
		 clippy::eq_op)]\n#![allow(clippy::unreadable_literal)]\n\n",
	);

	render_program_identity(&mut output, manifest);

	for (key, history) in &manifest.contracts {
		let current = history
			.current()
			.expect("validated migration histories always contain a current version");
		let current_version = history
			.current_version()
			.unwrap_or_else(|| panic!("validated migration histories carry a current version"));
		render_contract(
			&mut output,
			key,
			&history.rust_name,
			&ContractGeometry {
				kind: &history.identity.kind,
				discriminator_bytes: history.identity.discriminator_bytes,
				version_bytes: manifest.version_type.bytes() as u8,
			},
			current,
			current_version,
		);
	}

	output
}

/// Emit the program identity every generated assertion compares against.
///
/// The recorded geometry is deliberately not bound to the program's Rust
/// types. A contract type may be private to the program crate, and an
/// integration test cannot name it, so a type-binding guard would fail to
/// compile for those programs. Drift between the source and this record is
/// already caught earlier and more strictly: the `#[account]`, `#[instruction]`,
/// and `#[event]` macros refuse to expand when a schema differs from its
/// checked-in snapshot, telling the developer to run `pina migrations make`.
///
/// What this file provides is the authoritative, regenerated byte layout that
/// downstream decoders read — the offsets an indexer or a generated client
/// needs — with `pina migrations check` failing when it goes stale.
fn render_program_identity(output: &mut String, manifest: &MigrationManifest) {
	let _ = writeln!(output, "/// Program id recorded in the manifest.");
	let _ = writeln!(
		output,
		"pub const PROGRAM_ID: &str = {:?};\n",
		manifest.program_id
	);
}

/// Render one contract's constants.
/// One contract's recorded geometry, grouped to keep the argument list short.
struct ContractGeometry<'a> {
	kind: &'a ContractKind,
	discriminator_bytes: u8,
	version_bytes: u8,
}

fn render_contract(
	output: &mut String,
	key: &str,
	rust_name: &str,
	geometry: &ContractGeometry<'_>,
	current: &SchemaVersion,
	current_version: u32,
) {
	let kind_label = match geometry.kind {
		ContractKind::Account => "account",
		ContractKind::Instruction => "instruction",
		ContractKind::Event => "event",
	};
	let module = sanitize_identifier(key);
	let envelope = usize::from(geometry.discriminator_bytes) + usize::from(geometry.version_bytes);

	let _ = writeln!(output, "/// ABI layout for the `{rust_name}` {kind_label}.");
	let _ = writeln!(output, "pub mod {module} {{");
	let _ = writeln!(output, "\t/// Manifest contract key.");
	let _ = writeln!(output, "\tpub const KEY: &str = {key:?};");
	let _ = writeln!(output, "\t/// Rust type name as declared in the program.");
	let _ = writeln!(output, "\tpub const RUST_NAME: &str = {rust_name:?};");
	let _ = writeln!(output, "\t/// Current schema version.");
	let _ = writeln!(output, "\tpub const VERSION: u32 = {current_version};");
	let _ = writeln!(output, "\t/// Schema hash recorded for this version.");
	let _ = writeln!(
		output,
		"\tpub const SCHEMA_SHA256: &str = {:?};",
		current.schema_sha256()
	);
	// The envelope geometry is the part consumers get wrong by hand: enabling
	// migrations inserts a version byte after the discriminator, so every byte
	// after the discriminator shifts by one. Recording it explicitly makes the
	// shift a checked constant instead of an implicit addition.
	let _ = writeln!(output, "\t/// Width of the discriminator in bytes.");
	let _ = writeln!(
		output,
		"\tpub const DISCRIMINATOR_BYTES: usize = {};",
		geometry.discriminator_bytes
	);
	let _ = writeln!(output, "\t/// Byte offset of the migration version field.");
	let _ = writeln!(
		output,
		"\tpub const VERSION_OFFSET: usize = {};",
		geometry.discriminator_bytes
	);
	let _ = writeln!(
		output,
		"\t/// Width of the migration version field in bytes."
	);
	let _ = writeln!(
		output,
		"\tpub const VERSION_BYTES: usize = {};",
		geometry.version_bytes
	);
	let _ = writeln!(
		output,
		"\t/// Bytes occupied by the discriminator and version envelope together."
	);
	let _ = writeln!(
		output,
		"\tpub const MIGRATION_HEADER_SIZE: usize = {envelope};"
	);

	let physical = current.schema.physical().unwrap_or_else(|error| {
		panic!("validated manifest schema has a physical layout: {error}")
	});
	match &physical {
		PhysicalLayout::Fixed { size, fields } => {
			let payload = current.schema.fixed_payload_size().unwrap_or(0);
			let _ = writeln!(
				output,
				"\t/// Payload size in bytes, excluding the envelope header."
			);
			let _ = writeln!(output, "\tpub const PAYLOAD_SIZE: usize = {payload};");
			let _ = writeln!(
				output,
				"\t/// Total encoded size in bytes, including the envelope header."
			);
			let _ = writeln!(
				output,
				"\tpub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;"
			);
			let _ = writeln!(
				output,
				"\t/// Manifest payload size; must agree with `PAYLOAD_SIZE`."
			);
			let _ = writeln!(output, "\tpub const MANIFEST_PAYLOAD_SIZE: usize = {size};");
			let _ = writeln!(
				output,
				"\t/// `(name, absolute_offset, size)` in encoded bytes."
			);
			let _ = writeln!(output, "\tpub const FIELDS: &[(&str, usize, usize)] = &[");
			for field in fields {
				let _ = writeln!(
					output,
					"\t\t({:?}, MIGRATION_HEADER_SIZE + {}, {}),",
					field.name, field.offset, field.size
				);
			}
			let _ = writeln!(output, "\t];");
		}
		PhysicalLayout::Compact {
			header_size,
			maximum_size,
			tail_alignment,
			..
		} => {
			let _ = writeln!(output, "\t/// Compact header size in bytes.");
			let _ = writeln!(output, "\tpub const HEADER_SIZE: usize = {header_size};");
			let _ = writeln!(output, "\t/// Maximum encoded size in bytes.");
			let _ = writeln!(output, "\tpub const MAX_SIZE: usize = {maximum_size};");
			let _ = writeln!(output, "\t/// Byte granularity of valid allocations.");
			let _ = writeln!(
				output,
				"\tpub const TAIL_ALIGNMENT: usize = {tail_alignment};"
			);
			let _ = writeln!(
				output,
				"\t/// Smallest valid encoded size, including the envelope header."
			);
			let _ = writeln!(
				output,
				"\tpub const MIN_SIZE: usize = MIGRATION_HEADER_SIZE + HEADER_SIZE;"
			);
		}
	}

	let _ = writeln!(output, "}}\n");
}

/// Turn a manifest contract key into a valid Rust module name.
fn sanitize_identifier(key: &str) -> String {
	let mut identifier = String::with_capacity(key.len());
	for character in key.chars() {
		if character.is_ascii_alphanumeric() {
			identifier.push(character.to_ascii_lowercase());
		} else {
			identifier.push('_');
		}
	}
	if identifier.starts_with(|character: char| character.is_ascii_digit()) {
		identifier.insert(0, '_');
	}
	identifier
}

/// Read a previously generated file, if it exists.
pub fn read_existing(program_dir: &Path) -> std::io::Result<Option<String>> {
	let path = program_dir.join(ABI_LAYOUT_TEST_PATH);
	match std::fs::read_to_string(&path) {
		Ok(contents) => Ok(Some(contents)),
		Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
		Err(error) => Err(error),
	}
}

#[cfg(test)]
mod tests {
	use pina_abi::MigrationVersionType;

	use super::*;

	/// Manifest keys contain separators that are not valid in an identifier.
	#[test]
	fn contract_keys_become_valid_module_names() {
		assert_eq!(sanitize_identifier("account:1:01"), "account_1_01");
		assert_eq!(sanitize_identifier("event-2-04"), "event_2_04");
	}

	/// A key that starts with a digit must not produce a bare numeric module.
	#[test]
	fn a_leading_digit_is_prefixed() {
		let identifier = sanitize_identifier("1account");

		assert!(
			identifier.starts_with('_'),
			"a leading digit needs a prefix: {identifier}"
		);
	}

	/// Missing files read as `None` rather than an error, which is what makes a
	/// first generation and a stale-file check the same code path.
	#[test]
	fn a_missing_layout_file_reads_as_none() {
		let temp = tempfile::tempdir().unwrap_or_else(|error| panic!("temp dir: {error}"));

		let existing =
			read_existing(temp.path()).unwrap_or_else(|error| panic!("read existing: {error}"));

		assert_eq!(existing, None);
	}

	/// A present file is returned verbatim so `check` can compare it.
	#[test]
	fn a_present_layout_file_is_returned() {
		let temp = tempfile::tempdir().unwrap_or_else(|error| panic!("temp dir: {error}"));
		std::fs::create_dir_all(temp.path().join("tests"))
			.unwrap_or_else(|error| panic!("create tests dir: {error}"));
		std::fs::write(temp.path().join(ABI_LAYOUT_TEST_PATH), "// generated\n")
			.unwrap_or_else(|error| panic!("write layout file: {error}"));

		let existing =
			read_existing(temp.path()).unwrap_or_else(|error| panic!("read existing: {error}"));

		assert_eq!(existing.as_deref(), Some("// generated\n"));
	}

	/// A manifest with no contracts still produces a valid, self-describing
	/// file rather than an empty one.
	#[test]
	fn an_empty_manifest_still_renders_a_header() {
		let manifest = MigrationManifest::new(
			"11111111111111111111111111111111".to_owned(),
			MigrationVersionType::U8,
		);

		let rendered = generate(&manifest);

		assert!(rendered.contains("program-id: 11111111111111111111111111111111"));
		assert!(rendered.contains("version-type: u8"));
	}
}

#[cfg(test)]
mod read_error_tests {
	use super::*;

	/// A path that exists but cannot be read as text surfaces the error rather
	/// than being reported as "no file", so `check` never mistakes an
	/// unreadable guard for a missing one.
	#[test]
	fn an_unreadable_path_surfaces_the_error() {
		let temp = tempfile::tempdir().unwrap_or_else(|error| panic!("temp dir: {error}"));
		let path = temp.path().join(ABI_LAYOUT_TEST_PATH);
		// A directory where the file is expected fails `read_to_string` with
		// something other than `NotFound`.
		std::fs::create_dir_all(&path).unwrap_or_else(|error| panic!("create dir: {error}"));

		let error = read_existing(temp.path()).expect_err("an unreadable path must error");

		assert_ne!(error.kind(), std::io::ErrorKind::NotFound);
	}
}
