// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'commands/commands.dart';

CommandRunner<void> buildRunner() {
  return CommandRunner<void>(
      'float-accounts-program-cli',
      "Command-line interface for floatAccountsProgram",
    )
    ..argParser.addOption(
      'url',
      abbr: 'u',
      defaultsTo: 'devnet',
      help:
          'RPC endpoint: mainnet, devnet, testnet, localhost, or an https URL.',
    )
    ..argParser.addOption(
      'keypair',
      abbr: 'k',
      defaultsTo: '~/.config/solana/id.json',
      help: 'Payer keypair JSON file.',
    )
    ..argParser.addOption(
      'program-id',
      help: 'Override the on-chain program address.',
    )
    ..argParser.addFlag(
      'simulate',
      help: 'Simulate the transaction and print logs instead of sending.',
    )
    ..argParser.addFlag(
      'json',
      negatable: false,
      help: 'Print machine-readable JSON output.',
    )
    ..addCommand(CreateCommand())
    ..addCommand(UpdateCommand())
    ..addCommand(FetchCommand());
}
