// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/heap_alloc_program.dart';

final class FillCommand extends Command<void> {
  FillCommand() {
    argParser
      ..addOption('bytes', mandatory: true, help: "bytes")
      ..addOption('fill', mandatory: true, help: "fill");
  }

  @override
  String get name => 'fill';

  @override
  String get description => "Instruction data for `Fill`.";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);

    final bytesValue = integer('--bytes', results['bytes']! as String);
    final fillValue = integer('--fill', results['fill']! as String);
    final instruction = getFillInstruction(
      programAddress: context.programAddress,
      bytes: bytesValue,
      fill: fillValue,
    );
    await context.send([instruction]);
  }
}
