//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use role_registry_program_client::instructions::AddRole;
use role_registry_program_client::instructions::AddRoleInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct AddRoleArgs {
	#[arg(long)]
	role_id: u64,
	#[arg(long)]
	permissions: u64,
	#[arg(long)]
	bump: u8,
	/// The `admin` account [default: payer]
	#[arg(long)]
	admin: Option<String>,
	/// The `grantee` account
	#[arg(long)]
	grantee: String,
	/// The `registry_config` account
	#[arg(long)]
	registry_config: String,
	/// The `role_entry` account
	#[arg(long)]
	role_entry: String,
}

pub(crate) fn run(context: &CliContext, args: AddRoleArgs) -> Result<(), CliError> {
	let admin = match &args.admin {
		Some(value) => CliContext::pubkey("--admin", value)?,
		None => context.payer_pubkey(),
	};
	let grantee = CliContext::pubkey("--grantee", &args.grantee)?;
	let registry_config = CliContext::pubkey("--registry_config", &args.registry_config)?;
	let role_entry = CliContext::pubkey("--role_entry", &args.role_entry)?;
	let data = AddRoleInstructionData::new(|data| {
		data.role_id.set(args.role_id);
		data.permissions.set(args.permissions);
		data.bump = args.bump;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = AddRole {
		admin,
		grantee,
		registry_config,
		role_entry,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
