//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use clap::Subcommand;
use serde_json::Value;
use serde_json::json;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Subcommand)]
pub enum Command {
	/// Global program configuration: the authority that may update it, the
	/// treasury that collects multisig creation fees, and the fee itself.
	ProgramConfig(ProgramConfigArgs),
	/// A multisig: consensus parameters plus the sorted member roster.
	///
	/// Members live in two parallel compact tails (`member_keys` sorted ascending,
	/// `member_permissions` aligned by index) so the account only pays rent for
	/// active members. A member's bit index in a proposal's vote masks is its
	/// position in `member_keys`.
	Multisig(MultisigArgs),
	/// A proposal: vote state and payload in one account.
	///
	/// The payload is stored exactly as the wire format the program re-parses at
	/// execution, validated once at creation, so there is a single encoding of a
	/// vault message or config action stream between creation and execution.
	Proposal(ProposalArgs),
	/// A member-scoped allowance to spend from a vault without a vote.
	SpendingLimit(SpendingLimitArgs),
}

#[derive(Debug, Args)]
pub struct ProgramConfigArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
}

#[derive(Debug, Args)]
pub struct MultisigArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `create_key`.
	#[arg(long)]
	create_key: Option<String>,
}

#[derive(Debug, Args)]
pub struct ProposalArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `multisig`.
	#[arg(long)]
	multisig: Option<String>,
	/// PDA seed `index`.
	#[arg(long)]
	index: Option<u64>,
}

#[derive(Debug, Args)]
pub struct SpendingLimitArgs {
	/// Account address; overrides PDA derivation.
	#[arg(long)]
	address: Option<String>,
	/// PDA seed `multisig`.
	#[arg(long)]
	multisig: Option<String>,
	/// PDA seed `create_key`.
	#[arg(long)]
	create_key: Option<String>,
}

pub(crate) fn run(context: &CliContext, command: Command) -> Result<(), CliError> {
	match command {
		Command::ProgramConfig(args) => fetch_program_config(context, args),
		Command::Multisig(args) => fetch_multisig(context, args),
		Command::Proposal(args) => fetch_proposal(context, args),
		Command::SpendingLimit(args) => fetch_spending_limit(context, args),
	}
}

fn fetch_program_config(context: &CliContext, args: ProgramConfigArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let seeds: &[&[u8]] = &["multisig-program-config".as_bytes()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match multisig_program_client::accounts::ProgramConfig::from_bytes(&data) {
		Ok(account) => program_config_json(account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "program-config", &address, &value);
	Ok(())
}

fn fetch_multisig(context: &CliContext, args: MultisigArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let create_key = match &args.create_key {
				Some(value) => CliContext::pubkey("--create_key", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "multisig".to_string(),
						seed: "--create_key".to_string(),
					});
				}
			};
			let seeds: &[&[u8]] = &["multisig".as_bytes(), create_key.as_ref()];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match multisig_program_client::accounts::Multisig::from_bytes(&data) {
		Ok(account) => multisig_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "multisig", &address, &value);
	Ok(())
}

fn fetch_proposal(context: &CliContext, args: ProposalArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let multisig = match &args.multisig {
				Some(value) => CliContext::pubkey("--multisig", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "proposal".to_string(),
						seed: "--multisig".to_string(),
					});
				}
			};
			let index = args.index.ok_or_else(|| {
				CliError::MissingSeed {
					account: "proposal".to_string(),
					seed: "--index".to_string(),
				}
			})?;
			let index_bytes = index.to_le_bytes();
			let seeds: &[&[u8]] = &[
				"proposal".as_bytes(),
				multisig.as_ref(),
				index_bytes.as_ref(),
			];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match multisig_program_client::accounts::Proposal::from_bytes(&data) {
		Ok(account) => proposal_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "proposal", &address, &value);
	Ok(())
}

fn fetch_spending_limit(context: &CliContext, args: SpendingLimitArgs) -> Result<(), CliError> {
	let address = match &args.address {
		Some(value) => CliContext::pubkey("--address", value)?,
		None => {
			let multisig = match &args.multisig {
				Some(value) => CliContext::pubkey("--multisig", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "spending-limit".to_string(),
						seed: "--multisig".to_string(),
					});
				}
			};
			let create_key = match &args.create_key {
				Some(value) => CliContext::pubkey("--create_key", value)?,
				None => {
					return Err(CliError::MissingSeed {
						account: "spending-limit".to_string(),
						seed: "--create_key".to_string(),
					});
				}
			};
			let seeds: &[&[u8]] = &[
				"spending-limit".as_bytes(),
				multisig.as_ref(),
				create_key.as_ref(),
			];
			Pubkey::find_program_address(seeds, &context.program_address).0
		}
	};
	let data = context.fetch_account(&address)?;
	let value = match multisig_program_client::accounts::SpendingLimit::from_bytes(&data) {
		Ok(account) => spending_limit_json(&account),
		Err(error) => {
			return Err(CliError::AccountDecode {
				address: address.to_string(),
				message: error.to_string(),
			});
		}
	};
	print_value(context.json, "spending-limit", &address, &value);
	Ok(())
}

fn program_config_json(account: &multisig_program_client::accounts::ProgramConfigZc) -> Value {
	json!({
		"bump": account.bump,
		"authority": account.authority.to_string(),
		"treasury": account.treasury.to_string(),
		"creation_fee": account.creation_fee.get(),
	})
}

fn multisig_json(account: &multisig_program_client::accounts::MultisigRef<'_>) -> Value {
	json!({
		"bump": account.bump,
		"create_key": account.create_key.to_string(),
		"config_authority": account.config_authority.to_string(),
		"rent_collector": account.rent_collector.to_string(),
		"threshold": account.threshold.get(),
		"timelock": account.timelock.get(),
		"ttl": account.ttl.get(),
		"transaction_index": account.transaction_index.get(),
		"stale_transaction_index": account.stale_transaction_index.get(),
		"member_roster": account.member_roster().to_vec(),
		"member_permissions": account.member_permissions().to_vec(),
	})
}

fn proposal_json(account: &multisig_program_client::accounts::ProposalRef<'_>) -> Value {
	json!({
		"bump": account.bump,
		"multisig": account.multisig.to_string(),
		"creator": account.creator.to_string(),
		"index": account.index.get(),
		"kind": account.kind,
		"vault_index": account.vault_index,
		"vault_bump": account.vault_bump,
		"status": account.status,
		"status_at": account.status_at.get(),
		"expires_at": account.expires_at.get(),
		"approved_mask": account.approved_mask.get(),
		"rejected_mask": account.rejected_mask.get(),
		"ephemeral_bumps": account.ephemeral_bumps().to_vec(),
		"message": account.message().to_vec(),
		"actions": account.actions().to_vec(),
	})
}

fn spending_limit_json(account: &multisig_program_client::accounts::SpendingLimitRef<'_>) -> Value {
	json!({
		"bump": account.bump,
		"multisig": account.multisig.to_string(),
		"create_key": account.create_key.to_string(),
		"vault_index": account.vault_index,
		"vault_bump": account.vault_bump,
		"mint": account.mint.to_string(),
		"amount": account.amount.get(),
		"remaining_amount": account.remaining_amount.get(),
		"last_reset": account.last_reset.get(),
		"period": account.period,
		"members": account.members().to_vec(),
		"destinations": account.destinations().to_vec(),
	})
}

fn print_value(json_output: bool, name: &str, address: &Pubkey, value: &Value) {
	if json_output {
		println!(
			"{}",
			serde_json::to_string_pretty(value).unwrap_or_default()
		);
		return;
	}

	println!("{name} {address}");
	if let Some(fields) = value.as_object() {
		for (key, value) in fields {
			println!("  {key}: {value}");
		}
	}
}
