//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use compact_accounts_program_client::instructions::Rename;
use compact_accounts_program_client::instructions::RenameInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct RenameArgs {
	#[arg(long)]
	title_len: u8,
	#[arg(long)]
	title: String,
	/// Funds title growth and receives rent refunded by title shrinkage [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `journal` account [default: derived]
	#[arg(long)]
	journal: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: RenameArgs) -> Result<(), CliError> {
	let title = CliContext::bytes::<24>("--title", &args.title)?;
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let journal = match &args.journal {
		Some(value) => CliContext::pubkey("--journal", value)?,
		None => {
			Pubkey::find_program_address(
				&["compact-journal".as_bytes(), authority.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let data = RenameInstructionData::new(|data| {
		data.title_len = args.title_len;
		data.title = title;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Rename {
		authority,
		journal,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
