//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use compact_accounts_program_client::instructions::Resize;
use compact_accounts_program_client::instructions::ResizeInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct ResizeArgs {
	#[arg(long)]
	entry_count: u8,
	#[arg(long)]
	marker_count: u8,
	/// Funds growth and receives the rent refund from shrinking [default: payer]
	#[arg(long)]
	authority: Option<String>,
	/// The `journal` account [default: derived]
	#[arg(long)]
	journal: Option<String>,
}

pub(crate) fn run(context: &CliContext, args: ResizeArgs) -> Result<(), CliError> {
	let authority = match &args.authority {
		Some(value) => CliContext::pubkey("--authority", value)?,
		None => context.payer_pubkey(),
	};
	let journal = match &args.journal {
		Some(value) => CliContext::pubkey("--journal", value)?,
		None => {
			Pubkey::find_program_address(
				&["compact-journal".as_bytes(), authority.as_ref()],
				&context.program_address,
			)
			.0
		}
	};
	let data = ResizeInstructionData::new(|data| {
		data.entry_count = args.entry_count;
		data.marker_count = args.marker_count;
	})
	.map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Resize {
		authority,
		journal,
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
