// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/prop_amm_program.dart';

final class RotateAuthorityCommand extends Command<void> {
  RotateAuthorityCommand() {
    argParser
      ..addOption('new_authority', mandatory: true, help: "newAuthority")
      ..addOption('oracle', mandatory: true, help: "The oracle account")
      ..addOption('authority', mandatory: false, help: "The authority account [default: payer]");
  }

  @override
  String get name => 'rotate_authority';

  @override
  String get description => "rotate_authority";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final oracle = pubkey('--oracle', results['oracle']! as String);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final newAuthorityValue = pubkey('--new-authority', results['new_authority']! as String);
    final instruction = getRotateAuthorityInstruction(
      programAddress: context.programAddress,
      oracle: oracle,
      authority: authority,
      newAuthority: newAuthorityValue,
    );
    await context.send([instruction]);
  }
}
