[package]
name = "deny_heap_allocations_in_onchain_instruction_handlers"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "6.0.4"

[dev-dependencies]
dylint_testing = "6.0.4"

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]
