// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { createPdaCommand } from "./commands/create_pda.ts";
import { forwardRotateWithPdaCommand } from "./commands/forward_rotate_with_pda.ts";
import { forwardRotateWithSignerCommand } from "./commands/forward_rotate_with_signer.ts";
import { helloCommand } from "./commands/hello.ts";
import { registerGlobals } from "./context.ts";
import { fetchCommand } from "./fetch.ts";

const program = registerGlobals(new Command())
	.name("pina-bpf-program-cli")
	.version("0.1.0")
	.description("Command-line interface for pinaBpfProgram");
program.addCommand(helloCommand);
program.addCommand(forwardRotateWithSignerCommand);
program.addCommand(forwardRotateWithPdaCommand);
program.addCommand(createPdaCommand);
program.addCommand(fetchCommand);
program.parseAsync(process.argv);
