// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);

/**
 * Whether an endpoint may be used as-is: any `https://` URL, or plaintext
 * `http://` pointed at exactly `localhost`, `127.0.0.1`, or `[::1]`.
 *
 * The host is read from the URL authority after rejecting userinfo, so
 * lookalikes such as `http://localhost.evil.com` or
 * `http://127.0.0.1@evil.com` do not count as local.
 */
export function endpointIsSecure(endpoint: string): boolean {
	const lowercase = endpoint.toLowerCase();
	if (lowercase.startsWith("https://")) {
		return true;
	}
	const scheme = "http://";
	if (!lowercase.startsWith(scheme)) {
		return false;
	}
	const authority = lowercase.slice(scheme.length).split(/[/?#]/)[0] ?? "";
	if (authority.includes("@")) {
		return false;
	}
	return LOOPBACK_HOSTS.has(authorityHost(authority));
}

function authorityHost(authority: string): string {
	if (authority.startsWith("[")) {
		const end = authority.indexOf("]");
		return end === -1 ? authority : authority.slice(1, end);
	}
	const port = authority.lastIndexOf(":");
	return port === -1 ? authority : authority.slice(0, port);
}
