// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/escrow_program.dart';

final class MakeCommand extends Command<void> {
  MakeCommand() {
    argParser
      ..addOption('seed', mandatory: true, help: "seed")
      ..addOption('amount_a', mandatory: true, help: "amountA")
      ..addOption('amount_b', mandatory: true, help: "amountB")
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption(
        'maker',
        mandatory: false,
        help: "The maker account [default: payer]",
      )
      ..addOption('mint_a', mandatory: true, help: "The mint_a account")
      ..addOption('mint_b', mandatory: true, help: "The mint_b account")
      ..addOption(
        'maker_ata_a',
        mandatory: true,
        help: "The maker_ata_a account",
      )
      ..addOption('escrow', mandatory: true, help: "The escrow account")
      ..addOption('vault', mandatory: true, help: "The vault account")
      ..addOption(
        'token_program',
        mandatory: true,
        help: "The token_program account",
      );
  }

  @override
  String get name => 'make';

  @override
  String get description => "make";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final maker = (results['maker'] as String?) != null
        ? pubkey('--maker', results['maker']! as String)
        : context.payerAddress;
    final mintA = pubkey('--mint-a', results['mint_a']! as String);
    final mintB = pubkey('--mint-b', results['mint_b']! as String);
    final makerAtaA = pubkey(
      '--maker-ata-a',
      results['maker_ata_a']! as String,
    );
    final escrow = pubkey('--escrow', results['escrow']! as String);
    final vault = pubkey('--vault', results['vault']! as String);
    final tokenProgram = pubkey(
      '--token-program',
      results['token_program']! as String,
    );
    final seedValue = bigInteger('--seed', results['seed']! as String);
    final amountAValue = bigInteger(
      '--amount-a',
      results['amount_a']! as String,
    );
    final amountBValue = bigInteger(
      '--amount-b',
      results['amount_b']! as String,
    );
    final bumpValue = integer('--bump', results['bump']! as String);
    final instruction = getMakeInstruction(
      programAddress: context.programAddress,
      maker: maker,
      mintA: mintA,
      mintB: mintB,
      makerAtaA: makerAtaA,
      escrow: escrow,
      vault: vault,
      associatedTokenProgram: Address(
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
      ),
      systemProgram: Address('11111111111111111111111111111111'),
      tokenProgram: tokenProgram,
      seed: seedValue,
      amountA: amountAValue,
      amountB: amountBValue,
      bump: bumpValue,
    );
    await context.send([instruction]);
  }
}
