// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getRotateAdminInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const rotateAdminCommand = registerGlobals(new Command("rotate_admin"))
	.description("rotateAdmin")
	.option("--admin <admin>", "The `admin` account [default: payer]")
	.requiredOption("--new-admin <newAdmin>", "The `new_admin` account")
	.requiredOption(
		"--registry-config <registryConfig>",
		"The `registry_config` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			admin: context.payer,
			newAdmin: pubkey("--new-admin", options.newAdmin),
			registryConfig: pubkey("--registry-config", options.registryConfig),
		};
		const instruction = getRotateAdminInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
