// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/duplicate_mutable_accounts_program.dart';

final class AllowsDuplicateReadonlyCommand extends Command<void> {
  AllowsDuplicateReadonlyCommand() {
    argParser
      ..addOption('account1', mandatory: true, help: "The account1 account")
      ..addOption('account2', mandatory: true, help: "The account2 account");
  }

  @override
  String get name => 'allows_duplicate_readonly';

  @override
  String get description => "allows_duplicate_readonly";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final account1 = pubkey('--account1', results['account1']! as String);
    final account2 = pubkey('--account2', results['account2']! as String);

    final instruction = getAllowsDuplicateReadonlyInstruction(
      programAddress: context.programAddress,
      account1: account1,
      account2: account2,
    );
    await context.send([instruction]);
  }
}
