// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getConfigInitializeInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const configInitializeCommand = registerGlobals(
	new Command("config_initialize"),
)
	.description("configInitialize")
	.requiredOption("--bump <bump>", "bump")
	.requiredOption("--treasury <treasury>", "treasury")
	.requiredOption("--creation-fee <creationFee>", "creationFee")
	.option(
		"--program-config <programConfig>",
		"The `program_config` account [default: derived]",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			treasury: pubkey("--treasury", options.treasury),
			creationFee: bigInteger("--creation-fee", options.creationFee),
			authority: context.payer,
			programConfig: options.programConfig === undefined
				? undefined
				: pubkey("--program-config", options.programConfig),
		};
		const instruction = await getConfigInitializeInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
