// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getConfigUpdateInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const configUpdateCommand = registerGlobals(new Command("config_update"))
	.description("configUpdate")
	.requiredOption("--set-treasury <setTreasury>", "setTreasury")
	.requiredOption("--treasury <treasury>", "treasury")
	.requiredOption("--set-creation-fee <setCreationFee>", "setCreationFee")
	.requiredOption("--creation-fee <creationFee>", "creationFee")
	.option("--authority <authority>", "The `authority` account [default: payer]")
	.option(
		"--program-config <programConfig>",
		"The `program_config` account [default: derived]",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			setTreasury: options.setTreasury,
			treasury: pubkey("--treasury", options.treasury),
			setCreationFee: options.setCreationFee,
			creationFee: bigInteger("--creation-fee", options.creationFee),
			authority: context.payer,
			programConfig: options.programConfig === undefined
				? undefined
				: pubkey("--program-config", options.programConfig),
		};
		const instruction = await getConfigUpdateInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
