// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getMultisigCreateInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const multisigCreateCommand = registerGlobals(
	new Command("multisig_create"),
)
	.description("multisigCreate")
	.requiredOption("--bump <bump>", "bump")
	.requiredOption("--threshold <threshold>", "threshold")
	.requiredOption("--timelock <timelock>", "timelock")
	.requiredOption("--ttl <ttl>", "ttl")
	.requiredOption(
		"--member-permissions <memberPermissions>",
		"memberPermissions",
	)
	.requiredOption("--config-authority <configAuthority>", "configAuthority")
	.requiredOption("--rent-collector <rentCollector>", "rentCollector")
	.requiredOption(
		"--program-config <programConfig>",
		"The `program_config` account",
	)
	.option(
		"--create-key <createKey>",
		"The `create_key` account [default: payer]",
	)
	.option("--multisig <multisig>", "The `multisig` account [default: derived]")
	.option(
		"--rent-payer <rentPayer>",
		"The `rent_payer` account [default: payer]",
	)
	.requiredOption(
		"--treasury <treasury>",
		"Treasury that collects the creation fee; pass the program's own",
	)
	.requiredOption(
		"--member-accounts <memberAccounts>",
		"The founding members, sorted by address; `member_permissions` indexes",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			threshold: smallInteger("--threshold", options.threshold),
			timelock: smallInteger("--timelock", options.timelock),
			ttl: smallInteger("--ttl", options.ttl),
			memberPermissions: base58(
				"--member-permissions",
				options.memberPermissions,
			),
			configAuthority: pubkey("--config-authority", options.configAuthority),
			rentCollector: pubkey("--rent-collector", options.rentCollector),
			programConfig: pubkey("--program-config", options.programConfig),
			createKey: context.payer,
			multisig: options.multisig === undefined
				? undefined
				: pubkey("--multisig", options.multisig),
			rentPayer: context.payer,
			treasury: pubkey("--treasury", options.treasury),
			memberAccounts: pubkey("--member-accounts", options.memberAccounts),
		};
		const instruction = await getMultisigCreateInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
