// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getProposalCloseInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const proposalCloseCommand = registerGlobals(
	new Command("proposal_close"),
)
	.description("proposalClose")
	.requiredOption("--multisig <multisig>", "The `multisig` account")
	.requiredOption("--proposal <proposal>", "The `proposal` account")
	.requiredOption(
		"--rent-collector <rentCollector>",
		"The `rent_collector` account",
	)
	.requiredOption(
		"--clock <clock>",
		"Clock for the expiry test: an expired active proposal can neither",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			multisig: pubkey("--multisig", options.multisig),
			proposal: pubkey("--proposal", options.proposal),
			rentCollector: pubkey("--rent-collector", options.rentCollector),
			clock: pubkey("--clock", options.clock),
		};
		const instruction = getProposalCloseInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
