// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getProposalCreateInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const proposalCreateCommand = registerGlobals(
	new Command("proposal_create"),
)
	.description("proposalCreate")
	.requiredOption("--bump <bump>", "bump")
	.requiredOption("--kind <kind>", "kind")
	.requiredOption("--vault-index <vaultIndex>", "vaultIndex")
	.requiredOption("--vault-bump <vaultBump>", "vaultBump")
	.requiredOption("--ephemeral-signers <ephemeralSigners>", "ephemeralSigners")
	.requiredOption("--ephemeral-bumps <ephemeralBumps>", "ephemeralBumps")
	.requiredOption("--message-len <messageLen>", "messageLen")
	.requiredOption("--message <message>", "message")
	.requiredOption("--actions-len <actionsLen>", "actionsLen")
	.requiredOption("--actions <actions>", "actions")
	.requiredOption("--multisig <multisig>", "The `multisig` account")
	.requiredOption("--proposal <proposal>", "The `proposal` account")
	.requiredOption("--clock <clock>", "The `clock` account")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			kind: smallInteger("--kind", options.kind),
			vaultIndex: smallInteger("--vault-index", options.vaultIndex),
			vaultBump: smallInteger("--vault-bump", options.vaultBump),
			ephemeralSigners: smallInteger(
				"--ephemeral-signers",
				options.ephemeralSigners,
			),
			ephemeralBumps: base58("--ephemeral-bumps", options.ephemeralBumps),
			messageLen: smallInteger("--message-len", options.messageLen),
			message: base58("--message", options.message),
			actionsLen: smallInteger("--actions-len", options.actionsLen),
			actions: base58("--actions", options.actions),
			multisig: pubkey("--multisig", options.multisig),
			proposal: pubkey("--proposal", options.proposal),
			creator: context.payer,
			rentPayer: context.payer,
			clock: pubkey("--clock", options.clock),
		};
		const instruction = getProposalCreateInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
