// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getSpendingLimitUseInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const spendingLimitUseCommand = registerGlobals(
	new Command("spending_limit_use"),
)
	.description("spendingLimitUse")
	.requiredOption("--amount <amount>", "amount")
	.requiredOption("--decimals <decimals>", "decimals")
	.requiredOption("--multisig <multisig>", "The `multisig` account")
	.requiredOption(
		"--spending-limit <spendingLimit>",
		"The `spending_limit` account",
	)
	.requiredOption(
		"--vault <vault>",
		"The vault PDA: SOL source or SPL transfer authority",
	)
	.requiredOption(
		"--destination <destination>",
		"SOL destination, or the destination token account for SPL",
	)
	.requiredOption("--clock <clock>", "The `clock` account")
	.requiredOption(
		"--vault-token-account <vaultTokenAccount>",
		"SPL source token account; absent for SOL",
	)
	.requiredOption("--mint <mint>", "SPL mint; absent for SOL")
	.requiredOption(
		"--token-program <tokenProgram>",
		"SPL token program; absent for SOL",
	)
	.requiredOption(
		"--system-program <systemProgram>",
		"System program; absent for SPL",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			amount: bigInteger("--amount", options.amount),
			decimals: smallInteger("--decimals", options.decimals),
			multisig: pubkey("--multisig", options.multisig),
			spendingLimit: pubkey("--spending-limit", options.spendingLimit),
			member: context.payer,
			vault: pubkey("--vault", options.vault),
			destination: pubkey("--destination", options.destination),
			clock: pubkey("--clock", options.clock),
			vaultTokenAccount: pubkey(
				"--vault-token-account",
				options.vaultTokenAccount,
			),
			mint: pubkey("--mint", options.mint),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
			systemProgram: pubkey("--system-program", options.systemProgram),
		};
		const instruction = getSpendingLimitUseInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
