// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getVaultExecuteInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const vaultExecuteCommand = registerGlobals(new Command("vault_execute"))
	.description("vaultExecute")
	.requiredOption("--multisig <multisig>", "The `multisig` account")
	.requiredOption("--proposal <proposal>", "The `proposal` account")
	.requiredOption("--clock <clock>", "The `clock` account")
	.requiredOption(
		"--message-accounts <messageAccounts>",
		"The message's account keys, in message order. Accounts the message",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			multisig: pubkey("--multisig", options.multisig),
			proposal: pubkey("--proposal", options.proposal),
			member: context.payer,
			clock: pubkey("--clock", options.clock),
			messageAccounts: pubkey("--message-accounts", options.messageAccounts),
		};
		const instruction = getVaultExecuteInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
