// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/custom_errors_program.dart';

final class RequireGtCommand extends Command<void> {
  RequireGtCommand() {
    argParser
;
  }

  @override
  String get name => 'require_gt';

  @override
  String get description => "require_gt";

  @override
  Future<void> run() async {

    final context = await createContext(globalResults!);


    final instruction = getRequireGtInstruction(
      programAddress: context.programAddress,
    );
    await context.send([instruction]);
  }
}
