// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getFailsDuplicateMutableInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const failsDuplicateMutableCommand = registerGlobals(
	new Command("fails_duplicate_mutable"),
)
	.description("failsDuplicateMutable")
	.requiredOption("--account1 <account1>", "The `account1` account")
	.requiredOption("--account2 <account2>", "The `account2` account")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			account1: pubkey("--account1", options.account1),
			account2: pubkey("--account2", options.account2),
		};
		const instruction = getFailsDuplicateMutableInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
