//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations make`. Do not edit.
//!
//! Run `pina migrations make` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: d7534c00da61a8109928b2099d19d4aab04bda0358051830479fd63834ffa32f
// program-id: GKYaKKaAJvuzkH2GKkaEFAqESh9NEobZ3V2Ub7qbpVYn
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "GKYaKKaAJvuzkH2GKkaEFAqESh9NEobZ3V2Ub7qbpVYn";

/// ABI layout for the `PolicyState` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "PolicyState";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "af0c41a0121d7cbce909cd26987a1092c956456f12c9de17edb54ab56cd87e2e";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 18;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 18;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
		("minimum", MIGRATION_HEADER_SIZE + 1, 8),
		("maximum", MIGRATION_HEADER_SIZE + 9, 8),
		("required_approvals", MIGRATION_HEADER_SIZE + 17, 1),
	];
}

/// ABI layout for the `PolicyChecked` event.
pub mod event_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "PolicyChecked";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4dcb3bd09cf7c284a408e80a32634fb7984edf85d99ec5a40b8da7ba48bee387";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 80;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 80;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amount", MIGRATION_HEADER_SIZE + 0, 8),
		("memo", MIGRATION_HEADER_SIZE + 8, 65),
		("approvals", MIGRATION_HEADER_SIZE + 73, 6),
		("required_approvals", MIGRATION_HEADER_SIZE + 79, 1),
	];
}

/// ABI layout for the `InitializePolicyInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "InitializePolicyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "af0c41a0121d7cbce909cd26987a1092c956456f12c9de17edb54ab56cd87e2e";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 18;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 18;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("bump", MIGRATION_HEADER_SIZE + 0, 1),
		("minimum", MIGRATION_HEADER_SIZE + 1, 8),
		("maximum", MIGRATION_HEADER_SIZE + 9, 8),
		("required_approvals", MIGRATION_HEADER_SIZE + 17, 1),
	];
}

/// ABI layout for the `CheckPolicyInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CheckPolicyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "3015ea557bc12463709ea8d70bcb6834f6d6c8606de58af4394972fc10132fab";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 79;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 79;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amount", MIGRATION_HEADER_SIZE + 0, 8),
		("memo", MIGRATION_HEADER_SIZE + 8, 65),
		("approvals", MIGRATION_HEADER_SIZE + 73, 6),
	];
}

