// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getSetRewardIndexInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const setRewardIndexCommand = registerGlobals(
	new Command("set_reward_index"),
)
	.description("setRewardIndex")
	.requiredOption("--new-index <newIndex>", "newIndex")
	.option("--admin <admin>", "The `admin` account [default: payer]")
	.requiredOption("--pool-state <poolState>", "The `pool_state` account")
	.requiredOption(
		"--reward-mint <rewardMint>",
		"The pool's reward mint, for validating the vault binding",
	)
	.requiredOption(
		"--token-program <tokenProgram>",
		"The token program that owns the reward mint and vault",
	)
	.requiredOption(
		"--reward-vault <rewardVault>",
		"The pool's canonical reward vault. An index update is a promise to pay:",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			newIndex: bigInteger("--new-index", options.newIndex),
			admin: context.payer,
			poolState: pubkey("--pool-state", options.poolState),
			rewardMint: pubkey("--reward-mint", options.rewardMint),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
			rewardVault: pubkey("--reward-vault", options.rewardVault),
		};
		const instruction = getSetRewardIndexInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
