// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getWithdrawInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const withdrawCommand = registerGlobals(new Command("withdraw"))
	.description("withdraw")
	.requiredOption("--amount <amount>", "amount")
	.option("--user <user>", "The `user` account [default: payer]")
	.requiredOption("--stake-mint <stakeMint>", "The `stake_mint` account")
	.requiredOption("--pool-state <poolState>", "The `pool_state` account")
	.requiredOption(
		"--position-state <positionState>",
		"The `position_state` account",
	)
	.requiredOption(
		"--user-stake-ata <userStakeAta>",
		"The `user_stake_ata` account",
	)
	.requiredOption(
		"--token-program <tokenProgram>",
		"The `token_program` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			amount: bigInteger("--amount", options.amount),
			user: context.payer,
			stakeMint: pubkey("--stake-mint", options.stakeMint),
			poolState: pubkey("--pool-state", options.poolState),
			positionState: pubkey("--position-state", options.positionState),
			userStakeAta: pubkey("--user-stake-ata", options.userStakeAta),
			tokenProgram: pubkey("--token-program", options.tokenProgram),
		};
		const instruction = getWithdrawInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
