// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import '../context.dart';
import 'package:pina_codama_clients/role_registry_program.dart';

final class UpdateRoleCommand extends Command<void> {
  UpdateRoleCommand() {
    argParser
      ..addOption('permissions', mandatory: true, help: "permissions")
      ..addOption(
        'admin',
        mandatory: false,
        help: "The admin account [default: payer]",
      )
      ..addOption(
        'registry_config',
        mandatory: true,
        help: "The registry_config account",
      )
      ..addOption(
        'role_entry',
        mandatory: true,
        help: "The role_entry account",
      );
  }

  @override
  String get name => 'update_role';

  @override
  String get description => "update_role";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final admin = (results['admin'] as String?) != null
        ? pubkey('--admin', results['admin']! as String)
        : context.payerAddress;
    final registryConfig = pubkey(
      '--registry-config',
      results['registry_config']! as String,
    );
    final roleEntry = pubkey('--role-entry', results['role_entry']! as String);
    final permissionsValue = bigInteger(
      '--permissions',
      results['permissions']! as String,
    );
    final instruction = getUpdateRoleInstruction(
      programAddress: context.programAddress,
      admin: admin,
      registryConfig: registryConfig,
      roleEntry: roleEntry,
      permissions: permissionsValue,
    );
    await context.send([instruction]);
  }
}
