//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

use clap::Args;
use escrow_program_client::instructions::Take;
use escrow_program_client::instructions::TakeInstructionData;
use solana_sdk::pubkey::Pubkey;

use crate::context::CliContext;
use crate::context::CliError;

#[derive(Debug, Args)]
pub struct TakeArgs {
	/// The `taker` account [default: payer]
	#[arg(long)]
	taker: Option<String>,
	/// The `mint_a` account
	#[arg(long)]
	mint_a: String,
	/// The `mint_b` account
	#[arg(long)]
	mint_b: String,
	/// The `taker_ata_a` account
	#[arg(long)]
	taker_ata_a: String,
	/// The `taker_ata_b` account
	#[arg(long)]
	taker_ata_b: String,
	/// The `maker` account
	#[arg(long)]
	maker: String,
	/// The `maker_ata_b` account
	#[arg(long)]
	maker_ata_b: String,
	/// The `escrow` account
	#[arg(long)]
	escrow: String,
	/// The `vault` account
	#[arg(long)]
	vault: String,
	/// The `token_program` account
	#[arg(long)]
	token_program: String,
}

pub(crate) fn run(context: &CliContext, args: TakeArgs) -> Result<(), CliError> {
	let taker = match &args.taker {
		Some(value) => CliContext::pubkey("--taker", value)?,
		None => context.payer_pubkey(),
	};
	let mint_a = CliContext::pubkey("--mint_a", &args.mint_a)?;
	let mint_b = CliContext::pubkey("--mint_b", &args.mint_b)?;
	let taker_ata_a = CliContext::pubkey("--taker_ata_a", &args.taker_ata_a)?;
	let taker_ata_b = CliContext::pubkey("--taker_ata_b", &args.taker_ata_b)?;
	let maker = CliContext::pubkey("--maker", &args.maker)?;
	let maker_ata_b = CliContext::pubkey("--maker_ata_b", &args.maker_ata_b)?;
	let escrow = CliContext::pubkey("--escrow", &args.escrow)?;
	let vault = CliContext::pubkey("--vault", &args.vault)?;
	let token_program = CliContext::pubkey("--token_program", &args.token_program)?;
	let data = TakeInstructionData::new(|_data| {}).map_err(|_| {
		CliError::InvalidData {
			message: "instruction data rejected the provided arguments".to_string(),
		}
	})?;

	let accounts = Take {
		taker,
		mint_a,
		mint_b,
		taker_ata_a,
		taker_ata_b,
		maker,
		maker_ata_b,
		escrow,
		vault,
		token_program,
		associated_token_program: Pubkey::from_str_const(
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
		),
		system_program: Pubkey::from_str_const("11111111111111111111111111111111"),
	};

	context.send(accounts.instruction(data))
}
