// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { addTagCommand } from "./commands/add_tag.ts";
import { initializeCommand } from "./commands/initialize.ts";
import { removeTagCommand } from "./commands/remove_tag.ts";
import { updateProfileCommand } from "./commands/update_profile.ts";
import { registerGlobals } from "./context.ts";
import { fetchCommand } from "./fetch.ts";

const program = registerGlobals(new Command())
	.name("profile-program-cli")
	.version("0.1.0")
	.description("Command-line interface for profileProgram");
program.addCommand(initializeCommand);
program.addCommand(updateProfileCommand);
program.addCommand(addTagCommand);
program.addCommand(removeTagCommand);
program.addCommand(fetchCommand);
program.parseAsync(process.argv);
