// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { initializeCommand } from "./commands/initialize.ts";
import { testEventCommand } from "./commands/test_event.ts";
import { testEventCpiCommand } from "./commands/test_event_cpi.ts";

import { registerGlobals } from "./context.ts";

const program = registerGlobals(new Command())
	.name("events-program-cli")
	.version("0.1.0")
	.description("Command-line interface for eventsProgram");
program.addCommand(initializeCommand);
program.addCommand(testEventCommand);
program.addCommand(testEventCpiCommand);
program.parseAsync(process.argv);
