// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/migrations_program.dart';

final class RelayCommand extends Command<void> {
  RelayCommand() {
    argParser
      ..addOption('value', mandatory: true, help: "value")
      ..addOption(
        'authority',
        mandatory: false,
        help: "The authority account [default: payer]",
      )
      ..addOption('referrer', mandatory: true, help: "The referrer account")
      ..addOption('state', mandatory: true, help: "The state account")
      ..addOption(
        'migration_payer',
        mandatory: false,
        help: "The migration_payer account [default: payer]",
      )
      ..addOption(
        'migration_program',
        mandatory: true,
        help: "The migration_program account",
      );
  }

  @override
  String get name => 'relay';

  @override
  String get description => "relay";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final referrer = pubkey('--referrer', results['referrer']! as String);
    final state = pubkey('--state', results['state']! as String);
    final migrationPayer = (results['migration_payer'] as String?) != null
        ? pubkey('--migration-payer', results['migration_payer']! as String)
        : context.payerAddress;
    final migrationProgram = pubkey(
      '--migration-program',
      results['migration_program']! as String,
    );
    final valueValue = bigInteger('--value', results['value']! as String);
    final instruction = getRelayInstruction(
      programAddress: context.programAddress,
      authority: authority,
      referrer: referrer,
      state: state,
      migrationPayer: migrationPayer,
      systemProgram: Address('11111111111111111111111111111111'),
      migrationProgram: migrationProgram,
      value: valueValue,
    );
    await context.send([instruction]);
  }
}
