// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:test/test.dart';
import 'package:pina_cli_apps/src/endpoint_guard.dart';

void main() {
  group('endpointIsSecure', () {
    test('accepts https and exact loopback hosts', () {
      for (final endpoint in [
        'https://rpc.example.com',
        'http://localhost',
        'http://localhost:8899',
        'http://127.0.0.1',
        'http://127.0.0.1:8899',
        'http://[::1]:8899',
      ]) {
        expect(endpointIsSecure(endpoint), isTrue, reason: endpoint);
      }
    });

    test('rejects remote lookalikes and other plaintext', () {
      for (final endpoint in [
        'http://localhost.evil.com',
        'http://127.0.0.1.evil.com',
        'http://127.0.0.1@evil.com',
        'http://user:password@localhost',
        'http://evil.com',
        'http://example.com/localhost',
        'http://192.168.0.10',
        'ftp://localhost',
      ]) {
        expect(endpointIsSecure(endpoint), isFalse, reason: endpoint);
      }
    });
  });
}
