// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getAllocateInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const allocateCommand = registerGlobals(new Command("allocate"))
	.description("Instruction data for `Allocate`.")
	.requiredOption("--value <value>", "value")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			value: bigInteger("--value", options.value),
		};
		const instruction = getAllocateInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
