// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getFillInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const fillCommand = registerGlobals(new Command("fill"))
	.description("Instruction data for `Fill`.")
	.requiredOption("--bytes <bytes>", "bytes")
	.requiredOption("--fill <fill>", "fill")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bytes: smallInteger("--bytes", options.bytes),
			fill: smallInteger("--fill", options.fill),
		};
		const instruction = getFillInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
