//! Compute unit budget modules for the generated JavaScript and Dart clients.
//!
//! Neither upstream renderer knows the `pinaComputeUnits` plugin, so this
//! module adds the read side around their output: one constant pair per
//! measured instruction and a program-level helper that turns the instructions
//! of a transaction into the limit to request. The numbers are copied from the
//! IDL, where `pina_cli` computed them; nothing here adds a margin.
//!
//! Programs without a measured instruction get no module, so their clients are
//! exactly what the renderers produced.

use std::fmt::Write as _;
use std::path::Path;

use codama_nodes::DiscriminatorNode;
use codama_nodes::Endianness;
use codama_nodes::InstructionNode;
use codama_nodes::Number;
use codama_nodes::NumberFormat;
use codama_nodes::ProgramNode;
use codama_nodes::RootNode;
use codama_nodes::TypeNode;
use codama_nodes::ValueNode;
use pina_codama_renderer::compute_units::ComputeUnitBudget;

use crate::client_migrations::pascal_case;
use crate::client_migrations::shouting_snake;
use crate::compute_units::MAX_COMPUTE_UNIT_LIMIT;
use crate::error::CodamaError;

/// One measured instruction, as the client modules need it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct InstructionBudget {
	/// IDL instruction name, e.g. `makeOffer`.
	name: String,
	/// The bytes that open every encoding of the instruction.
	discriminator: Vec<u8>,
	budget: ComputeUnitBudget,
}

/// Collect the recorded budget of every measured instruction in `program`.
///
/// # Errors
///
/// Returns a message when a plugin is malformed or a measured instruction has
/// no constant discriminator to recognize it by.
pub(crate) fn instruction_budgets(program: &ProgramNode) -> Result<Vec<InstructionBudget>, String> {
	let mut budgets = Vec::new();

	for instruction in &program.instructions {
		let Some(budget) =
			ComputeUnitBudget::from_instruction(instruction).map_err(|error| error.to_string())?
		else {
			continue;
		};
		let discriminator = leading_discriminator(instruction).ok_or_else(|| {
			format!(
				"instruction `{}` records compute units but has no little-endian constant \
				 discriminator at offset 0 to recognize it by",
				instruction.name.as_ref()
			)
		})?;

		budgets.push(InstructionBudget {
			name: instruction.name.as_ref().to_owned(),
			discriminator,
			budget,
		});
	}

	Ok(budgets)
}

/// The constant discriminator that opens the instruction's data.
fn leading_discriminator(instruction: &InstructionNode) -> Option<Vec<u8>> {
	instruction.discriminators.iter().find_map(|discriminator| {
		let DiscriminatorNode::Constant(constant) = discriminator else {
			return None;
		};
		let (TypeNode::Number(number_type), ValueNode::Number(value)) = (
			constant.constant.r#type.as_ref(),
			constant.constant.value.as_ref(),
		) else {
			return None;
		};
		let width = match number_type.format {
			NumberFormat::U8 => 1,
			NumberFormat::U16 => 2,
			NumberFormat::U32 => 4,
			NumberFormat::U64 => 8,
			_ => return None,
		};
		let Number::UnsignedInteger(value) = value.number else {
			return None;
		};

		(constant.offset == 0 && number_type.endian == Endianness::Le)
			.then(|| value.to_le_bytes()[..width].to_vec())
	})
}

fn byte_list(bytes: &[u8]) -> String {
	bytes
		.iter()
		.map(u8::to_string)
		.collect::<Vec<_>>()
		.join(", ")
}

/// The TypeScript module for one program, or `None` when nothing is measured.
fn js_module(program: &str, budgets: &[InstructionBudget]) -> Option<String> {
	if budgets.is_empty() {
		return None;
	}

	let program_pascal = pascal_case(program);
	let program_address = format!("{}_PROGRAM_ADDRESS", shouting_snake(program));
	let mut source = format!(
		r#"/**
 * This code was AUTOGENERATED by `pina generate` from the program's recorded
 * compute unit measurements. Please DO NOT EDIT THIS FILE; record again with
 * `pina test --record-compute-units` and regenerate.
 */

import {{
	type Address,
	containsBytes,
	type Instruction,
	type ReadonlyUint8Array,
}} from "@solana/kit";
import {{ {program_address} }} from "./programs";
"#
	);

	for entry in budgets {
		let constant = shouting_snake(&entry.name);
		let _ = write!(
			source,
			r"
/**
 * Compute units `{name}` consumed in its most expensive recorded Surfpool
 * simulation.
 */
export const {constant}_MEASURED_COMPUTE_UNITS = {measured};

/**
 * Compute unit limit to request for a transaction carrying `{name}`: the
 * measurement plus the project's margin and the cost of the compute budget
 * instructions.
 */
export const {constant}_COMPUTE_UNIT_LIMIT = {limit};
",
			name = entry.name,
			measured = entry.budget.measured,
			limit = entry.budget.limit,
		);
	}

	let limits = budgets
		.iter()
		.map(|entry| {
			format!(
				"\t[new Uint8Array([{}]), {}_COMPUTE_UNIT_LIMIT],",
				byte_list(&entry.discriminator),
				shouting_snake(&entry.name)
			)
		})
		.collect::<Vec<_>>()
		.join("\n");
	let _ = write!(
		source,
		r#"
/** The most compute units a transaction may request. */
const MAX_COMPUTE_UNIT_LIMIT = {MAX_COMPUTE_UNIT_LIMIT};

/** Each measured instruction's discriminator and its recorded limit. */
const COMPUTE_UNIT_LIMITS: ReadonlyArray<readonly [ReadonlyUint8Array, number]> = [
{limits}
];

/**
 * The compute unit limit to request for a transaction carrying `instructions`.
 *
 * Sums the recorded limit of every instruction addressed to this program.
 * The sum is conservative: each limit carries its own margin and the compute
 * budget instructions' cost, which a transaction pays only once. Instructions
 * for other programs are not counted, so add their budgets yourself.
 *
 * Returns `undefined` when no instruction is addressed to this program or
 * when one of them has no recorded measurement. Request no limit then, so the
 * runtime default applies.
 *
 * @example
 * ```ts
 * const limit = get{program_pascal}ComputeUnitLimit(instructions);
 * const message = setTransactionMessageComputeUnitLimit(limit, base);
 * ```
 */
export function get{program_pascal}ComputeUnitLimit(
	instructions: ReadonlyArray<Pick<Instruction, "data" | "programAddress">>,
	config: {{ programAddress?: Address }} = {{}},
): number | undefined {{
	const programAddress = config.programAddress ?? {program_address};
	let total = 0;
	let counted = false;

	for (const instruction of instructions) {{
		if (instruction.programAddress !== programAddress) {{
			continue;
		}}

		const data = instruction.data;
		const limit = data === undefined
			? undefined
			: COMPUTE_UNIT_LIMITS.find(([discriminator]) =>
				containsBytes(data, discriminator, 0)
			)?.[1];

		if (limit === undefined) {{
			return undefined;
		}}

		total += limit;
		counted = true;
	}}

	return counted ? Math.min(total, MAX_COMPUTE_UNIT_LIMIT) : undefined;
}}
"#
	);

	Some(source)
}

/// The Dart library for one program, or `None` when nothing is measured.
fn dart_module(program: &str, budgets: &[InstructionBudget]) -> Option<String> {
	if budgets.is_empty() {
		return None;
	}

	let program_pascal = pascal_case(program);
	let mut source =
		r"// Auto-generated by `pina generate` from the program's recorded compute unit
// measurements. Do not edit; record again with `pina test --record-compute-units`
// and regenerate.

import 'dart:typed_data';

import 'package:solana_kit_addresses/solana_kit_addresses.dart';
import 'package:solana_kit_instructions/solana_kit_instructions.dart';

import 'programs/programs.dart';
"
		.to_owned();

	for entry in budgets {
		let _ = write!(
			source,
			r"
/// Compute units `{name}` consumed in its most expensive recorded Surfpool
/// simulation.
const int {name}MeasuredComputeUnits = {measured};

/// Compute unit limit to request for a transaction carrying `{name}`: the
/// measurement plus the project's margin and the cost of the compute budget
/// instructions.
const int {name}ComputeUnitLimit = {limit};
",
			name = entry.name,
			measured = entry.budget.measured,
			limit = entry.budget.limit,
		);
	}

	let limits = budgets
		.iter()
		.map(|entry| {
			format!(
				"  ([{}], {}ComputeUnitLimit),",
				byte_list(&entry.discriminator),
				entry.name
			)
		})
		.collect::<Vec<_>>()
		.join("\n");
	let _ = write!(
		source,
		r"
/// The most compute units a transaction may request.
const int _maxComputeUnitLimit = {MAX_COMPUTE_UNIT_LIMIT};

/// Each measured instruction's discriminator and its recorded limit.
const List<(List<int>, int)> _computeUnitLimits = [
{limits}
];

/// The compute unit limit to request for a transaction carrying
/// [instructions].
///
/// Sums the recorded limit of every instruction addressed to this program.
/// The sum is conservative: each limit carries its own margin and the compute
/// budget instructions' cost, which a transaction pays only once. Instructions
/// for other programs are not counted, so add their budgets yourself.
///
/// Returns `null` when no instruction is addressed to this program or when one
/// of them has no recorded measurement. Request no limit then, so the runtime
/// default applies.
int? get{program_pascal}ComputeUnitLimit(
  Iterable<Instruction> instructions, {{
  Address programAddress = {program}ProgramAddress,
}}) {{
  var total = 0;
  var counted = false;

  for (final instruction in instructions) {{
    if (instruction.programAddress != programAddress) {{
      continue;
    }}

    final limit = _recordedLimit(instruction.data);
    if (limit == null) {{
      return null;
    }}

    total += limit;
    counted = true;
  }}

  if (!counted) {{
    return null;
  }}

  return total < _maxComputeUnitLimit ? total : _maxComputeUnitLimit;
}}

int? _recordedLimit(Uint8List? data) {{
  if (data == null) {{
    return null;
  }}

  for (final (discriminator, limit) in _computeUnitLimits) {{
    if (_startsWith(data, discriminator)) {{
      return limit;
    }}
  }}

  return null;
}}

bool _startsWith(Uint8List data, List<int> prefix) {{
  if (data.length < prefix.length) {{
    return false;
  }}

  for (var index = 0; index < prefix.length; index++) {{
    if (data[index] != prefix[index]) {{
      return false;
    }}
  }}

  return true;
}}
"
	);

	Some(source)
}

/// Emit `computeUnits.ts` for one TypeScript client and export it from the
/// generated barrel.
pub(crate) fn emit_js_compute_units_module(
	generated: &Path,
	root: &RootNode,
) -> Result<(), CodamaError> {
	let budgets = instruction_budgets(&root.program)
		.map_err(|message| js_error(generated, std::io::Error::other(message)))?;
	let Some(module) = js_module(root.program.name.as_ref(), &budgets) else {
		return Ok(());
	};
	let module_path = generated.join("computeUnits.ts");
	let index_path = generated.join("index.ts");

	std::fs::write(&module_path, module).map_err(|source| js_error(&module_path, source))?;

	let index =
		std::fs::read_to_string(&index_path).map_err(|source| js_error(&index_path, source))?;

	if index.contains("\"./computeUnits\"") {
		return Ok(());
	}

	let patched = format!("{}\nexport * from \"./computeUnits\";\n", index.trim_end());
	std::fs::write(&index_path, patched).map_err(|source| js_error(&index_path, source))
}

/// Emit `compute_units.dart` for one Dart program and export it from the
/// program barrel, `<program>.dart`.
pub(crate) fn emit_dart_compute_units_module(
	generated: &Path,
	program: &str,
	root: &RootNode,
) -> Result<(), CodamaError> {
	let budgets =
		instruction_budgets(&root.program).map_err(|message| dart_error(generated, message))?;
	let Some(module) = dart_module(root.program.name.as_ref(), &budgets) else {
		return Ok(());
	};
	let module_path = generated.join("compute_units.dart");
	let barrel_path = generated.join(format!("{program}.dart"));

	std::fs::write(&module_path, module).map_err(|source| dart_error(&module_path, source))?;

	let barrel =
		std::fs::read_to_string(&barrel_path).map_err(|source| dart_error(&barrel_path, source))?;

	if barrel.contains("'compute_units.dart'") {
		return Ok(());
	}

	let patched = format!("{}\nexport 'compute_units.dart';\n", barrel.trim_end());
	std::fs::write(&barrel_path, patched).map_err(|source| dart_error(&barrel_path, source))
}

fn js_error(path: &Path, source: std::io::Error) -> CodamaError {
	CodamaError::HardenJavaScript {
		path: path.to_path_buf(),
		source,
	}
}

fn dart_error(
	path: &Path,
	source: impl Into<Box<dyn std::error::Error + Send + Sync>>,
) -> CodamaError {
	CodamaError::DartClient {
		path: path.to_path_buf(),
		source: source.into(),
	}
}

#[cfg(test)]
mod tests {
	use std::error::Error;
	use std::fs;

	use codama_nodes::BytesEncoding;
	use codama_nodes::ConstantDiscriminatorNode;
	use codama_nodes::ConstantValueNode;
	use codama_nodes::FieldDiscriminatorNode;
	use codama_nodes::NumberTypeNode;
	use codama_nodes::NumberValueNode;
	use codama_nodes::PluginNode;
	use codama_nodes::StringTypeNode;
	use codama_nodes::StringValueNode;
	use tempfile::TempDir;

	use super::*;

	type TestResult = Result<(), Box<dyn Error>>;

	fn discriminator(
		format: NumberFormat,
		endian: Endianness,
		value: impl Into<Number>,
	) -> DiscriminatorNode {
		DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				NumberTypeNode {
					format,
					endian,
					..NumberTypeNode::le(format)
				},
				NumberValueNode::new(value),
			),
			0,
		))
	}

	fn instruction(
		name: &str,
		discriminators: Vec<DiscriminatorNode>,
		budget: Option<(u32, u32)>,
	) -> InstructionNode {
		InstructionNode {
			name: name.into(),
			discriminators,
			plugins: budget
				.map(|(measured, limit)| vec![ComputeUnitBudget { measured, limit }.to_plugin()])
				.unwrap_or_default(),
			..InstructionNode::default()
		}
	}

	fn root(instructions: Vec<InstructionNode>) -> RootNode {
		let mut program = ProgramNode::new(
			"counterProgram",
			"GJQcuWrT2f3f4KNuJcXhhwUa1ZQTYbxzzJ1hotzKu8hS",
		);
		program.instructions = instructions;

		RootNode::new(program)
	}

	fn counter() -> RootNode {
		root(vec![
			instruction(
				"initialize",
				vec![discriminator(NumberFormat::U8, Endianness::Le, 0u64)],
				Some((1_704, 2_400)),
			),
			instruction(
				"increment",
				vec![discriminator(NumberFormat::U8, Endianness::Le, 1u64)],
				Some((379, 800)),
			),
			instruction(
				"close",
				vec![discriminator(NumberFormat::U8, Endianness::Le, 2u64)],
				None,
			),
		])
	}

	#[test]
	fn collects_measured_instructions_with_their_wire_discriminators() -> TestResult {
		let widths = [
			(NumberFormat::U16, 0x0102_u64, vec![0x02, 0x01]),
			(NumberFormat::U32, 0x0102_u64, vec![0x02, 0x01, 0, 0]),
			(
				NumberFormat::U64,
				0x0102_u64,
				vec![0x02, 0x01, 0, 0, 0, 0, 0, 0],
			),
		];

		for (format, value, bytes) in widths {
			let wide = root(vec![instruction(
				"makeOffer",
				vec![discriminator(format, Endianness::Le, value)],
				Some((900, 1_400)),
			)]);

			assert_eq!(
				instruction_budgets(&wide.program)?,
				[InstructionBudget {
					name: "makeOffer".to_owned(),
					discriminator: bytes,
					budget: ComputeUnitBudget {
						measured: 900,
						limit: 1_400,
					},
				}]
			);
		}

		assert_eq!(instruction_budgets(&counter().program)?.len(), 2);

		Ok(())
	}

	#[test]
	fn refuses_budgets_it_cannot_recognize_on_the_wire() {
		let text = DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				StringTypeNode::new(BytesEncoding::Utf8),
				StringValueNode::new("increment"),
			),
			0,
		));
		let offset = DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				NumberTypeNode::le(NumberFormat::U8),
				NumberValueNode::new(1u64),
			),
			4,
		));

		for discriminators in [
			Vec::new(),
			vec![DiscriminatorNode::Field(FieldDiscriminatorNode::new(
				"discriminator",
				0,
			))],
			vec![text],
			vec![offset],
			vec![discriminator(NumberFormat::U16, Endianness::Be, 1u64)],
			vec![discriminator(NumberFormat::F32, Endianness::Le, 1u64)],
			vec![discriminator(NumberFormat::U8, Endianness::Le, -1i64)],
		] {
			let program = root(vec![instruction(
				"increment",
				discriminators,
				Some((10, 20)),
			)]);
			let message = instruction_budgets(&program.program)
				.expect_err("an unrecognizable instruction must fail");
			assert!(message.contains("no little-endian constant discriminator"));
		}

		let malformed = root(vec![InstructionNode {
			name: "increment".into(),
			plugins: vec![PluginNode::new("pinaComputeUnits")],
			..InstructionNode::default()
		}]);
		assert!(
			instruction_budgets(&malformed.program)
				.expect_err("a malformed plugin must fail")
				.contains("pinaComputeUnits")
		);
	}

	#[test]
	fn renders_typescript_and_dart_modules_only_for_measured_programs() -> TestResult {
		let budgets = instruction_budgets(&counter().program)?;

		assert_eq!(js_module("counterProgram", &[]), None);
		assert_eq!(dart_module("counterProgram", &[]), None);

		let js =
			js_module("counterProgram", &budgets).ok_or("a measured program renders a module")?;
		assert!(js.contains("export const INITIALIZE_COMPUTE_UNIT_LIMIT = 2400;"));
		assert!(js.contains("export const INCREMENT_MEASURED_COMPUTE_UNITS = 379;"));
		assert!(js.contains("[new Uint8Array([1]), INCREMENT_COMPUTE_UNIT_LIMIT],"));
		assert!(js.contains("import { COUNTER_PROGRAM_PROGRAM_ADDRESS } from \"./programs\";"));
		assert!(js.contains("export function getCounterProgramComputeUnitLimit("));
		assert!(!js.contains("CLOSE_"));

		let dart = dart_module("counterProgram", &budgets)
			.ok_or("a measured program renders a library")?;
		assert!(dart.contains("const int initializeComputeUnitLimit = 2400;"));
		assert!(dart.contains("const int incrementMeasuredComputeUnits = 379;"));
		assert!(dart.contains("([1], incrementComputeUnitLimit),"));
		assert!(dart.contains("Address programAddress = counterProgramProgramAddress,"));
		assert!(dart.contains("int? getCounterProgramComputeUnitLimit("));
		assert!(!dart.contains("close"));

		Ok(())
	}

	#[test]
	fn emits_and_exports_the_typescript_module_once() -> TestResult {
		let directory = TempDir::new()?;
		let generated = directory.path();
		let index = generated.join("index.ts");
		fs::write(&index, "export * from \"./accounts\";\n")?;

		emit_js_compute_units_module(generated, &counter())?;
		emit_js_compute_units_module(generated, &counter())?;

		assert!(generated.join("computeUnits.ts").is_file());
		assert_eq!(
			fs::read_to_string(&index)?,
			"export * from \"./accounts\";\nexport * from \"./computeUnits\";\n"
		);

		Ok(())
	}

	#[test]
	fn emits_and_exports_the_dart_library_once() -> TestResult {
		let directory = TempDir::new()?;
		let generated = directory.path().join("counter_program");
		let barrel = generated.join("counter_program.dart");
		fs::create_dir(&generated)?;
		fs::write(&barrel, "export 'accounts/accounts.dart';\n")?;

		emit_dart_compute_units_module(&generated, "counter_program", &counter())?;
		emit_dart_compute_units_module(&generated, "counter_program", &counter())?;

		assert!(generated.join("compute_units.dart").is_file());
		assert_eq!(
			fs::read_to_string(&barrel)?,
			"export 'accounts/accounts.dart';\nexport 'compute_units.dart';\n"
		);

		Ok(())
	}

	#[test]
	fn leaves_unmeasured_clients_untouched_and_reports_broken_ones() -> TestResult {
		let directory = TempDir::new()?;
		let unmeasured = root(vec![instruction(
			"increment",
			vec![discriminator(NumberFormat::U8, Endianness::Le, 1u64)],
			None,
		)]);

		emit_js_compute_units_module(directory.path(), &unmeasured)?;
		emit_dart_compute_units_module(directory.path(), "counter_program", &unmeasured)?;
		assert_eq!(fs::read_dir(directory.path())?.count(), 0);

		assert!(matches!(
			emit_js_compute_units_module(directory.path(), &counter()),
			Err(CodamaError::HardenJavaScript { .. })
		));
		assert!(matches!(
			emit_dart_compute_units_module(directory.path(), "counter_program", &counter()),
			Err(CodamaError::DartClient { .. })
		));

		let broken = root(vec![instruction("increment", Vec::new(), Some((10, 20)))]);
		assert!(matches!(
			emit_js_compute_units_module(directory.path(), &broken),
			Err(CodamaError::HardenJavaScript { .. })
		));
		assert!(matches!(
			emit_dart_compute_units_module(directory.path(), "counter_program", &broken),
			Err(CodamaError::DartClient { .. })
		));

		Ok(())
	}
}
