use std::path::Path;

use serde_json::Value;

use crate::error::CodamaError;

/// Validates Dart renderer inputs before any Dart source is emitted.
///
/// Codec behavior belongs to `codama-renderers-dart` and the Solana Kit Dart
/// packages. Pina deliberately does not rewrite generated Dart source: a
/// renderer that cannot express Pina's semantic IDL must fail before emitting
/// a client rather than being patched with a second, divergent codec layer.
pub fn validate_dart_client_idls(
	output_root: &Path,
	programs: &[String],
	idl_paths: &[impl AsRef<Path>],
) -> Result<(), CodamaError> {
	if programs.len() != idl_paths.len() {
		return Err(dart_error(
			output_root,
			format!(
				"received {} programs but {} IDL paths",
				programs.len(),
				idl_paths.len(),
			),
		));
	}

	for idl_path in idl_paths {
		let idl_path = idl_path.as_ref();
		let idl_source = std::fs::read_to_string(idl_path).map_err(|source| {
			CodamaError::DartClient {
				path: idl_path.to_path_buf(),
				source: Box::new(source),
			}
		})?;
		let idl: Value = serde_json::from_str(&idl_source).map_err(|source| {
			CodamaError::DartClient {
				path: idl_path.to_path_buf(),
				source: Box::new(source),
			}
		})?;

		validate_supported_types(&idl, idl_path)?;
	}

	Ok(())
}

/// Writes deterministic package-root entrypoints for rendered Dart programs.
pub fn write_dart_package_barrels(
	output_root: &Path,
	programs: &[String],
) -> Result<(), CodamaError> {
	let mut programs = programs.to_vec();
	programs.sort();

	for program in programs {
		let source = format!(
			"// Auto-generated by `pina codama generate`. Do not edit.\n\nexport \
			 'src/generated/{program}/{program}.dart';\n",
		);
		let path = output_root.join("lib").join(format!("{program}.dart"));
		std::fs::write(&path, source).map_err(|source| {
			CodamaError::DartClient {
				path,
				source: Box::new(source),
			}
		})?;
	}

	Ok(())
}

fn validate_supported_types(value: &Value, path: &Path) -> Result<(), CodamaError> {
	match value {
		Value::Array(values) => {
			for value in values {
				validate_supported_types(value, path)?;
			}
		}
		Value::Object(object) => {
			let kind = object.get("kind").and_then(Value::as_str);

			if let Some(kind) = kind
				&& kind.ends_with("TypeNode")
				&& !matches!(
					kind,
					"arrayTypeNode"
						| "booleanTypeNode"
						| "bytesTypeNode" | "definedTypeLinkNode"
						| "enumEmptyVariantTypeNode"
						| "enumTypeNode" | "fixedSizeTypeNode"
						| "numberTypeNode" | "optionTypeNode"
						| "publicKeyTypeNode"
						| "sizePrefixTypeNode"
						| "stringTypeNode" | "structFieldTypeNode"
						| "structTypeNode"
				) {
				return Err(dart_error(
					path,
					format!("Dart renderer does not support semantic type `{kind}`"),
				));
			}

			match kind {
				Some("stringTypeNode") => {
					if object.get("encoding").and_then(Value::as_str) != Some("utf8") {
						return Err(dart_error(
							path,
							"Dart zeropod strings require UTF-8 encoding".to_owned(),
						));
					}
				}
				Some("numberTypeNode") => validate_number_type(object, path)?,
				Some("optionTypeNode") => validate_option_type(object, path)?,
				_ => {}
			}

			for value in object.values() {
				validate_supported_types(value, path)?;
			}
		}
		_ => {}
	}

	Ok(())
}

fn validate_number_type(
	object: &serde_json::Map<String, Value>,
	path: &Path,
) -> Result<(), CodamaError> {
	let format = object.get("format").and_then(Value::as_str);
	if !matches!(
		format,
		Some(
			"u8" | "u16"
				| "u32" | "u64"
				| "u128" | "i8"
				| "i16" | "i32"
				| "i64" | "i128"
				| "f32" | "f64"
		)
	) {
		return Err(dart_error(
			path,
			format!(
				"Dart renderer does not support number format `{}`",
				format.unwrap_or("<missing>"),
			),
		));
	}

	if object.get("endian").and_then(Value::as_str) != Some("le") {
		return Err(dart_error(
			path,
			"Pina zeropod numbers require little-endian encoding".to_owned(),
		));
	}

	Ok(())
}

fn validate_option_type(
	object: &serde_json::Map<String, Value>,
	path: &Path,
) -> Result<(), CodamaError> {
	if object.get("fixed").and_then(Value::as_bool) != Some(true) {
		return Err(dart_error(
			path,
			"Pina PodOption values require fixed-size option encoding".to_owned(),
		));
	}

	let prefix = object
		.get("prefix")
		.and_then(Value::as_object)
		.ok_or_else(|| dart_error(path, "Pina PodOption is missing its prefix".to_owned()))?;
	let format = prefix.get("format").and_then(Value::as_str);
	if !matches!(format, Some("u8" | "u16" | "u32")) {
		return Err(dart_error(
			path,
			format!(
				"Pina PodOption does not support prefix format `{}`",
				format.unwrap_or("<missing>"),
			),
		));
	}

	Ok(())
}

fn dart_error(path: impl AsRef<Path>, message: String) -> CodamaError {
	CodamaError::DartClient {
		path: path.as_ref().to_path_buf(),
		source: Box::new(std::io::Error::other(message)),
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn accepts_supported_zeropod_semantics() {
		let value = serde_json::json!({
			"kind": "structTypeNode",
			"fields": [
				{
					"kind": "structFieldTypeNode",
					"name": "value",
					"type": {
						"kind": "optionTypeNode",
						"fixed": true,
						"item": { "kind": "numberTypeNode", "format": "u64", "endian": "le" },
						"prefix": { "kind": "numberTypeNode", "format": "u8", "endian": "le" }
					}
				}
			]
		});

		validate_supported_types(&value, Path::new("fixture.json"))
			.expect("supported zeropod semantics must validate");
	}

	#[test]
	fn rejects_unknown_semantic_types() {
		let value = serde_json::json!({ "kind": "mapTypeNode" });
		let error = validate_supported_types(&value, Path::new("fixture.json"))
			.expect_err("map types must fail closed");

		assert!(error.to_string().contains("mapTypeNode"));
	}

	#[test]
	fn rejects_non_utf8_strings() {
		let value = serde_json::json!({ "kind": "stringTypeNode", "encoding": "base58" });
		let error = validate_supported_types(&value, Path::new("fixture.json"))
			.expect_err("non-UTF-8 strings must fail closed");

		assert!(error.to_string().contains("UTF-8"));
	}

	#[test]
	fn rejects_non_zeropod_number_layouts() {
		let value = serde_json::json!({
			"kind": "numberTypeNode",
			"format": "shortU16",
			"endian": "be"
		});
		let error = validate_supported_types(&value, Path::new("fixture.json"))
			.expect_err("unsupported numbers must fail closed");

		assert!(error.to_string().contains("shortU16"));
	}

	#[test]
	fn rejects_variable_and_wide_options() {
		for value in [
			serde_json::json!({
				"kind": "optionTypeNode",
				"fixed": false,
				"prefix": { "kind": "numberTypeNode", "format": "u8", "endian": "le" }
			}),
			serde_json::json!({
				"kind": "optionTypeNode",
				"fixed": true,
				"prefix": { "kind": "numberTypeNode", "format": "u64", "endian": "le" }
			}),
		] {
			validate_supported_types(&value, Path::new("fixture.json"))
				.expect_err("unsupported options must fail closed");
		}
	}
}
