use std::fs;
use std::path::Path;
use std::path::PathBuf;

use heck::ToUpperCamelCase;

// A non-system placeholder keeps the generated Surfpool deployment executable.
// Users must still replace it before sharing or deploying the project.
const PLACEHOLDER_PROGRAM_ID: &str = "Fg6PaFpoGXkYsidMpWxTWqkZkkM8NufCHCX9ddLKBqd7";

/// Errors produced during project initialization.
#[derive(Debug, thiserror::Error)]
pub enum InitError {
	#[error("invalid package name `{name}`")]
	InvalidPackageName { name: String },

	#[error("refusing to overwrite existing file: {path}")]
	DestinationExists { path: PathBuf },

	#[error("IO error at {path}: {source}")]
	Io {
		path: PathBuf,
		source: std::io::Error,
	},
}

/// All scaffold files generated by `pina init`, expressed as relative paths.
const SCAFFOLD_FILES: &[&str] = &[
	"Cargo.toml",
	"pina.toml",
	"README.md",
	".gitignore",
	".cargo/config.toml",
	"build.rs",
	"src/lib.rs",
	"src/entrypoint.rs",
	"tests/integration.rs",
	"rust-toolchain.toml",
	"tests/surfpool/Cargo.toml",
	"tests/surfpool/src/lib.rs",
];

/// Initialize a new Pina program project in `project_dir`.
///
/// When `force` is `false`, this function fails if any scaffold file already
/// exists. When `true`, scaffold files are overwritten.
pub fn init_project(project_dir: &Path, package_name: &str, force: bool) -> Result<(), InitError> {
	if !is_valid_package_name(package_name) {
		return Err(InitError::InvalidPackageName {
			name: package_name.to_owned(),
		});
	}

	// Resolve all destination paths up-front.
	let paths: Vec<PathBuf> = SCAFFOLD_FILES
		.iter()
		.map(|rel| project_dir.join(rel))
		.collect();

	// Check for existing files before writing anything.
	if !force {
		for path in &paths {
			if path.exists() {
				return Err(InitError::DestinationExists { path: path.clone() });
			}
		}
	}

	// Ensure all required directories exist.
	for dir in [
		project_dir.to_path_buf(),
		project_dir.join("src"),
		project_dir.join("tests"),
		project_dir.join("tests/surfpool/src"),
		project_dir.join(".cargo"),
	] {
		fs::create_dir_all(&dir).map_err(|source| InitError::Io { path: dir, source })?;
	}

	let program_title = package_name.replace(['-', '_'], " ").to_upper_camel_case();

	write_file(&paths[0], &cargo_toml_template(package_name))?;
	write_file(&paths[1], &pina_toml_template())?;
	write_file(&paths[2], &readme_template(package_name))?;
	write_file(&paths[3], &gitignore_template())?;
	write_file(&paths[4], &cargo_config_template())?;
	write_file(&paths[5], &build_script_template())?;
	write_file(&paths[6], &lib_template(package_name, &program_title))?;
	write_file(&paths[7], &entrypoint_template())?;
	write_file(
		&paths[8],
		&integration_test_template(package_name, &program_title),
	)?;
	write_file(&paths[9], &rust_toolchain_template())?;
	write_file(&paths[10], &surfpool_cargo_toml_template(package_name))?;
	write_file(&paths[11], &surfpool_test_template())?;

	Ok(())
}

/// Print next-steps guidance to stdout.
pub fn print_next_steps(project_dir: &Path, _package_name: &str) {
	println!();
	println!("  Next steps:");
	println!();
	println!("    cd {}", project_dir.display());
	println!("    # 1. Set your program address in src/lib.rs, then snapshot the ABI:");
	println!("    pina migrations make           # record the version-0 baseline");
	println!();
	println!("    pina lint                      # run Pina's security lints");
	println!("    pina build                     # build SBF and generate the IDL");
	println!("    pina test --unit               # fast native tests");
	println!("    pina test                      # build SBF and test with Surfpool");
	println!("    pina dev --yes                 # create and review the Surfpool runbook");
	println!("    pina generate                  # generate configured clients");
	println!();
	println!(
		"  Run `pina migrations make` only after the declared program address is final: the \
		 recorded history is bound to that address."
	);
	println!();
}

/// `pina.toml` for a new program.
///
/// Migrations are on by default. The recorded history is bound to the declared
/// program address, so the manifest is deliberately *not* scaffolded here: the
/// placeholder `declare_id!` would pin the history to an address the user is
/// about to replace. `pina migrations make` is the bootstrap step, and it runs
/// once the real address is in place.
fn pina_toml_template() -> String {
	r#"[project]
program = "."

[clients]
output = "clients"
languages = ["cpi", "rust", "typescript"]
mode = "auto"
scaffold = true

# ABI migrations. Versions are counted per contract, so `u8` gives every
# account, instruction, and event its own 255-version budget. The width is
# program-wide and freezes at the first published release, so it cannot be
# widened later; pick `u16` or `u32` before launch only if one contract is
# expected to need more.
[migrations]
version_type = "u8"
auto = true
"#
	.to_owned()
}

/// Build script that keeps macro expansion fresh when the migration policy or
/// manifest changes.
///
/// A proc macro does not re-expand when `pina.toml` or the manifest changes, so
/// the recorded `auto` policy needs this directive to take effect on the next
/// build. `pina migrations make` scaffolds the same file when it is missing.
fn build_script_template() -> String {
	"fn main() {\n\tprintln!(\"cargo:rerun-if-changed=migrations/manifest.json\");\n}\n".to_owned()
}

fn is_valid_package_name(name: &str) -> bool {
	if name.is_empty() {
		return false;
	}

	if name == "." || name == ".." {
		return false;
	}

	if name.contains('/') || name.contains('\\') || name.chars().any(char::is_whitespace) {
		return false;
	}

	name.chars()
		.all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
}

fn write_file(path: &Path, contents: &str) -> Result<(), InitError> {
	fs::write(path, contents).map_err(|source| {
		InitError::Io {
			path: path.to_path_buf(),
			source,
		}
	})
}

fn cargo_toml_template(package_name: &str) -> String {
	let pina_version = env!("CARGO_PKG_VERSION");

	format!(
		r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2024"
publish = false

[workspace.metadata.cli]
solana = "3.0.0"

[lib]
# `cdylib` only. A second `lib`/`rlib` crate type makes rustc reject LTO for
# the program, which costs 20-35% of deployed program size. Integration tests
# exercise the real source with the `#[path = "../src/lib.rs"]` pattern in
# `tests/integration.rs` instead of linking this crate.
crate-type = ["cdylib"]

[features]
default = []
# Enables formatted failure diagnostics and caller locations. Costs `core::fmt`
# in the deployed binary; use it while debugging, not for production deploys.
verbose-logs = ["pina/verbose-logs"]
bpf-entrypoint = []

[dependencies]
pina = {{ version = "{pina_version}", features = ["logs", "derive"] }}

# Production profile for the deployed program. Every setting here either
# shrinks the deployed binary or keeps the build honest about it.
#
# `overflow-checks` is opt-in: leaving it off turns arithmetic overflow from a
# panic into a wrap, which is cheaper but loses a real class of bug detection.
# Set it to `true` while the program is young even though it costs bytes.
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

# Build scripts and proc macros do not ship in the deployed program, so they
# should not be built at the program's opt-level or serialized behind its
# codegen-units setting.
[profile.release.build-override]
opt-level = 3
codegen-units = 1
incremental = false

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
	'cfg(target_os, values("solana"))',
]
"#
	)
}

fn readme_template(package_name: &str) -> String {
	format!(
		r"# {package_name}

Generated by `pina init`.

## Prerequisites

SBF compilation delegates to the Agave CLI's `cargo-build-sbf` driver. Install the Agave CLI (Solana `agave` release) once and keep it on `PATH`.

TypeScript client generation requires Node.js with npm and `npx`.

## Development

- Build SBF and IDL: `pina build`
- Build a deterministic deployable with Solana Verify: `pina build --verify`
- Generate configured clients: `pina generate`
- Run Pina's pinned security lint set: `pina lint`
- Apply machine-applicable security lint suggestions: `pina lint --fix`, then
  review the resulting diff
- Build (all features): `cargo build --all-features`
- Fast native tests: `pina test --unit`
- SBF integration tests on an isolated Surfpool instance: `pina test`
- Persistent development Surfnet: `pina dev --yes` on the first run, then
  review and commit the generated `txtx.yml`
- Generate a standalone CPI crate for other programs: `pina generate --client cpi`

## IDL

Generate Codama IDL JSON directly:

```bash
pina idl --path .
```
"
	)
}

fn rust_toolchain_template() -> String {
	r#"[toolchain]
channel = "nightly-2026-02-20"
components = ["rust-src"]
profile = "minimal"
"#
	.to_owned()
}

fn gitignore_template() -> String {
	"target/\n.DS_Store\n".to_owned()
}

fn cargo_config_template() -> String {
	"[alias]\nbuild-program = \"build-sbf --sbf-out-dir target/deploy -F bpf-entrypoint\"\n"
		.to_owned()
}

fn lib_template(package_name: &str, program_title: &str) -> String {
	format!(
		r#"//! {program_title} — starter Pina program generated by `pina init`.

#![allow(clippy::inline_always)]
#![no_std]

#[cfg(all(
	not(target_arch = "bpf"),
	not(feature = "bpf-entrypoint"),
	not(test)
))]
extern crate std;

#[cfg(feature = "bpf-entrypoint")]
pub mod entrypoint;

use pina::*;

// Replace this with your deployed program address before sharing the project.
declare_id!("{PLACEHOLDER_PROGRAM_ID}");

#[discriminator]
pub enum {program_title}Instruction {{
	Initialize = 0,
}}

#[instruction(discriminator = {program_title}Instruction::Initialize)]
pub struct InitializeInstruction {{
	pub value: u8,
}}

#[derive(Accounts, Debug)]
pub struct InitializeAccounts<'a> {{
	pub authority: &'a AccountView,
}}

impl<'a> ProcessAccountInfos<'a> for InitializeAccounts<'a> {{
	fn process(self, data: &[u8]) -> ProgramResult {{
		let args = InitializeInstruction::try_from_bytes(data)?;
		self.authority.assert_signer()?;
		if args.value == 0 {{
			return Err(ProgramError::InvalidArgument);
		}}

		log!("Initialized {package_name}");
		Ok(())
	}}
}}

// Unit tests live here, next to the code they cover, so `cargo test --lib`
// measures the real program source. The crate is `cdylib` only for LTO, and
// Cargo still builds this test harness from `src/lib.rs`.
#[cfg(test)]
mod tests {{
	use super::*;

	/// The instruction discriminator is part of the wire format. Treat a
	/// change here as a breaking change for deployed clients.
	#[test]
	fn instruction_discriminator_is_stable() {{
		assert_eq!({program_title}Instruction::Initialize as u8, 0);
	}}

	#[test]
	fn decodes_initialized_instruction() {{
		let mut data = [0u8; InitializeInstruction::SIZE];
		InitializeInstruction::initialize(&mut data, |args| {{
			args.value = 7;
			Ok(())
		}})
		.expect("initialize instruction storage");

		let decoded = InitializeInstruction::try_from_bytes(&data)
			.expect("decode initialized instruction");
		assert_eq!(decoded.value, 7);
	}}

	#[test]
	fn rejects_wrong_program_id() {{
		let wrong_id: Address = [9u8; 32].into();
		let data = [{program_title}Instruction::Initialize as u8];
		let result = parse_instruction::<{program_title}Instruction>(&wrong_id, &ID, &data);

		assert!(matches!(result, Err(ProgramError::IncorrectProgramId)));
	}}
}}

pub fn process_instruction(
	program_id: &Address,
	accounts: &mut [AccountView],
	data: &[u8],
) -> ProgramResult {{
	let instruction: {program_title}Instruction = parse_instruction(program_id, &ID, data)?;
	match instruction {{
		{program_title}Instruction::Initialize => {{
			InitializeAccounts::try_from((program_id, accounts))?.process(data)
		}}
	}}
}}
"#
	)
}

fn surfpool_cargo_toml_template(package_name: &str) -> String {
	let pina_version = env!("CARGO_PKG_VERSION");

	format!(
		r#"[package]
name = "{package_name}-surfpool-tests"
version = "0.0.0"
edition = "2024"
publish = false

# Keep Surfpool's host runtime dependency graph isolated from the program's
# native Mollusk tests and SBF build.
[workspace]

[dependencies]
# `pina` is required because this harness includes the program source, which
# imports pina directly.
pina = "{pina_version}"
pina_test = "{pina_version}"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
	'cfg(target_os, values("solana"))',
	'cfg(feature, values("bpf-entrypoint"))',
]
"#
	)
}

fn entrypoint_template() -> String {
	r"use pina::*;

use crate::*;

nostd_entrypoint!(process_instruction);
"
	.to_owned()
}

fn integration_test_template(package_name: &str, program_title: &str) -> String {
	let _ = (package_name, program_title);
	r#"//! Tests that need the compiled program artifact.
//!
//! The program crate is `cdylib` only so the deployed binary can use fat LTO.
//! Cargo cannot link a `cdylib` into an integration test, which means this
//! file cannot `use` the program's types. Two patterns cover that gap:
//!
//! 1. Behavioural coverage lives in `src/lib.rs` under `#[cfg(test)] mod
//!    tests`, next to the code it exercises. Run it with `cargo test --lib`;
//!    it measures coverage of the real program source.
//! 2. On-chain behaviour lives in `tests/surfpool`, which `pina test` runs
//!    against the built SBF artifact.
//!
//! Keep this file for anything that only needs the compiled artifact path.

/// Pina's build publishes the deploy artifact for `pina test`.
#[test]
fn deploy_artifact_path_is_conventional() {
	let artifact = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
		.join("target/deploy")
		.join(env!("CARGO_PKG_NAME"));

	assert!(
		artifact.extension().is_none(),
		"artifact base path is {}",
		artifact.display()
	);
}
"#
	.to_owned()
}

fn surfpool_test_template() -> String {
	r#"#![cfg(test)]

use pina_test::AccountMeta;
use pina_test::ProgramTest;
use pina_test::Pubkey;

// The program crate is `cdylib` only (so the deployed binary can use fat LTO)
// and cannot be linked as a dependency. Include its source instead: the
// program id and instruction encoders below are the real ones.
#[path = "../../../src/lib.rs"]
mod program;

use program::ID;
use program::InitializeInstruction;

/// Deploy the real SBF artifact to an isolated, offline Surfnet.
///
/// `pina test` supplies the artifact path and runs ignored Surfpool tests after
/// building SBF. Keeping this ignored during `cargo test` preserves the fast
/// native/Mollusk loop.
#[test]
#[ignore = "run with `pina test`"]
fn initialize_runs_on_surfpool() {{
	pina_test::run(async {{
		let program_id = Pubkey::new_from_array(ID.to_bytes());
		let mut program = ProgramTest::start(program_id)
			.await
			.expect("start isolated program test");
		let authority = program.payer();
		let mut data = [0u8; InitializeInstruction::SIZE];
		InitializeInstruction::initialize(&mut data, |args| {{
			args.value = 42;
			Ok(())
		}})
		.expect("initialize instruction storage");
		let instruction = program.instruction(
			&data,
			vec![AccountMeta::new_readonly(authority, true)],
		);
		program
			.send_instruction(instruction)
			.expect("execute Initialize instruction");

		program.stop().expect("stop isolated program test");
	}});
}}
"#
	.to_owned()
}

#[cfg(test)]
mod tests {
	use super::*;

	struct TempDir {
		path: PathBuf,
	}

	impl TempDir {
		fn new(prefix: &str) -> Self {
			let timestamp = std::time::SystemTime::now()
				.duration_since(std::time::UNIX_EPOCH)
				.map_or(0, |duration| duration.as_nanos());
			let path = std::env::temp_dir().join(format!(
				"pina_cli_{prefix}_{}_{}",
				std::process::id(),
				timestamp
			));
			Self { path }
		}
	}

	impl Drop for TempDir {
		fn drop(&mut self) {
			let _ = fs::remove_dir_all(&self.path);
		}
	}

	#[test]
	fn init_project_creates_scaffold() {
		let dir = TempDir::new("create");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		for rel_path in SCAFFOLD_FILES {
			assert!(
				dir.path.join(rel_path).exists(),
				"expected scaffold file to exist: {rel_path}"
			);
		}
		assert!(!dir.path.join("src/cpi.rs").exists());

		let cargo = fs::read_to_string(dir.path.join("Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Cargo.toml to be readable: {err}"));
		assert!(cargo.contains("name = \"my_program\""));
		assert!(cargo.contains(&format!(
			"pina = {{ version = \"{}\"",
			env!("CARGO_PKG_VERSION")
		)));
		assert!(cargo.contains("default = []"));
		assert!(cargo.contains("bpf-entrypoint = []"));
		assert!(!cargo.contains("cpi = []"));
		assert!(cargo.contains("[workspace.metadata.cli]"));
		assert!(cargo.contains("solana = \"3.0.0\""));
		assert!(!cargo.contains("[workspace.metadata.bin]"));
		assert!(!cargo.contains("dylint"));
		assert!(!cargo.contains("[workspace.metadata.dylint]"));
		assert!(!cargo.contains("dylint_lib"));
		assert!(!cargo.contains("mollusk-svm"));

		let config = fs::read_to_string(dir.path.join("pina.toml"))
			.unwrap_or_else(|err| panic!("expected pina.toml to be readable: {err}"));
		assert!(config.contains("program = \".\""));
		assert!(config.contains("languages = [\"cpi\", \"rust\", \"typescript\"]"));
		assert!(!cargo.contains("pina_test"));
		assert!(!cargo.contains("surfpool-tests"));
		assert!(!cargo.contains("surfpool-sdk"));

		let surfpool_cargo = fs::read_to_string(dir.path.join("tests/surfpool/Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Surfpool Cargo.toml to be readable: {err}"));
		assert!(surfpool_cargo.contains("name = \"my_program-surfpool-tests\""));
		assert!(surfpool_cargo.contains("[workspace]"));
		assert!(surfpool_cargo.contains(&format!("pina_test = \"{}\"", env!("CARGO_PKG_VERSION"))));
		// The harness includes the program source, so it depends on pina
		// rather than on the cdylib program crate.
		assert!(surfpool_cargo.contains(&format!("pina = \"{}\"", env!("CARGO_PKG_VERSION"))));
		assert!(!surfpool_cargo.contains("program_under_test"));
		assert!(!surfpool_cargo.contains("surfpool-sdk"));
	}

	/// Migrations are on by default, and the manifest is deliberately absent:
	/// it would bind the recorded history to the placeholder program address.
	#[test]
	fn init_project_enables_migrations_without_pinning_the_placeholder_address() {
		let dir = TempDir::new("migrations_default");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let config = fs::read_to_string(dir.path.join("pina.toml"))
			.unwrap_or_else(|err| panic!("expected pina.toml to be readable: {err}"));
		let parsed: toml::Value = toml::from_str(&config)
			.unwrap_or_else(|err| panic!("scaffolded pina.toml must parse: {err}"));
		let migrations = parsed
			.get("migrations")
			.and_then(toml::Value::as_table)
			.unwrap_or_else(|| panic!("scaffold must configure [migrations]"));

		assert_eq!(
			migrations.get("version_type").and_then(toml::Value::as_str),
			Some("u8")
		);
		assert_eq!(
			migrations.get("auto").and_then(toml::Value::as_bool),
			Some(true)
		);

		// The scaffold must not pre-record a history: `make` pins the declared
		// program address, and the scaffold still carries the placeholder.
		assert!(!dir.path.join("migrations").exists());

		// The auto policy needs the rerun directive so a policy flip re-expands.
		let build_script = fs::read_to_string(dir.path.join("build.rs"))
			.unwrap_or_else(|err| panic!("expected build.rs to be readable: {err}"));
		assert!(build_script.contains("cargo:rerun-if-changed=migrations/manifest.json"));
	}

	#[test]
	fn init_project_creates_entrypoint() {
		let dir = TempDir::new("entrypoint");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let entrypoint = fs::read_to_string(dir.path.join("src/entrypoint.rs"))
			.unwrap_or_else(|err| panic!("expected entrypoint.rs to be readable: {err}"));
		assert!(entrypoint.contains("nostd_entrypoint!"));
		assert!(entrypoint.contains("use crate::*;"));
		assert!(!entrypoint.contains("pub fn process_instruction"));
	}

	#[test]
	fn init_project_creates_cargo_config() {
		let dir = TempDir::new("cargo_config");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let config = fs::read_to_string(dir.path.join(".cargo/config.toml"))
			.unwrap_or_else(|err| panic!("expected .cargo/config.toml to be readable: {err}"));
		assert!(config.contains("build-program"));
		assert!(config.contains("build-sbf"));
		assert!(!config.contains("sbpf-linker"));

		let toolchain = fs::read_to_string(dir.path.join("rust-toolchain.toml"))
			.unwrap_or_else(|err| panic!("expected rust-toolchain.toml to be readable: {err}"));
		assert!(toolchain.contains("nightly-2026-02-20"));
		assert!(toolchain.contains("rust-src"));
		let readme = fs::read_to_string(dir.path.join("README.md"))
			.unwrap_or_else(|err| panic!("expected README.md to be readable: {err}"));
		assert!(readme.contains("cargo-build-sbf"));
		assert!(readme.contains("Node.js with npm and `npx`"));
		assert!(readme.contains("pina lint"));
		assert!(readme.contains("pina lint --fix"));
	}

	#[test]
	fn init_project_creates_integration_test() {
		let dir = TempDir::new("integration");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let test = fs::read_to_string(dir.path.join("tests/integration.rs"))
			.unwrap_or_else(|err| panic!("expected integration.rs to be readable: {err}"));
		// Behavioural coverage lives in-crate because the crate is cdylib
		// only; this file keeps only artifact-level assertions.
		assert!(test.contains("cargo test --lib"));
		assert!(test.contains("tests/surfpool"));
	}

	#[test]
	fn init_project_creates_real_surfpool_test() {
		let dir = TempDir::new("surfpool");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let test = fs::read_to_string(dir.path.join("tests/surfpool/src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected Surfpool lib.rs to be readable: {err}"));
		assert!(test.contains("ProgramTest::start(program_id)"));
		assert!(test.contains("send_instruction"));
		assert!(test.contains("execute Initialize instruction"));
		assert!(test.contains("let mut program"));
		assert!(test.contains("program.stop()"));
		assert!(!test.contains("Uncomment"));
	}

	#[test]
	fn init_project_lib_references_entrypoint_module() {
		let dir = TempDir::new("lib_entrypoint");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let lib = fs::read_to_string(dir.path.join("src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected lib.rs to be readable: {err}"));
		assert!(lib.contains("pub mod entrypoint;"));
		assert!(!lib.contains("pub mod cpi;"));
		assert!(lib.contains("process_instruction"));
		assert!(lib.contains("pub struct InitializeInstruction"));
		assert!(lib.contains("self.authority.assert_signer()?"));
		assert!(!lib.contains("surfpool-tests"));
	}

	#[test]
	fn init_project_refuses_existing_files_without_force() {
		let dir = TempDir::new("exists");
		fs::create_dir_all(&dir.path)
			.unwrap_or_else(|err| panic!("expected temp dir creation to succeed: {err}"));
		fs::write(
			dir.path.join("Cargo.toml"),
			"[package]\nname = \"existing\"",
		)
		.unwrap_or_else(|err| panic!("expected seed file write to succeed: {err}"));

		let result = init_project(&dir.path, "my_program", false);

		match result {
			Err(InitError::DestinationExists { path }) => {
				assert!(path.ends_with("Cargo.toml"));
			}
			other => panic!("expected DestinationExists error, got: {other:?}"),
		}
	}

	#[test]
	fn init_project_overwrites_when_force_enabled() {
		let dir = TempDir::new("force");
		fs::create_dir_all(dir.path.join("src"))
			.unwrap_or_else(|err| panic!("expected src dir creation to succeed: {err}"));
		fs::write(dir.path.join("Cargo.toml"), "invalid")
			.unwrap_or_else(|err| panic!("expected initial Cargo.toml write to succeed: {err}"));
		fs::write(dir.path.join("src/lib.rs"), "invalid")
			.unwrap_or_else(|err| panic!("expected initial lib.rs write to succeed: {err}"));

		init_project(&dir.path, "my_program", true)
			.unwrap_or_else(|err| panic!("expected forced init to succeed: {err}"));

		let cargo = fs::read_to_string(dir.path.join("Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Cargo.toml to be readable: {err}"));
		assert!(cargo.contains("name = \"my_program\""));
		assert!(!cargo.contains("invalid"));
	}

	#[test]
	fn init_project_reports_final_surfpool_test_write_failure() {
		let dir = TempDir::new("surfpool_write_failure");
		let blocked_file = dir.path.join("tests/surfpool/src/lib.rs");
		fs::create_dir_all(&blocked_file)
			.unwrap_or_else(|err| panic!("expected blocking directory creation to succeed: {err}"));

		let result = init_project(&dir.path, "my_program", true);

		assert!(matches!(
			result,
			Err(InitError::Io { path, .. }) if path == blocked_file
		));
	}

	#[test]
	fn init_project_rejects_invalid_name() {
		let dir = TempDir::new("invalid_name");
		let result = init_project(&dir.path, "not valid", false);
		assert!(matches!(result, Err(InitError::InvalidPackageName { .. })));
	}

	#[test]
	fn init_project_handles_hyphenated_name() {
		let dir = TempDir::new("hyphen");
		init_project(&dir.path, "my-cool-program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let lib = fs::read_to_string(dir.path.join("src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected lib.rs to be readable: {err}"));
		// Hyphenated name should produce CamelCase title.
		assert!(lib.contains("MyCoolProgramInstruction"));

		// In-crate unit tests are the coverage path for cdylib programs.
		assert!(lib.contains("#[cfg(test)]"));
	}

	#[test]
	fn surfpool_manifest_alias_avoids_support_crate_name_collisions() {
		for package_name in ["pina-test", "pina_test"] {
			let dir = TempDir::new(package_name);
			init_project(&dir.path, package_name, false)
				.unwrap_or_else(|err| panic!("expected {package_name} init to succeed: {err}"));
			let manifest = dir.path.join("tests/surfpool/Cargo.toml");
			let manifest = fs::read_to_string(&manifest)
				.unwrap_or_else(|err| panic!("read generated manifest for {package_name}: {err}"));
			let manifest: toml::Value = toml::from_str(&manifest)
				.unwrap_or_else(|err| panic!("parse generated manifest for {package_name}: {err}"));
			let dependencies = manifest
				.get("dependencies")
				.and_then(toml::Value::as_table)
				.unwrap_or_else(|| panic!("dependencies must be a table for {package_name}"));

			assert_eq!(dependencies.len(), 2);
			assert_eq!(
				dependencies.get("pina_test").and_then(toml::Value::as_str),
				Some(env!("CARGO_PKG_VERSION"))
			);
			// The harness includes the program source, so it depends on pina
			// directly instead of linking the cdylib program crate.
			assert_eq!(
				dependencies.get("pina").and_then(toml::Value::as_str),
				Some(env!("CARGO_PKG_VERSION"))
			);
			assert!(dependencies.get("program_under_test").is_none());
			let source = fs::read_to_string(dir.path.join("tests/surfpool/src/lib.rs"))
				.unwrap_or_else(|err| panic!("read generated test for {package_name}: {err}"));
			assert!(source.contains("#[path = \"../../../src/lib.rs\"]"));
			assert!(source.contains("use program::"));
		}
	}
}
