use std::fs;
use std::path::Path;
use std::path::PathBuf;

use heck::ToUpperCamelCase;

// A non-system placeholder keeps the generated Surfpool deployment executable.
// Users must still replace it before sharing or deploying the project.
const PLACEHOLDER_PROGRAM_ID: &str = "Fg6PaFpoGXkYsidMpWxTWqkZkkM8NufCHCX9ddLKBqd7";

/// Errors produced during project initialization.
#[derive(Debug, thiserror::Error)]
pub enum InitError {
	#[error("invalid package name `{name}`")]
	InvalidPackageName { name: String },

	#[error("refusing to overwrite existing file: {path}")]
	DestinationExists { path: PathBuf },

	#[error("IO error at {path}: {source}")]
	Io {
		path: PathBuf,
		source: std::io::Error,
	},
}

/// All scaffold files generated by `pina init`, expressed as relative paths.
const SCAFFOLD_FILES: &[&str] = &[
	"Cargo.toml",
	"pina.toml",
	"README.md",
	".gitignore",
	".cargo/config.toml",
	"src/lib.rs",
	"src/entrypoint.rs",
	"src/cpi.rs",
	"tests/integration.rs",
	"rust-toolchain.toml",
	"tests/surfpool/Cargo.toml",
	"tests/surfpool/src/lib.rs",
];

/// Initialize a new Pina program project in `project_dir`.
///
/// When `force` is `false`, this function fails if any scaffold file already
/// exists. When `true`, scaffold files are overwritten.
pub fn init_project(project_dir: &Path, package_name: &str, force: bool) -> Result<(), InitError> {
	if !is_valid_package_name(package_name) {
		return Err(InitError::InvalidPackageName {
			name: package_name.to_owned(),
		});
	}

	// Resolve all destination paths up-front.
	let paths: Vec<PathBuf> = SCAFFOLD_FILES
		.iter()
		.map(|rel| project_dir.join(rel))
		.collect();

	// Check for existing files before writing anything.
	if !force {
		for path in &paths {
			if path.exists() {
				return Err(InitError::DestinationExists { path: path.clone() });
			}
		}
	}

	// Ensure all required directories exist.
	for dir in [
		project_dir.to_path_buf(),
		project_dir.join("src"),
		project_dir.join("tests"),
		project_dir.join("tests/surfpool/src"),
		project_dir.join(".cargo"),
	] {
		fs::create_dir_all(&dir).map_err(|source| InitError::Io { path: dir, source })?;
	}

	let program_title = package_name.replace(['-', '_'], " ").to_upper_camel_case();

	write_file(&paths[0], &cargo_toml_template(package_name))?;
	write_file(&paths[1], &pina_toml_template())?;
	write_file(&paths[2], &readme_template(package_name))?;
	write_file(&paths[3], &gitignore_template())?;
	write_file(&paths[4], &cargo_config_template())?;
	write_file(&paths[5], &lib_template(package_name, &program_title))?;
	write_file(&paths[6], &entrypoint_template())?;
	write_file(&paths[7], &cpi_template(&program_title))?;
	write_file(
		&paths[8],
		&integration_test_template(package_name, &program_title),
	)?;
	write_file(&paths[9], &rust_toolchain_template())?;
	write_file(&paths[10], &surfpool_cargo_toml_template(package_name))?;
	write_file(&paths[11], &surfpool_test_template())?;

	Ok(())
}

/// Print next-steps guidance to stdout.
pub fn print_next_steps(project_dir: &Path, _package_name: &str) {
	println!();
	println!("  Next steps:");
	println!();
	println!("    cd {}", project_dir.display());
	println!("    pina lint                      # run Pina's security lints");
	println!("    pina build                     # build SBF and generate the IDL");
	println!("    pina test --unit               # fast native tests");
	println!("    pina test                      # build SBF and test with Surfpool");
	println!("    pina dev --yes                 # create and review the Surfpool runbook");
	println!("    pina generate                  # generate configured clients");
	println!();
	println!("  Update the program address in src/lib.rs with your deployed program ID.");
	println!();
}

fn pina_toml_template() -> String {
	r#"[project]
program = "."

[clients]
output = "clients"
languages = ["rust", "typescript"]
"#
	.to_owned()
}

fn is_valid_package_name(name: &str) -> bool {
	if name.is_empty() {
		return false;
	}

	if name == "." || name == ".." {
		return false;
	}

	if name.contains('/') || name.contains('\\') || name.chars().any(char::is_whitespace) {
		return false;
	}

	name.chars()
		.all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
}

fn write_file(path: &Path, contents: &str) -> Result<(), InitError> {
	fs::write(path, contents).map_err(|source| {
		InitError::Io {
			path: path.to_path_buf(),
			source,
		}
	})
}

fn cargo_toml_template(package_name: &str) -> String {
	let pina_version = env!("CARGO_PKG_VERSION");

	format!(
		r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2024"
publish = false

[workspace.metadata.cli]
solana = "3.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
bpf-entrypoint = []
cpi = []

[dependencies]
pina = {{ version = "{pina_version}", features = ["logs", "derive"] }}

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
	'cfg(target_os, values("solana"))',
]
"#
	)
}

fn readme_template(package_name: &str) -> String {
	format!(
		r#"# {package_name}

Generated by `pina init`.

## Prerequisites

SBF compilation delegates to the Agave CLI's `cargo-build-sbf` driver. Install the Agave CLI (Solana `agave` release) once and keep it on `PATH`.

TypeScript client generation requires Node.js with npm and `npx`.

## Development

- Build SBF and IDL: `pina build`
- Build a deterministic deployable with Solana Verify: `pina build --verify`
- Generate configured clients: `pina generate`
- Run Pina's pinned security lint set: `pina lint`
- Apply machine-applicable security lint suggestions: `pina lint --fix`, then
  review the resulting diff
- Build (all features): `cargo build --all-features`
- Fast native tests: `pina test --unit`
- SBF integration tests on an isolated Surfpool instance: `pina test`
- Persistent development Surfnet: `pina dev --yes` on the first run, then
  review and commit the generated `txtx.yml`
- Export typed CPI builders for another program:
  `features = ["cpi"]`

## IDL

Generate Codama IDL JSON directly:

```bash
pina idl --path .
```
"#
	)
}

fn rust_toolchain_template() -> String {
	r#"[toolchain]
channel = "nightly-2026-02-20"
components = ["rust-src"]
profile = "minimal"
"#
	.to_owned()
}

fn gitignore_template() -> String {
	"target/\n.DS_Store\n".to_owned()
}

fn cargo_config_template() -> String {
	"[alias]\nbuild-program = \"build-sbf --sbf-out-dir target/deploy -F bpf-entrypoint\"\n"
		.to_owned()
}

fn lib_template(package_name: &str, program_title: &str) -> String {
	format!(
		r#"//! {program_title} — starter Pina program generated by `pina init`.

#![allow(clippy::inline_always)]
#![no_std]

#[cfg(all(
	not(target_arch = "bpf"),
	not(feature = "bpf-entrypoint"),
	not(test)
))]
extern crate std;

#[cfg(feature = "bpf-entrypoint")]
pub mod entrypoint;

#[cfg(feature = "cpi")]
pub mod cpi;

use pina::*;

// Replace this with your deployed program address before sharing the project.
declare_id!("{PLACEHOLDER_PROGRAM_ID}");

#[discriminator]
pub enum {program_title}Instruction {{
	Initialize = 0,
}}

#[instruction(discriminator = {program_title}Instruction::Initialize)]
pub struct InitializeInstruction {{
	pub value: u8,
}}

#[derive(Accounts, Debug)]
pub struct InitializeAccounts<'a> {{
	pub authority: &'a AccountView,
}}

impl<'a> ProcessAccountInfos<'a> for InitializeAccounts<'a> {{
	fn process(self, data: &[u8]) -> ProgramResult {{
		let args = InitializeInstruction::try_from_bytes(data)?;
		self.authority.assert_signer()?;
		if args.value == 0 {{
			return Err(ProgramError::InvalidArgument);
		}}

		log!("Initialized {package_name}");
		Ok(())
	}}
}}

pub fn process_instruction(
	program_id: &Address,
	accounts: &mut [AccountView],
	data: &[u8],
) -> ProgramResult {{
	let instruction: {program_title}Instruction = parse_instruction(program_id, &ID, data)?;
	match instruction {{
		{program_title}Instruction::Initialize => {{
			InitializeAccounts::try_from((program_id, accounts))?.process(data)
		}}
	}}
}}
"#
	)
}

fn surfpool_cargo_toml_template(package_name: &str) -> String {
	let pina_version = env!("CARGO_PKG_VERSION");

	format!(
		r#"[package]
name = "{package_name}-surfpool-tests"
version = "0.0.0"
edition = "2024"
publish = false

# Keep Surfpool's host runtime dependency graph isolated from the program's
# native Mollusk tests and SBF build.
[workspace]

[dependencies]
pina_test = "{pina_version}"
program_under_test = {{ package = "{package_name}", path = "../.." }}
"#
	)
}

fn entrypoint_template() -> String {
	r"use pina::*;

use crate::*;

nostd_entrypoint!(process_instruction);
"
	.to_owned()
}

fn cpi_template(program_title: &str) -> String {
	format!(
		r#"//! Typed CPI builders for this Pina program.
//!
//! This module is compiled only when the `cpi` feature is enabled. Keep that
//! feature disabled for deployment builds unless another on-chain program needs
//! to call this program through its typed CPI surface.

use pina::*;

use crate::ID;
use crate::InitializeInstruction;

/// Marker for this program's ID used by generated CPI builders.
#[derive(Clone, Copy, Debug)]
pub struct {program_title}Program;

impl CpiProgramId for {program_title}Program {{
	const ID: Address = ID;
}}

/// A validated executable account for this program.
pub type ProgramAccount<'a> = Program<'a, {program_title}Program>;

pub mod accounts {{
	use super::*;

	/// Accounts required to initialize the program.
	#[derive(Clone, Copy, Debug)]
	pub struct Initialize<'a> {{
		/// Signer authorizing initialization.
		pub authority: CpiHandle<'a>,
	}}

	impl<'a> Initialize<'a> {{
		/// Validates signer privileges and builds the CPI account set.
		pub const fn new(authority: &'a AccountView) -> Self {{
			Self {{
				authority: CpiHandle::readonly_signer(authority),
			}}
		}}
	}}

	impl<'a> ToCpiAccounts<'a, 1> for Initialize<'a> {{
		fn to_cpi_handles(&self) -> [CpiHandle<'a>; 1] {{
			[self.authority]
		}}
	}}
}}

pub mod instructions {{
	use super::*;

	/// Initializes the program through a typed CPI.
	#[derive(Clone, Copy, Debug)]
	#[must_use = "the CPI has no effect until invoke or invoke_signed is called"]
	pub struct Initialize<'a> {{
		/// Validated accounts required by the initialize instruction.
		pub accounts: accounts::Initialize<'a>,

		/// Non-zero value accepted by the starter handler.
		pub value: u8,
	}}

	impl<'a> Initialize<'a> {{
		/// Builds an initialize CPI instruction.
		#[inline(always)]
		pub const fn new(accounts: accounts::Initialize<'a>, value: u8) -> Self {{
			Self {{ accounts, value }}
		}}

		/// Invokes the program using transaction-level signatures.
		#[inline(always)]
		pub fn invoke(&self, program: &ProgramAccount<'_>) -> ProgramResult {{
			self.invoke_signed(program, &[])
		}}

		/// Invokes the program with additional PDA signer seeds.
		#[inline(always)]
		pub fn invoke_signed(
			&self,
			program: &ProgramAccount<'_>,
			signers: &[Signer<'_, '_>],
		) -> ProgramResult {{
			let mut data = [0u8; InitializeInstruction::SIZE];
			let args = InitializeInstruction::initialize(&mut data)?;
			args.value = self.value;
			let ctx = CpiContext::new(*program, self.accounts);

			ctx.invoke_signed(&data, signers)
		}}
	}}
}}

"#
	)
}

fn integration_test_template(package_name: &str, program_title: &str) -> String {
	let package_ident = package_name.replace('-', "_");
	format!(
		r#"use {package_ident}::*;

/// Smoke test: verify that the instruction discriminator is stable.
#[test]
fn instruction_discriminators_are_stable() {{
	assert_eq!({program_title}Instruction::Initialize as u8, 0);
}}

/// Smoke test: parse_instruction rejects a mismatched program ID.
#[test]
fn parse_instruction_rejects_wrong_program_id() {{
	let wrong_id: pina::Address = [9u8; 32].into();
	let data = [{program_title}Instruction::Initialize as u8];
	let result =
		pina::parse_instruction::<{program_title}Instruction>(&wrong_id, &ID, &data);
	assert!(matches!(result, Err(pina::ProgramError::IncorrectProgramId)));
}}

/// Fast native test for the client-facing instruction encoder.
#[test]
fn initialize_instruction_encodes_fields() {{
	let mut data = [0u8; InitializeInstruction::SIZE];
	let args = InitializeInstruction::initialize(&mut data)
		.expect("initialize instruction storage");
	args.value = 42;

	let decoded = InitializeInstruction::try_from_bytes(&data)
		.expect("decode initialized instruction");
	assert_eq!(decoded.value, 42);
}}
"#
	)
}

fn surfpool_test_template() -> String {
	r#"#![cfg(test)]

use pina_test::AccountMeta;
use pina_test::ProgramTest;
use pina_test::Pubkey;

use program_under_test::ID;
use program_under_test::InitializeInstruction;

/// Deploy the real SBF artifact to an isolated, offline Surfnet.
///
/// `pina test` supplies the artifact path and runs ignored Surfpool tests after
/// building SBF. Keeping this ignored during `cargo test` preserves the fast
/// native/Mollusk loop.
#[test]
#[ignore = "run with `pina test`"]
fn initialize_runs_on_surfpool() {{
	pina_test::run(async {{
		let program_id = Pubkey::new_from_array(ID.to_bytes());
		let mut program = ProgramTest::start(program_id)
			.await
			.expect("start isolated program test");
		let authority = program.payer();
		let mut data = [0u8; InitializeInstruction::SIZE];
		let args = InitializeInstruction::initialize(&mut data)
			.expect("initialize instruction storage");
		args.value = 42;
		let instruction = program.instruction(
			&data,
			vec![AccountMeta::new_readonly(authority, true)],
		);
		program
			.send_instruction(instruction)
			.expect("execute Initialize instruction");

		program.stop().expect("stop isolated program test");
	}});
}}
"#
	.to_owned()
}

#[cfg(test)]
mod tests {
	use super::*;

	struct TempDir {
		path: PathBuf,
	}

	impl TempDir {
		fn new(prefix: &str) -> Self {
			let timestamp = std::time::SystemTime::now()
				.duration_since(std::time::UNIX_EPOCH)
				.map_or(0, |duration| duration.as_nanos());
			let path = std::env::temp_dir().join(format!(
				"pina_cli_{prefix}_{}_{}",
				std::process::id(),
				timestamp
			));
			Self { path }
		}
	}

	impl Drop for TempDir {
		fn drop(&mut self) {
			let _ = fs::remove_dir_all(&self.path);
		}
	}

	#[test]
	fn init_project_creates_scaffold() {
		let dir = TempDir::new("create");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		for rel_path in SCAFFOLD_FILES {
			assert!(
				dir.path.join(rel_path).exists(),
				"expected scaffold file to exist: {rel_path}"
			);
		}

		let cargo = fs::read_to_string(dir.path.join("Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Cargo.toml to be readable: {err}"));
		assert!(cargo.contains("name = \"my_program\""));
		assert!(cargo.contains(&format!(
			"pina = {{ version = \"{}\"",
			env!("CARGO_PKG_VERSION")
		)));
		assert!(cargo.contains("default = []"));
		assert!(cargo.contains("bpf-entrypoint = []"));
		assert!(cargo.contains("cpi = []"));
		assert!(cargo.contains("[workspace.metadata.cli]"));
		assert!(cargo.contains("solana = \"3.0.0\""));
		assert!(!cargo.contains("[workspace.metadata.bin]"));
		assert!(!cargo.contains("dylint"));
		assert!(!cargo.contains("[workspace.metadata.dylint]"));
		assert!(!cargo.contains("dylint_lib"));
		assert!(!cargo.contains("mollusk-svm"));

		let config = fs::read_to_string(dir.path.join("pina.toml"))
			.unwrap_or_else(|err| panic!("expected pina.toml to be readable: {err}"));
		assert!(config.contains("program = \".\""));
		assert!(config.contains("languages = [\"rust\", \"typescript\"]"));
		assert!(!cargo.contains("pina_test"));
		assert!(!cargo.contains("surfpool-tests"));
		assert!(!cargo.contains("surfpool-sdk"));

		let surfpool_cargo = fs::read_to_string(dir.path.join("tests/surfpool/Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Surfpool Cargo.toml to be readable: {err}"));
		assert!(surfpool_cargo.contains("name = \"my_program-surfpool-tests\""));
		assert!(surfpool_cargo.contains("[workspace]"));
		assert!(surfpool_cargo.contains(&format!("pina_test = \"{}\"", env!("CARGO_PKG_VERSION"))));
		assert!(
			surfpool_cargo
				.contains("program_under_test = { package = \"my_program\", path = \"../..\" }")
		);
		assert!(!surfpool_cargo.contains("surfpool-sdk"));
	}

	#[test]
	fn init_project_creates_entrypoint() {
		let dir = TempDir::new("entrypoint");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let entrypoint = fs::read_to_string(dir.path.join("src/entrypoint.rs"))
			.unwrap_or_else(|err| panic!("expected entrypoint.rs to be readable: {err}"));
		assert!(entrypoint.contains("nostd_entrypoint!"));
		assert!(entrypoint.contains("use crate::*;"));
		assert!(!entrypoint.contains("pub fn process_instruction"));
	}

	#[test]
	fn init_project_creates_feature_gated_cpi_module() {
		let dir = TempDir::new("cpi");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let cpi = fs::read_to_string(dir.path.join("src/cpi.rs"))
			.unwrap_or_else(|err| panic!("expected cpi.rs to be readable: {err}"));
		assert!(cpi.contains("pub struct MyProgramProgram;"));
		assert!(cpi.contains("impl CpiProgramId for MyProgramProgram"));
		assert!(cpi.contains("pub type ProgramAccount<'a>"));
		assert!(cpi.contains("pub mod accounts"));
		assert!(cpi.contains("pub mod instructions"));
		assert!(cpi.contains("authority: CpiHandle::readonly_signer(authority)"));
		assert!(cpi.contains("InitializeInstruction::initialize"));
		assert!(cpi.contains("pub accounts: accounts::Initialize<'a>"));
		assert!(cpi.contains("pub value: u8"));
		assert!(cpi.contains("pub fn invoke_signed"));
		assert!(cpi.contains("ctx.invoke_signed(&data, signers)"));
		assert!(!cpi.contains("ctx.invoke(&data, signers)"));
		assert!(!cpi.contains("pub const fn initialize("));
	}

	#[test]
	fn init_project_creates_cargo_config() {
		let dir = TempDir::new("cargo_config");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let config = fs::read_to_string(dir.path.join(".cargo/config.toml"))
			.unwrap_or_else(|err| panic!("expected .cargo/config.toml to be readable: {err}"));
		assert!(config.contains("build-program"));
		assert!(config.contains("build-sbf"));
		assert!(!config.contains("sbpf-linker"));

		let toolchain = fs::read_to_string(dir.path.join("rust-toolchain.toml"))
			.unwrap_or_else(|err| panic!("expected rust-toolchain.toml to be readable: {err}"));
		assert!(toolchain.contains("nightly-2026-02-20"));
		assert!(toolchain.contains("rust-src"));
		let readme = fs::read_to_string(dir.path.join("README.md"))
			.unwrap_or_else(|err| panic!("expected README.md to be readable: {err}"));
		assert!(readme.contains("cargo-build-sbf"));
		assert!(readme.contains("Node.js with npm and `npx`"));
		assert!(readme.contains("pina lint"));
		assert!(readme.contains("pina lint --fix"));
	}

	#[test]
	fn init_project_creates_integration_test() {
		let dir = TempDir::new("integration");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let test = fs::read_to_string(dir.path.join("tests/integration.rs"))
			.unwrap_or_else(|err| panic!("expected integration.rs to be readable: {err}"));
		assert!(test.contains("use my_program::*;"));
		assert!(test.contains("instruction_discriminators_are_stable"));
		assert!(test.contains("initialize_instruction_encodes_fields"));
	}

	#[test]
	fn init_project_creates_real_surfpool_test() {
		let dir = TempDir::new("surfpool");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let test = fs::read_to_string(dir.path.join("tests/surfpool/src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected Surfpool lib.rs to be readable: {err}"));
		assert!(test.contains("ProgramTest::start(program_id)"));
		assert!(test.contains("send_instruction"));
		assert!(test.contains("execute Initialize instruction"));
		assert!(test.contains("let mut program"));
		assert!(test.contains("program.stop()"));
		assert!(!test.contains("Uncomment"));
	}

	#[test]
	fn init_project_lib_references_entrypoint_module() {
		let dir = TempDir::new("lib_entrypoint");
		init_project(&dir.path, "my_program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let lib = fs::read_to_string(dir.path.join("src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected lib.rs to be readable: {err}"));
		assert!(lib.contains("pub mod entrypoint;"));
		assert!(lib.contains("#[cfg(feature = \"cpi\")]"));
		assert!(lib.contains("pub mod cpi;"));
		assert!(lib.contains("process_instruction"));
		assert!(lib.contains("pub struct InitializeInstruction"));
		assert!(lib.contains("self.authority.assert_signer()?"));
		assert!(!lib.contains("surfpool-tests"));
	}

	#[test]
	fn init_project_refuses_existing_files_without_force() {
		let dir = TempDir::new("exists");
		fs::create_dir_all(&dir.path)
			.unwrap_or_else(|err| panic!("expected temp dir creation to succeed: {err}"));
		fs::write(
			dir.path.join("Cargo.toml"),
			"[package]\nname = \"existing\"",
		)
		.unwrap_or_else(|err| panic!("expected seed file write to succeed: {err}"));

		let result = init_project(&dir.path, "my_program", false);

		match result {
			Err(InitError::DestinationExists { path }) => {
				assert!(path.ends_with("Cargo.toml"));
			}
			other => panic!("expected DestinationExists error, got: {other:?}"),
		}
	}

	#[test]
	fn init_project_overwrites_when_force_enabled() {
		let dir = TempDir::new("force");
		fs::create_dir_all(dir.path.join("src"))
			.unwrap_or_else(|err| panic!("expected src dir creation to succeed: {err}"));
		fs::write(dir.path.join("Cargo.toml"), "invalid")
			.unwrap_or_else(|err| panic!("expected initial Cargo.toml write to succeed: {err}"));
		fs::write(dir.path.join("src/lib.rs"), "invalid")
			.unwrap_or_else(|err| panic!("expected initial lib.rs write to succeed: {err}"));

		init_project(&dir.path, "my_program", true)
			.unwrap_or_else(|err| panic!("expected forced init to succeed: {err}"));

		let cargo = fs::read_to_string(dir.path.join("Cargo.toml"))
			.unwrap_or_else(|err| panic!("expected Cargo.toml to be readable: {err}"));
		assert!(cargo.contains("name = \"my_program\""));
		assert!(!cargo.contains("invalid"));
	}

	#[test]
	fn init_project_reports_final_surfpool_test_write_failure() {
		let dir = TempDir::new("surfpool_write_failure");
		let blocked_file = dir.path.join("tests/surfpool/src/lib.rs");
		fs::create_dir_all(&blocked_file)
			.unwrap_or_else(|err| panic!("expected blocking directory creation to succeed: {err}"));

		let result = init_project(&dir.path, "my_program", true);

		assert!(matches!(
			result,
			Err(InitError::Io { path, .. }) if path == blocked_file
		));
	}

	#[test]
	fn init_project_rejects_invalid_name() {
		let dir = TempDir::new("invalid_name");
		let result = init_project(&dir.path, "not valid", false);
		assert!(matches!(result, Err(InitError::InvalidPackageName { .. })));
	}

	#[test]
	fn init_project_handles_hyphenated_name() {
		let dir = TempDir::new("hyphen");
		init_project(&dir.path, "my-cool-program", false)
			.unwrap_or_else(|err| panic!("expected init to succeed: {err}"));

		let lib = fs::read_to_string(dir.path.join("src/lib.rs"))
			.unwrap_or_else(|err| panic!("expected lib.rs to be readable: {err}"));
		// Hyphenated name should produce CamelCase title.
		assert!(lib.contains("MyCoolProgramInstruction"));

		let test = fs::read_to_string(dir.path.join("tests/integration.rs"))
			.unwrap_or_else(|err| panic!("expected integration.rs to be readable: {err}"));
		// The `use` import should use underscores (Rust ident).
		assert!(test.contains("use my_cool_program::*;"));
	}

	#[test]
	fn surfpool_manifest_alias_avoids_support_crate_name_collisions() {
		for package_name in ["pina-test", "pina_test"] {
			let dir = TempDir::new(package_name);
			init_project(&dir.path, package_name, false)
				.unwrap_or_else(|err| panic!("expected {package_name} init to succeed: {err}"));
			let manifest = dir.path.join("tests/surfpool/Cargo.toml");
			let manifest = fs::read_to_string(&manifest)
				.unwrap_or_else(|err| panic!("read generated manifest for {package_name}: {err}"));
			let manifest: toml::Value = toml::from_str(&manifest)
				.unwrap_or_else(|err| panic!("parse generated manifest for {package_name}: {err}"));
			let dependencies = manifest
				.get("dependencies")
				.and_then(toml::Value::as_table)
				.unwrap_or_else(|| panic!("dependencies must be a table for {package_name}"));

			assert_eq!(dependencies.len(), 2);
			assert_eq!(
				dependencies.get("pina_test").and_then(toml::Value::as_str),
				Some(env!("CARGO_PKG_VERSION"))
			);
			let program = dependencies
				.get("program_under_test")
				.and_then(toml::Value::as_table)
				.unwrap_or_else(|| panic!("program alias must be a table for {package_name}"));
			assert_eq!(
				program.get("package").and_then(toml::Value::as_str),
				Some(package_name)
			);
			assert_eq!(
				program.get("path").and_then(toml::Value::as_str),
				Some("../..")
			);
			let source = fs::read_to_string(dir.path.join("tests/surfpool/src/lib.rs"))
				.unwrap_or_else(|err| panic!("read generated test for {package_name}: {err}"));
			assert!(source.contains("use program_under_test::"));
		}
	}
}
