//! Generated JavaScript module for the event log read path.
//!
//! The upstream Codama renderer emits one `events/<name>.ts` codec module per
//! event. This module adds the program-level read path around them: it decodes
//! `Program data:` log lines, projects historical event bytes into the current
//! shape when the checked-in manifest proves an automatic transition, and
//! reports the source version so consumers can tell a projected event from an
//! emitted one. Versions without a derivable projection fail closed.

use std::path::Path;

use codama_nodes::DiscriminatorNode;
use codama_nodes::EventNode;
use codama_nodes::Number;
use codama_nodes::NumberFormat;
use codama_nodes::RootNode;
use codama_nodes::TypeNode;
use codama_nodes::ValueNode;

use crate::client_events::EventClientHistory;
use crate::client_events::EventClientHistoryIndex;
use crate::client_migrations::pascal_case;
use crate::client_migrations::shouting_snake;
use crate::error::CodamaError;
use crate::js_client::snake_to_camel;

/// Emit `events/logs.ts` for one program when it declares events.
///
/// Programs without events get no module. Every event gets a log entry point;
/// migration-aware events additionally get `normalize*` with historical
/// projection and source-version provenance.
pub(crate) fn emit_js_event_log_module(
	generated: &Path,
	program: &str,
	histories: &EventClientHistoryIndex,
	root: &RootNode,
) -> Result<(), CodamaError> {
	if root.program.events.is_empty() {
		return Ok(());
	}
	let Some(module) = event_log_module(program, &root.program.events, histories) else {
		return Ok(());
	};

	let events_dir = generated.join("events");
	let module_path = events_dir.join("logs.ts");
	std::fs::write(&module_path, module).map_err(|source| {
		CodamaError::HardenJavaScript {
			path: module_path.clone(),
			source,
		}
	})?;

	let index_path = events_dir.join("index.ts");
	let index = std::fs::read_to_string(&index_path).map_err(|source| {
		CodamaError::HardenJavaScript {
			path: index_path.clone(),
			source,
		}
	})?;
	if !index.contains("\"./logs\"") {
		let patched = index.replacen(
			"export * from",
			"export * from \"./logs\";\nexport * from",
			1,
		);
		std::fs::write(&index_path, patched).map_err(|source| {
			CodamaError::HardenJavaScript {
				path: index_path,
				source,
			}
		})?;
	}

	Ok(())
}

fn event_log_module(
	program: &str,
	events: &[EventNode],
	histories: &EventClientHistoryIndex,
) -> Option<String> {
	let mut imports = Vec::new();
	let mut body = Vec::new();
	let mut decoders = Vec::new();

	for event in events {
		let Some(facts) = event_facts(event, histories) else {
			continue;
		};
		let name = event.name.as_ref().to_owned();
		let pascal = pascal_case(&name);
		let shouting = shouting_snake(&name);
		let type_name = format!("{pascal}Event");
		let decoder = format!("get{type_name}Decoder");
		let _ = shouting;
		imports.push(format!(
			"import {{\n\t{decoder},\n\tget{pascal}EventDiscriminatorBytes,\n\ttype \
			 {type_name},\n}} from \"./{name}.js\";"
		));
		body.push(decoder_module(&name, &pascal, &type_name, &decoder, &facts));
		decoders.push((name.clone(), pascal, type_name));
	}

	if body.is_empty() {
		// Every event lacks a constant discriminator, so no log line can be
		// attributed to it. The upstream codec modules remain the only entry.
		return None;
	}

	let program_pascal = pascal_case(&snake_to_camel(program));
	let union = decoders
		.iter()
		.map(|(_, pascal, _)| format!("\t| Decoded{pascal}Event"))
		.collect::<Vec<_>>()
		.join("\n");
	let dispatches = decoders
		.iter()
		.map(|(_, pascal, _)| {
			let binding = lower_camel(pascal);
			format!(
				"\t\tconst {binding} = parse{pascal}EventFromLog(log);\n\t\tif ({binding} !== \
				 null) {{\n\t\t\tdiscovered.push({binding});\n\t\t\tcontinue;\n\t\t}}"
			)
		})
		.collect::<Vec<_>>()
		.join("\n");

	Some(format!(
		r#"/**
 * This code was AUTOGENERATED using the Codama library and Pina's migration
 * manifest. Please DO NOT EDIT THIS FILE, instead rerun client generation.
 *
 * Event log read path: decode `Program data:` log lines into typed events,
 * project historical bytes into the current shape when the checked-in
 * migration manifest proves the transition is automatic, and report the
 * source version that wrote the log. Versions without a derivable projection
 * fail with the reason instead of misreading.
 */

import {{ getBase64Encoder, type ReadonlyUint8Array }} from "@solana/kit";
{imports}

{body}

/** Every event this program can emit, as decoded from a log line. */
export type Decoded{program_pascal}Event =
{union};

/**
 * Decode every `Program data:` line that names one of this program's events.
 *
 * Unrelated lines and programs are skipped. A log that names an event but
 * carries an unknown, future, or non-projectable version throws instead of
 * being silently dropped.
 */
export function parse{program_pascal}EventsFromLogs(
	logs: readonly string[],
): Decoded{program_pascal}Event[] {{
	const discovered: Decoded{program_pascal}Event[] = [];
	for (const log of logs) {{
{dispatches}
	}}
	return discovered;
}}
"#,
		imports = imports.join("\n"),
		body = body.join("\n"),
	))
}

/// The per-event decoding module.
fn decoder_module(
	name: &str,
	pascal: &str,
	type_name: &str,
	decoder: &str,
	facts: &EventFacts<'_>,
) -> String {
	let shouting = shouting_snake(name);
	let discriminator_len = facts.discriminator.len();

	if let (Some(envelope), Some(history)) = (&facts.envelope, facts.history) {
		return projected_decoder_module(
			name,
			pascal,
			type_name,
			decoder,
			&shouting,
			discriminator_len,
			envelope,
			history,
		);
	}

	let version_check = facts
		.envelope
		.as_ref()
		.map_or_else(String::new, |envelope| {
			let version = envelope.version;
			let version_read = version_read("bytes", discriminator_len, envelope.version_bytes);
			format!(
				"\tconst sourceVersion = {version_read};\n\tif (sourceVersion !== {version}) \
				 {{\n\t\tthrow new RangeError(\n\t\t\t`event migration version mismatch: expected \
				 {version}, received ${{sourceVersion}} (the log was written by a different \
				 schema; regenerate this client)`,\n\t\t);\n\t}}\n"
			)
		});
	let header_size =
		discriminator_len + facts.envelope.as_ref().map_or(0, |env| env.version_bytes);
	let version_note = if facts.envelope.is_some() {
		"the event carries no checked-in migration history, so only its current version decodes"
	} else {
		"the event has no version envelope; only its current layout decodes"
	};

	format!(
		r#"/**
 * Decode one current-layout event record: {version_note}.
 */
export function normalize{pascal}Event(
	data: ReadonlyUint8Array | Uint8Array,
): Decoded{pascal}Event {{
	const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
	const discriminatorBytes = get{pascal}EventDiscriminatorBytes();
	if (bytes.length < {header_size}) {{
		throw new RangeError(
			`the provided data is too short for the "{type_name}" event envelope`,
		);
	}}
	for (let index = 0; index < {discriminator_len}; index += 1) {{
		if (bytes[index] !== discriminatorBytes[index]) {{
			throw new RangeError(
				'the provided data does not match the "{type_name}" event discriminator.',
			);
		}}
	}}
{version_check}	return {{ name: "{name}", data: {decoder}().decode(bytes) }};
}}

/** One log entry that named this event. */
export type Decoded{pascal}Event = {{ name: "{name}"; data: {type_name} }};

/**
 * Decode a `Program data:` log line, or return `null` when the line is not
 * this event.
 */
export function parse{pascal}EventFromLog(log: string): Decoded{pascal}Event | null {{
	const prefix = "Program data: ";
	if (!log.startsWith(prefix)) {{
		return null;
	}}
	const bytes = getBase64Encoder().encode(log.slice(prefix.length));
	if (bytes.length < {discriminator_len}) {{
		return null;
	}}
	const discriminatorBytes = get{pascal}EventDiscriminatorBytes();
	for (let index = 0; index < {discriminator_len}; index += 1) {{
		if (bytes[index] !== discriminatorBytes[index]) {{
			return null;
		}}
	}}
	return normalize{pascal}Event(bytes);
}}
"#,
	)
}

#[allow(clippy::too_many_arguments)]
fn projected_decoder_module(
	name: &str,
	pascal: &str,
	type_name: &str,
	decoder: &str,
	shouting: &str,
	discriminator_len: usize,
	envelope: &EventEnvelope,
	history: &EventClientHistory,
) -> String {
	let steps = history
		.steps
		.iter()
		.map(|step| {
			let moves = step
				.moves
				.iter()
				.map(|movement| {
					format!(
						"[{}, {}, {}]",
						movement.source_offset, movement.destination_offset, movement.size,
					)
				})
				.collect::<Vec<_>>()
				.join(", ");
			format!(
				"\t{{\n\t\tfrom: {from},\n\t\tto: {to},\n\t\tautomatic: \
				 {automatic},\n\t\tsourcePayloadSize: {source_size},\n\t\tdestinationPayloadSize: \
				 {size},\n\t\tmoves: [{moves}],\n\t}},",
				from = step.from,
				to = step.to,
				automatic = step.automatic,
				source_size = step.source_payload_size,
				size = step.destination_payload_size,
			)
		})
		.collect::<Vec<_>>()
		.join("\n");
	let current_version = u32::try_from(envelope.version).unwrap_or(u32::MAX);
	let version = envelope.version;
	let manual_steps = history
		.steps
		.iter()
		.filter(|step| !step.automatic)
		.map(|step| format!("{}", step.from))
		.collect::<Vec<_>>()
		.join(", ");
	let header_size = discriminator_len + envelope.version_bytes;
	let version_read = version_read("bytes", discriminator_len, envelope.version_bytes);
	let version_write = version_write("projected", "header", version, envelope.version_bytes);

	format!(
		r#"interface {pascal}EventProjectionStep {{
	readonly from: number;
	readonly to: number;
	readonly automatic: boolean;
	readonly sourcePayloadSize: number;
	readonly destinationPayloadSize: number;
	readonly moves: readonly (readonly [number, number, number])[];
}}

/**
 * Adjacent projections derived from the checked-in migration manifest.
 * Adjacent steps compose, mirroring the runtime's `normalize_event_data`.
 */
const {shouting}_EVENT_PROJECTION_STEPS: readonly {pascal}EventProjectionStep[] = [
{steps}
];

/** Versions whose adjacent transition is manual and not derivable in clients. */
const {shouting}_EVENT_MANUAL_VERSIONS: readonly number[] = [{manual_steps}];

const {shouting}_EVENT_HEADER_SIZE = {header_size};
const {shouting}_EVENT_CURRENT_VERSION = {current_version};

/** Raw event bytes with their source version and whether a projection ran. */
export type Normalized{pascal}Event = {{
	name: "{name}";
	data: {type_name};
	sourceVersion: number;
	wasMigrated: boolean;
}};

/**
 * Decode one event record, projecting historical versions into the current
 * shape and retaining the version that actually wrote the bytes.
 *
 * Unknown, future, and non-projectable versions fail closed with the reason.
 */
export function normalize{pascal}Event(
	data: ReadonlyUint8Array | Uint8Array,
): Normalized{pascal}Event {{
	const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
	const discriminatorBytes = get{pascal}EventDiscriminatorBytes();
	if (bytes.length < {shouting}_EVENT_HEADER_SIZE) {{
		throw new RangeError(
			`the provided data is too short for the "{type_name}" event envelope`,
		);
	}}
	for (let index = 0; index < {discriminator_len}; index += 1) {{
		if (bytes[index] !== discriminatorBytes[index]) {{
			throw new RangeError(
				'the provided data does not match the "{type_name}" event discriminator.',
			);
		}}
	}}
	const sourceVersion = {version_read};
	if (sourceVersion === {shouting}_EVENT_CURRENT_VERSION) {{
		return {{
			name: "{name}",
			data: {decoder}().decode(bytes),
			sourceVersion,
			wasMigrated: false,
		}};
	}}
	if (sourceVersion > {shouting}_EVENT_CURRENT_VERSION) {{
		throw new RangeError(
			`event migration version mismatch: expected {current_version}, received ${{sourceVersion}} (the log was written by a newer program; upgrade this client)`,
		);
	}}
	const projected = project{pascal}Event(bytes, sourceVersion);
	return {{
		name: "{name}",
		data: {decoder}().decode(projected),
		sourceVersion,
		wasMigrated: true,
	}};
}}

/** One log entry that named this event. */
export type Decoded{pascal}Event = Normalized{pascal}Event;

/**
 * Decode a `Program data:` log line, or return `null` when the line is not
 * this event.
 *
 * Lines that name the event but carry an unprojectable version throw.
 */
export function parse{pascal}EventFromLog(log: string): Decoded{pascal}Event | null {{
	const prefix = "Program data: ";
	if (!log.startsWith(prefix)) {{
		return null;
	}}
	const bytes = getBase64Encoder().encode(log.slice(prefix.length));
	if (bytes.length < {discriminator_len}) {{
		return null;
	}}
	const discriminatorBytes = get{pascal}EventDiscriminatorBytes();
	for (let index = 0; index < {discriminator_len}; index += 1) {{
		if (bytes[index] !== discriminatorBytes[index]) {{
			return null;
		}}
	}}
	return normalize{pascal}Event(bytes);
}}

function project{pascal}Event(
	bytes: Uint8Array,
	sourceVersion: number,
): Uint8Array {{
	const discriminatorBytes = get{pascal}EventDiscriminatorBytes();
	let version = sourceVersion;
	let payload = bytes.slice({shouting}_EVENT_HEADER_SIZE);
	while (version !== {shouting}_EVENT_CURRENT_VERSION) {{
		const step = {shouting}_EVENT_PROJECTION_STEPS.find(
			(candidate) => candidate.from === version,
		);
		if (step === undefined || !step.automatic) {{
			const reason = {shouting}_EVENT_MANUAL_VERSIONS.includes(version)
				? "its adjacent transition is manual, so only an on-chain projection or a client generated from that schema can represent it"
				: "this client has no checked-in projection for it";
			throw new RangeError(
				`event migration version mismatch: expected {current_version}, received ${{version}} (${{reason}})`,
			);
		}}
		if (payload.length !== step.sourcePayloadSize) {{
			throw new RangeError(
				`event migration version mismatch: expected {current_version}, received ${{version}} (the log length does not match the v${{version}} schema)`,
			);
		}}
		const destination = new Uint8Array(step.destinationPayloadSize);
		for (const [sourceOffset, destinationOffset, size] of step.moves) {{
			destination.set(
				payload.subarray(sourceOffset, sourceOffset + size),
				destinationOffset,
			);
		}}
		payload = destination;
		version = step.to;
	}}

	const projected = new Uint8Array({shouting}_EVENT_HEADER_SIZE + payload.length);
	projected.set(discriminatorBytes, 0);
	const header = {discriminator_len};
	{version_write}
	projected.set(payload, {shouting}_EVENT_HEADER_SIZE);
	return projected;
}}
"#,
	)
}

/// Envelope facts for one migration-aware event.
struct EventEnvelope {
	/// Little-endian discriminator bytes.
	discriminator: Vec<u8>,
	/// Version width in bytes.
	version_bytes: usize,
	/// Current schema version.
	version: u64,
}

/// Everything the JS emitter needs about one event node.
struct EventFacts<'a> {
	discriminator: Vec<u8>,
	envelope: Option<EventEnvelope>,
	history: Option<&'a EventClientHistory>,
}

fn event_facts<'a>(
	event: &EventNode,
	histories: &'a EventClientHistoryIndex,
) -> Option<EventFacts<'a>> {
	let (discriminator_value, discriminator_width) =
		event.discriminators.iter().find_map(|discriminator| {
			let DiscriminatorNode::Constant(constant) = discriminator else {
				return None;
			};
			let ValueNode::Number(number) = constant.constant.value.as_ref() else {
				return None;
			};
			let TypeNode::Number(number_type) = constant.constant.r#type.as_ref() else {
				return None;
			};
			let width = number_width(number_type.format)?;
			let Number::UnsignedInteger(value) = number.number else {
				return None;
			};
			Some((value, width))
		})?;
	let discriminator = discriminator_value.to_le_bytes()[..discriminator_width].to_vec();
	let envelope = event_migration_envelope(event, &discriminator);
	let history = envelope
		.as_ref()
		.and_then(|envelope| envelope.history(histories));

	Some(EventFacts {
		discriminator,
		envelope,
		history,
	})
}

impl EventEnvelope {
	fn history<'a>(
		&self,
		histories: &'a EventClientHistoryIndex,
	) -> Option<&'a EventClientHistory> {
		let mut padded = [0_u8; 8];
		let width = self.discriminator.len().min(padded.len());
		padded[..width].copy_from_slice(&self.discriminator[..width]);
		histories.get(self.discriminator.len(), u64::from_le_bytes(padded))
	}
}

/// Read the `[discriminator][migrationVersion]` envelope from an event node.
fn event_migration_envelope(event: &EventNode, discriminator: &[u8]) -> Option<EventEnvelope> {
	let TypeNode::Struct(data) = event.data.as_ref() else {
		return None;
	};
	let fields = &data.fields;
	let mut envelope = fields.iter().filter_map(|field| {
		let default_value = field.default_value.as_ref().as_ref()?;
		let kind = match field.name.as_ref() {
			"discriminator" => "discriminator",
			"migrationVersion" => "migrationVersion",
			_ => return None,
		};
		Some((kind, field.r#type.as_ref(), default_value))
	});
	let number_facts = |field_type: &TypeNode, default_value: &ValueNode| {
		let ValueNode::Number(number) = default_value else {
			return None;
		};
		let TypeNode::Number(number_type) = field_type else {
			return None;
		};
		let width = number_width(number_type.format)?;
		let Number::UnsignedInteger(value) = number.number else {
			return None;
		};
		Some((value, width))
	};

	let Some(("discriminator", field_type, default_value)) = envelope.next() else {
		return None;
	};
	let _ = number_facts(field_type, default_value)?;
	let Some(("migrationVersion", field_type, default_value)) = envelope.next() else {
		return None;
	};
	let (version, version_bytes) = number_facts(field_type, default_value)?;

	Some(EventEnvelope {
		discriminator: discriminator.to_vec(),
		version_bytes,
		version,
	})
}

fn number_width(format: NumberFormat) -> Option<usize> {
	match format {
		NumberFormat::U8 => Some(1),
		NumberFormat::U16 => Some(2),
		NumberFormat::U32 => Some(4),
		NumberFormat::U64 => Some(8),
		_ => None,
	}
}

/// A TypeScript expression reading a little-endian version from `source`.
fn version_read(source: &str, offset: usize, width: usize) -> String {
	match width {
		2 => format!("{source}[{offset}] | ({source}[{}] << 8)", offset + 1),
		4 => {
			format!(
				"{source}[{offset}] | ({source}[{}] << 8) | ({source}[{}] << 16) | ({source}[{}] \
				 << 24)",
				offset + 1,
				offset + 2,
				offset + 3,
			)
		}
		_ => format!("{source}[{offset}]"),
	}
}

/// A TypeScript statement writing a little-endian version into `target`.
fn version_write(target: &str, offset: &str, version: u64, width: usize) -> String {
	match width {
		2 => {
			format!(
				"{target}[{offset}] = {version} & 0xff;\n\t{target}[{offset} + 1] = ({version} >> \
				 8) & 0xff;"
			)
		}
		4 => {
			format!(
				"{target}[{offset}] = {version} & 0xff;\n\t{target}[{offset} + 1] = ({version} >> \
				 8) & 0xff;\n\t{target}[{offset} + 2] = ({version} >> 16) & \
				 0xff;\n\t{target}[{offset} + 3] = ({version} >> 24) & 0xff;"
			)
		}
		_ => format!("{target}[{offset}] = {version};"),
	}
}

fn lower_camel(pascal: &str) -> String {
	let mut characters = pascal.chars();
	match characters.next() {
		Some(first) => first.to_lowercase().collect::<String>() + characters.as_str(),
		None => String::new(),
	}
}

#[cfg(test)]
mod tests {
	use std::path::PathBuf;

	use codama_nodes::ConstantDiscriminatorNode;
	use codama_nodes::ConstantValueNode;
	use codama_nodes::DefaultValueStrategy;
	use codama_nodes::NumberTypeNode;
	use codama_nodes::NumberValueNode;
	use codama_nodes::PublicKeyTypeNode;
	use codama_nodes::RootNode;
	use codama_nodes::SizeDiscriminatorNode;
	use codama_nodes::StringTypeNode;
	use codama_nodes::StringValueNode;
	use codama_nodes::StructFieldTypeNode;
	use codama_nodes::StructTypeNode;

	use super::*;

	fn workspace_root() -> PathBuf {
		Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
	}

	fn read_idl(name: &str) -> RootNode {
		let path = workspace_root().join("codama/idls").join(name);
		let source = std::fs::read_to_string(&path)
			.unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
		serde_json::from_str(&source)
			.unwrap_or_else(|error| panic!("decode {}: {error}", path.display()))
	}

	fn migrations_history() -> EventClientHistory {
		EventClientHistory {
			rust_name: "ValueChangedEvent".to_owned(),
			discriminator: vec![4],
			current_version: 1,
			steps: vec![crate::client_events::EventProjectionStep {
				from: 0,
				to: 1,
				automatic: true,
				source_payload_size: 8,
				destination_payload_size: 10,
				moves: vec![crate::client_events::EventFieldMove {
					source_offset: 0,
					destination_offset: 0,
					size: 8,
				}],
			}],
		}
	}

	fn number_field(name: &str, format: NumberFormat, number: Number) -> StructFieldTypeNode {
		let mut field =
			StructFieldTypeNode::new(name, TypeNode::Number(NumberTypeNode::le(format)));
		field.default_value = Box::new(Some(ValueNode::Number(NumberValueNode { number })));
		field.default_value_strategy = Some(DefaultValueStrategy::Omitted);
		field
	}

	fn constant_discriminator(format: NumberFormat, number: Number) -> DiscriminatorNode {
		DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(NumberTypeNode::le(format), NumberValueNode { number }),
			0,
		))
	}

	fn envelope_event(name: &str, version_format: NumberFormat, version: Number) -> EventNode {
		let data = StructTypeNode::new(vec![
			number_field(
				"discriminator",
				NumberFormat::U8,
				Number::UnsignedInteger(4),
			),
			number_field("migrationVersion", version_format, version),
			number_field("value", NumberFormat::U64, Number::UnsignedInteger(0)),
		]);
		let mut event = EventNode::new(name, data);
		event.discriminators = vec![constant_discriminator(
			NumberFormat::U8,
			Number::UnsignedInteger(4),
		)];
		event
	}

	fn write_index(generated: &Path) {
		let events = generated.join("events");
		std::fs::create_dir_all(&events).expect("events dir");
		std::fs::write(events.join("index.ts"), "export * from \"./myEvent\";\n")
			.expect("index file");
	}

	#[test]
	fn emits_nothing_when_no_event_has_a_discriminator() {
		let mut root = read_idl("events_program.json");
		for event in &mut root.program.events {
			event.discriminators.clear();
		}
		let temporary = tempfile::tempdir().expect("temp dir");
		let generated = temporary.path().join("events_program/src/generated");
		write_index(&generated);

		emit_js_event_log_module(
			&generated,
			"events_program",
			&EventClientHistoryIndex::default(),
			&root,
		)
		.expect("no renderable events is not an error");
		assert!(!generated.join("events/logs.ts").exists());
	}

	#[test]
	fn module_index_failures_propagate() {
		let root = read_idl("events_program.json");
		let temporary = tempfile::tempdir().expect("temp dir");
		let generated = temporary.path().join("events_program/src/generated");
		// A directory where the barrel index should be makes the read fail after
		// the log module itself was written.
		std::fs::create_dir_all(generated.join("events/index.ts")).expect("blocked index");

		let error = emit_js_event_log_module(
			&generated,
			"events_program",
			&EventClientHistoryIndex::default(),
			&root,
		)
		.expect_err("an unreadable index must fail");
		assert!(matches!(error, CodamaError::HardenJavaScript { .. }));
		assert!(generated.join("events/logs.ts").exists());
	}

	#[cfg(unix)]
	#[test]
	fn module_index_write_failures_propagate() {
		use std::os::unix::fs::PermissionsExt;

		let root = read_idl("events_program.json");
		let temporary = tempfile::tempdir().expect("temp dir");
		let generated = temporary.path().join("events_program/src/generated");
		write_index(&generated);
		let index = generated.join("events/index.ts");
		std::fs::set_permissions(&index, std::fs::Permissions::from_mode(0o444))
			.expect("read-only index");

		let error = emit_js_event_log_module(
			&generated,
			"events_program",
			&EventClientHistoryIndex::default(),
			&root,
		)
		.expect_err("a read-only index must fail");
		// Restore permissions so the temporary directory can be removed.
		std::fs::set_permissions(&index, std::fs::Permissions::from_mode(0o644))
			.expect("restore index");
		assert!(matches!(error, CodamaError::HardenJavaScript { .. }));
	}

	#[test]
	fn events_without_a_discriminator_are_skipped() {
		let mut root = read_idl("events_program.json");
		root.program.events[0].discriminators.clear();

		let module = event_log_module(
			"events_program",
			&root.program.events,
			&EventClientHistoryIndex::default(),
		)
		.unwrap_or_else(|| panic!("one renderable event keeps the module"));
		assert!(module.contains("MyOtherEventEvent"));
		assert!(!module.contains("MyEventEvent"));
	}

	#[test]
	fn migratable_events_without_history_emit_a_current_only_decoder() {
		let root = read_idl("migrations_program.json");
		let module = event_log_module(
			"migrations_program",
			&root.program.events,
			&EventClientHistoryIndex::default(),
		)
		.unwrap_or_else(|| panic!("the migration event must emit a log module"));

		assert!(module.contains("carries no checked-in migration history"));
		assert!(module.contains("written by a different schema; regenerate this client"));
		assert!(!module.contains("PROJECTION_STEPS"));
	}

	#[test]
	fn event_facts_require_numeric_unsigned_constants() {
		let mut events = Vec::new();

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators = vec![DiscriminatorNode::Size(SizeDiscriminatorNode::new(4))];
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators = vec![DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				NumberTypeNode::le(NumberFormat::U8),
				ValueNode::String(StringValueNode::new("4")),
			),
			0,
		))];
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators = vec![DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				StringTypeNode::utf8(),
				ValueNode::Number(NumberValueNode::new(4_u8)),
			),
			0,
		))];
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators = vec![DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				NumberTypeNode::le(NumberFormat::F32),
				ValueNode::Number(NumberValueNode::new(4_u8)),
			),
			0,
		))];
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators = vec![DiscriminatorNode::Constant(ConstantDiscriminatorNode::new(
			ConstantValueNode::new(
				NumberTypeNode::le(NumberFormat::U8),
				ValueNode::Number(NumberValueNode::new(-4_i8)),
			),
			0,
		))];
		events.push(event);

		let histories = EventClientHistoryIndex::default();
		for event in &events {
			let label = format!("event `{}`", event.name.as_ref());
			assert!(
				event_facts(event, &histories).is_none(),
				"{label} has no facts"
			);
		}
	}

	#[test]
	fn event_facts_require_a_numeric_unsigned_envelope() {
		let mut events = Vec::new();

		// Non-struct event data has no envelope at all.
		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.data = Box::new(TypeNode::Bytes(codama_nodes::BytesTypeNode::new()));
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[0].r#type = Box::new(TypeNode::PublicKey(PublicKeyTypeNode::new()));
		}
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[0].default_value =
				Box::new(Some(ValueNode::String(StringValueNode::new("4"))));
		}
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[1].r#type = Box::new(TypeNode::PublicKey(PublicKeyTypeNode::new()));
		}
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[1].default_value =
				Box::new(Some(ValueNode::String(StringValueNode::new("1"))));
		}
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[1].r#type =
				Box::new(TypeNode::Number(NumberTypeNode::le(NumberFormat::F32)));
		}
		events.push(event);

		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields[1].default_value =
				Box::new(Some(ValueNode::Number(NumberValueNode::new(-1_i8))));
		}
		events.push(event);

		// A discriminator constant is required for an envelope.
		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		event.discriminators.clear();
		events.push(event);

		// The version field must exist.
		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields.truncate(1);
		}
		events.push(event);

		// The version field appearing before the discriminator is not an envelope.
		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			data.fields.swap(0, 1);
		}
		events.push(event);

		let histories = EventClientHistoryIndex::default();
		for event in &events {
			let label = format!("event `{}`", event.name.as_ref());
			let facts = event_facts(event, &histories);
			assert!(
				facts.is_none() || facts.and_then(|facts| facts.envelope).is_none(),
				"{label} must not produce an envelope",
			);
		}

		// Unrelated defaulted fields are skipped while scanning the envelope.
		let mut event =
			envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
		if let TypeNode::Struct(data) = event.data.as_mut() {
			let mut note = number_field("note", NumberFormat::U8, Number::UnsignedInteger(7));
			note.default_value_strategy = None;
			data.fields.insert(1, note);
		}
		let facts = event_facts(&event, &histories)
			.unwrap_or_else(|| panic!("skipped fields keep the envelope"));
		assert!(facts.envelope.is_some());
	}

	#[test]
	fn event_discriminator_widths_map_to_their_byte_lengths() {
		let histories = EventClientHistoryIndex::default();
		for (format, number, width) in [
			(NumberFormat::U8, Number::UnsignedInteger(4), 1),
			(NumberFormat::U16, Number::UnsignedInteger(0x0102), 2),
			(NumberFormat::U32, Number::UnsignedInteger(0x0102_0304), 4),
			(
				NumberFormat::U64,
				Number::UnsignedInteger(0x0102_0304_0506_0708),
				8,
			),
		] {
			let mut event =
				envelope_event("valueChanged", NumberFormat::U8, Number::UnsignedInteger(1));
			event.discriminators = vec![constant_discriminator(format, number)];
			let facts = event_facts(&event, &histories)
				.unwrap_or_else(|| panic!("discriminator width {width} must map"));
			assert_eq!(facts.discriminator.len(), width);
		}
	}

	#[test]
	fn name_helpers_handle_empty_names() {
		assert_eq!(lower_camel(""), "");
	}

	#[test]
	fn migration_aware_events_emit_a_log_entry_point_with_projection() {
		let root = read_idl("migrations_program.json");
		let mut histories = EventClientHistoryIndex::default();
		let history = migrations_history();
		histories.insert_for_test(history);

		let module = event_log_module("migrations_program", &root.program.events, &histories)
			.unwrap_or_else(|| panic!("the migration event must emit a log module"));

		assert!(module.contains("export function parseMigrationsProgramEventsFromLogs("));
		assert!(module.contains("export function normalizeValueChangedEventEvent("));
		assert!(module.contains("export function parseValueChangedEventEventFromLog("));
		assert!(module.contains("getValueChangedEventEventDecoder"));
		assert!(module.contains("getValueChangedEventEventDiscriminatorBytes"));
		assert!(module.contains("from: 0,"));
		assert!(module.contains("to: 1,"));
		assert!(module.contains("sourcePayloadSize: 8"));
		assert!(module.contains("destinationPayloadSize: 10"));
		assert!(module.contains("moves: [[0, 0, 8]]"));
		assert!(module.contains("wasMigrated: true"));
		assert!(module.contains("upgrade this client"));
		assert!(module.contains("manual, so only an on-chain projection"));
	}

	#[test]
	fn events_without_history_emit_current_layout_decoding_only() {
		let root = read_idl("events_program.json");
		let module = event_log_module(
			"events_program",
			&root.program.events,
			&EventClientHistoryIndex::default(),
		)
		.unwrap_or_else(|| panic!("events must emit a log module"));

		assert!(module.contains("export function normalizeMyEventEvent("));
		assert!(module.contains("): DecodedMyEventEvent {"));
		assert!(module.contains(
			"return { name: \"myEvent\", data: getMyEventEventDecoder().decode(bytes) };"
		));
		assert!(module.contains("export function parseMyOtherEventEventFromLog("));
		assert!(module.contains("getMyEventEventDiscriminatorBytes"));
		assert!(module.contains("bytes[index] !== discriminatorBytes[index]"));
		assert!(module.contains("parseEventsProgramEventsFromLogs("));
		assert!(!module.contains("wasMigrated"));
		assert!(!module.contains("PROJECTION_STEPS"));
	}

	#[test]
	fn program_without_events_emits_nothing() {
		let root = read_idl("counter_program.json");
		assert!(
			event_log_module(
				"counter_program",
				&root.program.events,
				&EventClientHistoryIndex::default(),
			)
			.is_none()
		);
	}

	#[test]
	fn writes_the_log_module_and_exports_it_idempotently() {
		let root = read_idl("events_program.json");
		let temporary = tempfile::tempdir().expect("temp dir");
		let generated = temporary.path().join("events_program/src/generated");
		let events_dir = generated.join("events");
		std::fs::create_dir_all(&events_dir).expect("events dir");
		let index_path = events_dir.join("index.ts");
		std::fs::write(&index_path, "export * from \"./myEvent\";\n").expect("index");

		let histories = EventClientHistoryIndex::default();
		emit_js_event_log_module(&generated, "events_program", &histories, &root)
			.expect("emit module");
		let module = std::fs::read_to_string(events_dir.join("logs.ts")).expect("logs module");
		assert!(module.contains("parseEventsProgramEventsFromLogs"));

		// A second pass must not duplicate the barrel export.
		emit_js_event_log_module(&generated, "events_program", &histories, &root)
			.expect("emit module twice");
		let index = std::fs::read_to_string(&index_path).expect("index");
		assert_eq!(index.matches("\"./logs\"").count(), 1);
	}

	#[test]
	fn programs_without_events_write_nothing() {
		let root = read_idl("counter_program.json");
		let temporary = tempfile::tempdir().expect("temp dir");
		let generated = temporary.path().join("counter_program/src/generated");
		std::fs::create_dir_all(&generated).expect("generated dir");

		emit_js_event_log_module(
			&generated,
			"counter_program",
			&EventClientHistoryIndex::default(),
			&root,
		)
		.expect("no-op emit");
		assert!(!generated.join("events/logs.ts").exists());
	}

	#[test]
	fn version_helpers_cover_every_supported_width() {
		assert_eq!(version_read("bytes", 1, 1), "bytes[1]");
		assert_eq!(version_read("bytes", 1, 2), "bytes[1] | (bytes[2] << 8)",);
		assert!(version_read("bytes", 1, 4).contains("<< 24"));
		assert_eq!(version_write("out", "header", 7, 1), "out[header] = 7;");
		assert_eq!(
			version_write("out", "header", 7, 2),
			"out[header] = 7 & 0xff;\n\tout[header + 1] = (7 >> 8) & 0xff;",
		);
		assert!(version_write("out", "header", 7, 4).contains(">> 24"));
		assert_eq!(lower_camel("ValueChanged"), "valueChanged");
	}
}
