// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { relayCommand } from "./commands/relay.ts";
import { updateCommand } from "./commands/update.ts";
import { registerGlobals } from "./context.ts";
import { fetchCommand } from "./fetch.ts";

const program = registerGlobals(new Command())
	.name("migrations-program-cli")
	.version("0.1.0")
	.description("Command-line interface for migrationsProgram");
program.addCommand(updateCommand);
program.addCommand(relayCommand);
program.addCommand(fetchCommand);
program.parseAsync(process.argv);
