// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getInitInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const initCommand = registerGlobals(new Command("init"))
	.description("init")
	.requiredOption("--bump <bump>", "bump")
	.option(
		"--authority <authority>",
		"Pays for account creation and seeds the store PDA [default: payer]",
	)
	.requiredOption(
		"--store <store>",
		"The store PDA account (must be empty — not yet created)",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			bump: smallInteger("--bump", options.bump),
			authority: context.payer,
			store: pubkey("--store", options.store),
		};
		const instruction = getInitInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
