// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getTouchInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const touchCommand = registerGlobals(new Command("touch"))
	.description("touch")
	.option(
		"--authority <authority>",
		"The store's authority. Must sign [default: payer]",
	)
	.requiredOption(
		"--store <store>",
		"When present, the counter inside is incremented by one",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			authority: context.payer,
			store: pubkey("--store", options.store),
		};
		const instruction = getTouchInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
