// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getInitializeInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const initializeCommand = registerGlobals(new Command("initialize"))
	.description("initialize")
	.requiredOption("--config-bump <configBump>", "configBump")
	.requiredOption("--vault-bump <vaultBump>", "vaultBump")
	.requiredOption("--tree-bump <treeBump>", "treeBump")
	.requiredOption("--nullifiers-bump <nullifiersBump>", "nullifiersBump")
	.requiredOption("--custodians-bump <custodiansBump>", "custodiansBump")
	.requiredOption("--requesters-bump <requestersBump>", "requestersBump")
	.requiredOption("--log-bump <logBump>", "logBump")
	.requiredOption("--custodians <custodians>", "custodians")
	.option("--authority <authority>", "The `authority` account [default: payer]")
	.option(
		"--pool-config <poolConfig>",
		"The `pool_config` account [default: derived]",
	)
	.option(
		"--pool-vault <poolVault>",
		"The `pool_vault` account [default: derived]",
	)
	.option(
		"--merkle-tree <merkleTree>",
		"The `merkle_tree` account [default: derived]",
	)
	.option(
		"--nullifier-set <nullifierSet>",
		"The `nullifier_set` account [default: derived]",
	)
	.option(
		"--custodian-registry <custodianRegistry>",
		"The `custodian_registry` account [default: derived]",
	)
	.option(
		"--requester-registry <requesterRegistry>",
		"The `requester_registry` account [default: derived]",
	)
	.option(
		"--disclosure-log <disclosureLog>",
		"The `disclosure_log` account [default: derived]",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			configBump: smallInteger("--config-bump", options.configBump),
			vaultBump: smallInteger("--vault-bump", options.vaultBump),
			treeBump: smallInteger("--tree-bump", options.treeBump),
			nullifiersBump: smallInteger("--nullifiers-bump", options.nullifiersBump),
			custodiansBump: smallInteger("--custodians-bump", options.custodiansBump),
			requestersBump: smallInteger("--requesters-bump", options.requestersBump),
			logBump: smallInteger("--log-bump", options.logBump),
			custodians: base58("--custodians", options.custodians),
			authority: context.payer,
			poolConfig: options.poolConfig === undefined
				? undefined
				: pubkey("--pool-config", options.poolConfig),
			poolVault: options.poolVault === undefined
				? undefined
				: pubkey("--pool-vault", options.poolVault),
			merkleTree: options.merkleTree === undefined
				? undefined
				: pubkey("--merkle-tree", options.merkleTree),
			nullifierSet: options.nullifierSet === undefined
				? undefined
				: pubkey("--nullifier-set", options.nullifierSet),
			custodianRegistry: options.custodianRegistry === undefined
				? undefined
				: pubkey("--custodian-registry", options.custodianRegistry),
			requesterRegistry: options.requesterRegistry === undefined
				? undefined
				: pubkey("--requester-registry", options.requesterRegistry),
			disclosureLog: options.disclosureLog === undefined
				? undefined
				: pubkey("--disclosure-log", options.disclosureLog),
		};
		const instruction = await getInitializeInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
