// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getRegisterRequesterInstruction } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const registerRequesterCommand = registerGlobals(
	new Command("register_requester"),
)
	.description("registerRequester")
	.requiredOption("--requester <requester>", "requester")
	.requiredOption("--max-tier <maxTier>", "maxTier")
	.option("--authority <authority>", "The `authority` account [default: payer]")
	.requiredOption("--pool-config <poolConfig>", "The `pool_config` account")
	.requiredOption(
		"--requester-registry <requesterRegistry>",
		"The `requester_registry` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			requester: pubkey("--requester", options.requester),
			maxTier: smallInteger("--max-tier", options.maxTier),
			authority: context.payer,
			poolConfig: pubkey("--pool-config", options.poolConfig),
			requesterRegistry: pubkey(
				"--requester-registry",
				options.requesterRegistry,
			),
		};
		const instruction = getRegisterRequesterInstruction(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
