// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getResolveChallengeInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const resolveChallengeCommand = registerGlobals(
	new Command("resolve_challenge"),
)
	.description("resolveChallenge")
	.requiredOption(
		"--approve <approve>",
		"Nonzero resolves in the requester's favor (execution may proceed);",
	)
	.option(
		"--pool-config <poolConfig>",
		"The `pool_config` account [default: derived]",
	)
	.requiredOption(
		"--disclosure-request <disclosureRequest>",
		"The `disclosure_request` account",
	)
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			approve: smallInteger("--approve", options.approve),
			authority: context.payer,
			poolConfig: options.poolConfig === undefined
				? undefined
				: pubkey("--pool-config", options.poolConfig),
			disclosureRequest: pubkey(
				"--disclosure-request",
				options.disclosureRequest,
			),
		};
		const instruction = await getResolveChallengeInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
