// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { getWithdrawInstructionAsync } from "../client";
import {
	base58,
	base58Vec,
	bigInteger,
	CliContext,
	pubkey,
	registerGlobals,
	smallInteger,
} from "../context";

export const withdrawCommand = registerGlobals(new Command("withdraw"))
	.description("withdraw")
	.requiredOption("--nullifier <nullifier>", "nullifier")
	.requiredOption("--root <root>", "root")
	.requiredOption("--proof-a <proofA>", "proofA")
	.requiredOption("--proof-b <proofB>", "proofB")
	.requiredOption("--proof-c <proofC>", "proofC")
	.requiredOption("--pool-config <poolConfig>", "The `pool_config` account")
	.option(
		"--pool-vault <poolVault>",
		"The `pool_vault` account [default: derived]",
	)
	.requiredOption("--merkle-tree <merkleTree>", "The `merkle_tree` account")
	.requiredOption(
		"--nullifier-set <nullifierSet>",
		"The `nullifier_set` account",
	)
	.requiredOption(
		"--verifying-key-account <verifyingKeyAccount>",
		"The `verifying_key_account` account",
	)
	.requiredOption("--recipient <recipient>", "The `recipient` account")
	.action(async (options) => {
		const context = await CliContext.create(options);
		const input = {
			nullifier: base58("--nullifier", options.nullifier),
			root: base58("--root", options.root),
			proofA: base58("--proof-a", options.proofA),
			proofB: base58("--proof-b", options.proofB),
			proofC: base58("--proof-c", options.proofC),
			poolConfig: pubkey("--pool-config", options.poolConfig),
			poolVault: options.poolVault === undefined
				? undefined
				: pubkey("--pool-vault", options.poolVault),
			merkleTree: pubkey("--merkle-tree", options.merkleTree),
			nullifierSet: pubkey("--nullifier-set", options.nullifierSet),
			verifyingKeyAccount: pubkey(
				"--verifying-key-account",
				options.verifyingKeyAccount,
			),
			recipient: pubkey("--recipient", options.recipient),
		};
		const instruction = await getWithdrawInstructionAsync(
			...[input],
			{ programAddress: context.programAddress },
		);
		await context.send(instruction);
	});
