// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/account_realloc_program.dart';

final class InitializeCommand extends Command<void> {
  InitializeCommand() {
    argParser
      ..addOption('bump', mandatory: true, help: "bump")
      ..addOption('authority', mandatory: false, help: "Funds creation and becomes the sample's resize authority [default: payer]")
      ..addOption('sample', mandatory: false, help: "Empty PDA derived from `[b\"sample\", authority]` [default: derived]");
  }

  @override
  String get name => 'initialize';

  @override
  String get description => "Creates the per-authority sample PDA.";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = (results['authority'] as String?) != null
        ? pubkey('--authority', results['authority']! as String)
        : context.payerAddress;
    final sample = (results['sample'] as String?) != null
        ? pubkey('--sample', results['sample']! as String)
        : (await findSamplePda(
          seeds: SampleSeeds(authority: authority),
          programAddress: context.programAddress,
        )).$1;
    final bumpValue = integer('--bump', results['bump']! as String);
    final instruction = getInitializeInstruction(
      programAddress: context.programAddress,
      authority: authority,
      sample: sample,
      systemProgram: Address('11111111111111111111111111111111'),
      bump: bumpValue,
    );
    await context.send([instruction]);
  }
}
