// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import 'package:args/command_runner.dart';

import 'package:solana_kit_address/solana_kit_address.dart';

import '../context.dart';
import 'package:pina_codama_clients/account_realloc_program.dart';

final class Realloc2Command extends Command<void> {
  Realloc2Command() {
    argParser
      ..addOption('len', mandatory: true, help: "len")
      ..addOption(
        'sample1',
        mandatory: false,
        help: "The sample1 account [default: derived]",
      )
      ..addOption(
        'sample2',
        mandatory: false,
        help: "The sample2 account [default: derived]",
      );
  }

  @override
  String get name => 'realloc2';

  @override
  String get description =>
      "Exercises Anchor's duplicate-reallocation guard.  Both sample accounts must be the same canonical PDA for the signer, so the instruction always rejects with `AccountDuplicateReallocs` before any account is resized. It is intentionally not a two-target mutation API.";

  @override
  Future<void> run() async {
    final results = argResults!;
    final context = await createContext(globalResults!);
    final authority = context.payerAddress;
    final sample1 = (results['sample1'] as String?) != null
        ? pubkey('--sample1', results['sample1']! as String)
        : (await findSamplePda(
            seeds: SampleSeeds(authority: authority),
            programAddress: context.programAddress,
          )).$1;
    final sample2 = (results['sample2'] as String?) != null
        ? pubkey('--sample2', results['sample2']! as String)
        : (await findSamplePda(
            seeds: SampleSeeds(authority: authority),
            programAddress: context.programAddress,
          )).$1;
    final lenValue = integer('--len', results['len']! as String);
    final instruction = getRealloc2Instruction(
      programAddress: context.programAddress,
      authority: authority,
      sample1: sample1,
      sample2: sample2,
      systemProgram: Address("11111111111111111111111111111111"),
      len: lenValue,
    );
    await context.send([instruction]);
  }
}
