//! This code was AUTOGENERATED by `pina_cli_renderer`.
//! Please DO NOT EDIT THIS FILE directly.
//! Regenerate it from the program IDL instead.
#![allow(
	dead_code,
	clippy::doc_lazy_continuation,
	clippy::empty_line_after_doc_comments,
	clippy::too_many_arguments
)]

//! Generated CLI for the `customErrorsProgram` program.

mod commands;
mod context;
use clap::Parser;
use clap::Subcommand;
use context::CliContext;
use solana_sdk::pubkey::Pubkey;

/// Command-line interface for customErrorsProgram
#[derive(Debug, Parser)]
#[command(name = "custom-errors-program-cli", version = env!("CARGO_PKG_VERSION"), propagate_version = true)]
struct Cli {
	/// RPC endpoint: `mainnet`, `devnet`, `testnet`, `localhost`, or an https URL.
	#[arg(
		short = 'u',
		long,
		global = true,
		default_value = "devnet",
		env = "SOLANA_URL"
	)]
	url: String,

	/// Payer keypair file in the standard Solana JSON byte-array format.
	#[arg(
		short = 'k',
		long,
		global = true,
		default_value = "~/.config/solana/id.json",
		env = "PINA_KEYPAIR"
	)]
	keypair: String,

	/// Override the on-chain program address.
	#[arg(long, global = true)]
	program_id: Option<String>,

	/// Simulate the transaction and print its logs instead of sending.
	#[arg(long, global = true)]
	simulate: bool,

	/// Print machine-readable JSON output.
	#[arg(long, global = true)]
	json: bool,

	#[command(subcommand)]
	command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
	Hello(commands::HelloArgs),

	HelloNoMsg(commands::HelloNoMsgArgs),

	HelloNext(commands::HelloNextArgs),

	RequireEq(commands::RequireEqArgs),

	RequireNeq(commands::RequireNeqArgs),

	RequireGt(commands::RequireGtArgs),

	RequireGte(commands::RequireGteArgs),
}

fn main() {
	let cli = Cli::parse();
	if let Err(error) = run(cli) {
		eprintln!("error: {error}");
		std::process::exit(1);
	}
}

fn run(cli: Cli) -> Result<(), context::CliError> {
	let program_address = match &cli.program_id {
		Some(value) => CliContext::pubkey("--program-id", value)?,
		None => Pubkey::from_str_const("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"),
	};
	let context = CliContext::new(
		&cli.url,
		&cli.keypair,
		program_address,
		cli.simulate,
		cli.json,
	)?;

	match cli.command {
		Command::Hello(args) => commands::hello::run(&context, args),
		Command::HelloNoMsg(args) => commands::hello_no_msg::run(&context, args),
		Command::HelloNext(args) => commands::hello_next::run(&context, args),
		Command::RequireEq(args) => commands::require_eq::run(&context, args),
		Command::RequireNeq(args) => commands::require_neq::run(&context, args),
		Command::RequireGt(args) => commands::require_gt::run(&context, args),
		Command::RequireGte(args) => commands::require_gte::run(&context, args),
	}
}
