// This code was AUTOGENERATED by `@pina-rs/codama-renderer-cli`.
// Please DO NOT EDIT THIS FILE directly.
// Regenerate it from the program IDL instead.

import { Command } from "commander";
import { fetchCounterState, findCounterPda } from "./client";
import { bigInteger, CliContext, pubkey, registerGlobals } from "./context";

export const fetchCommand = registerGlobals(new Command("fetch"))
	.description("Fetch and decode program accounts.")
	.addCommand(
		registerGlobals(new Command("counter-state"))
			.description(
				"On-chain counter state.\n\nThe `#[account]` macro generates:\n- A discriminator field (`CounterAccountType::CounterState`) as the first\nbyte.\n- A `CounterStateZc` storage view generated by `pinapod::PinaPod`.\n- `HasDiscriminator` linking this struct to\n`CounterAccountType::CounterState`.\n- `initialize` and `try_from_bytes` helpers for caller-owned storage.\n\nLayout (10 bytes total):\n```text\n| offset | size | field         |\n|--------|------|---------------|\n| 0      | 1    | discriminator |\n| 1      | 1    | bump          |\n| 2      | 8    | count (little-endian u64) |\n```",
			)
			.option(
				"--address <address>",
				"Account address; overrides PDA derivation.",
			)
			.requiredOption("--authority <authority>", "PDA seed `authority`.")
			.action(async (options) => {
				const context = await CliContext.create(options);
				const authority = pubkey("--authority", options.authority as string);
				const address = options.address ??
					(await findCounterPda({ authority }, {
						programAddress: context.programAddress,
					}))[0];
				const account = await fetchCounterState(context.rpc, address);
				printAccount(context.json, "counter-state", address, account.data);
			}),
	);

function printAccount(
	json: boolean,
	name: string,
	address: string,
	data: unknown,
): void {
	if (json) {
		console.log(JSON.stringify({ address, ...(data as object) }, null, "\t"));
		return;
	}
	console.log(`${name} ${address}`);
	const fields = data as Record<string, unknown>;
	for (const [key, value] of Object.entries(fields)) {
		console.log(`  ${key}: ${value}`);
	}
}
